apalache-mc/apalache

.envrc
3rdparty/install-local.sh
CONTRIBUTING.md
Makefile
docs/manual.md
test/tla/Assignments20200309.tla

This PR collections my suggestions and question as I work through the manual. I'm not quite finished yet, and my changes will benefit from a self-review prior to a final review, but I think there's already lots here that could benefit from feedback. I've tried to break it into logically distinct commits with messages that clearly explain the reasoning behind each change, so it might be worth reviewing by commit.

Suggested tweaks and elaborations to the manual

---

CHANGES.md

In preparation for releasing 0.7.0

Increment changelog section

---

script/release-0.7.0.txt

Just adding the changes file for this release.

Prepare for 0.7 release

---

script/release

Correct project name

---

CONTRIBUTING.md
docs/manual.md

Correct travis-ci URL

---

docs/manual.md

@istoilkovska pointed that there is no designated type for naturals. I have added a clarification in the manual.

Clarification on Naturals in the manual

---

CONTRIBUTING.md

The release was very smooth this week. I think all the steps are working and fully understood. Next release will be automatic :)

Update release process documentation

---

docs/adr/002adr-types.md
tla-types/src/main/scala/at/forsyte/apalache/tla/typecheck/CachingType1Parser.scala
tla-types/src/main/scala/at/forsyte/apalache/tla/typecheck/TlaType1.scala
tla-types/src/main/scala/at/forsyte/apalache/tla/typecheck/Type1Parser.scala
tla-types/src/main/scala/at/forsyte/apalache/tla/typecheck/TypeParserFactory.scala
tla-types/src/main/scala/at/forsyte/apalache/tla/typecheck/parser/DefaultType1Parser.scala
tla-types/src/main/scala/at/forsyte/apalache/tla/typecheck/parser/Type1Lexer.scala
tla-types/src/main/scala/at/forsyte/apalache/tla/typecheck/parser/Type1ParseError.scala
tla-types/src/main/scala/at/forsyte/apalache/tla/typecheck/parser/Type1TokenReader.scala
tla-types/src/main/scala/at/forsyte/apalache/tla/typecheck/parser/tokens.scala
tla-types/src/test/scala/at/forsyte/apalache/tla/typecheck/TestCachingType1Parser.scala
tla-types/src/test/scala/at/forsyte/apalache/tla/typecheck/TestDefaultType1Parser.scala
tla-types/src/test/scala/at/forsyte/apalache/tla/typecheck/TestTlaType1.scala
tla-types/src/test/scala/at/forsyte/apalache/tla/typecheck/TestType1Parser.scala

I will add more features to this PR later. But here is the first logical piece.
This PR contains a parser for Type System 1, as described in [ADR-002](https://github.com/informalsystems/apalache/blob/unstable/docs/adr/002adr-types.md).

Parser for the new types

---

tla-import/pom.xml

Update the latest version of surefire

---

tla-assignments/src/main/scala/at/forsyte/apalache/tla/assignments/AssignmentStrategyEncoder.scala
tla-assignments/src/main/scala/at/forsyte/apalache/tla/assignments/ManualAssignments.scala
tla-assignments/src/main/scala/at/forsyte/apalache/tla/assignments/SymbTransGenerator.scala
tla-assignments/src/test/scala/at/forsyte/apalache/tla/assignments/TestAssignmentStrategyEncoder.scala
tla-assignments/src/test/scala/at/forsyte/apalache/tla/assignments/TestManualAssignments.scala

Manual assignments

---

.envrc
.gitignore
Dockerfile
bin/apalache-mc
docs/manual.md
tla-bmcmt/pom.xml

Augments #230 with a few stray 3rdparty dir references.

Remove a few lingering 3rdparty references

---

README.md

The youtube videos on Apalache are hard to find. I have added them to the front page.

talks related to Apalache

---

tla-types/src/main/scala/at/forsyte/apalache/tla/typecheck/TlaType1.scala
tla-types/src/test/scala/at/forsyte/apalache/tla/typecheck/TestTlaType1.scala

Broken out of #244
This adds the raw changeset from #259
Original Author: Igor Konnov igor@informal.systems

Add TlaType1 methods for inspecting type variable names

---

tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/passes/UnrollPassImpl.scala

After some discussion, we've found caching to be unnecessary, so it has been disabled. Closes #273.

Disabled caching

---

pom.xml

Bump tla2tools to 1.7.0

---

tla-types/src/main/scala/at/forsyte/apalache/tla/typecheck/etc/EtcBuilder.scala

Originally authored by Igor Konnov <konnov@forsyte.at>
Broken out of #259

ETC-7: Add EtcBuilder module 

---

tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/passes/PreproPassImpl.scala
tlair/src/main/scala/at/forsyte/apalache/tla/lir/transformations/standard/FlatLanguagePred.scala
tlair/src/main/scala/at/forsyte/apalache/tla/lir/transformations/standard/KeraLanguagePred.scala

detailed error conditions and more details about individual preprocessing steps in `PreproPassImpl`.

better diagnostics in preprocessing

---

test/tla/Rec12.tla
test/tla/Rec2.tla
test/tla/Rec4.tla
test/tla/Rec5.tla
test/tla/Rec6.tla
test/tla/cli-integration-tests.md
tla-import/src/main/scala/at/forsyte/apalache/tla/imp/ModuleTranslator.scala
tla-import/src/test/scala/at/forsyte/apalache/tla/imp/TestSanyImporter.scala
tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/Unroller.scala

This PR introduces a temporary workaround for issue #130, which needs a fix in SANY

Workaround for issue #130

---

tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/RecFunDefAndRefRule.scala
tla-import/src/main/scala/at/forsyte/apalache/tla/imp/OpApplTranslator.scala
tla-import/src/main/scala/at/forsyte/apalache/tla/imp/OpDefTranslator.scala
tla-import/src/main/scala/at/forsyte/apalache/tla/imp/SubstTranslator.scala
tla-import/src/main/scala/at/forsyte/apalache/tla/imp/src/SaveToStoreTracker.scala
tla-import/src/main/scala/at/forsyte/apalache/tla/imp/src/SourceStore.scala
tla-import/src/test/scala/at/forsyte/apalache/tla/imp/TestSanyImporter.scala
tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/Desugarer.scala
tla-pp/src/test/scala/at/forsyte/apalache/tla/pp/TestDesugarer.scala
tlair/src/main/scala/at/forsyte/apalache/tla/lir/Builder.scala
tlair/src/main/scala/at/forsyte/apalache/tla/lir/io/PrettyWriter.scala
tlair/src/main/scala/at/forsyte/apalache/tla/lir/oper/TlaFunOper.scala
tlair/src/main/scala/at/forsyte/apalache/tla/lir/oper/TlaOper.scala
tlair/src/main/scala/at/forsyte/apalache/tla/lir/storage/SourceLocator.scala
tlair/src/test/scala/at/forsyte/apalache/tla/lir/io/TestPrettyWriter.scala

This PR fixes the parsing issues in #297 and #144.

Fix 297: add support for multi-argument recursive functions

---

tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/SymbStateDecoder.scala

fix #320: print the SMT model in comments rather than in plain output

---

docs/idiomatic/001assignments.md

I believe the old was wrong. Not sure. Should be checked.

grammar fix

---

docs/adr/002adr-types.md

This PR synchronizes the notation in `002adr-types.md`: the operator `:>` is replaced with `##`.

replace ":>" with "##"

---

test/tla/APAbcastByz.tla
test/tla/cli-integration-tests.md
tla-assignments/src/main/scala/at/forsyte/apalache/tla/assignments/Reordering.scala
tla-assignments/src/main/scala/at/forsyte/apalache/tla/assignments/SymbTransGenerator.scala
tla-assignments/src/main/scala/at/forsyte/apalache/tla/assignments/passes/PrimingPassImpl.scala
tla-assignments/src/test/scala/at/forsyte/apalache/tla/assignments/TestReordering.scala
tla-assignments/src/test/scala/at/forsyte/apalache/tla/assignments/TestSymbTransGenerator.scala

Reordered assignments

---

test/tla/cli-integration-tests.md

Wrong error expectation

---

README.md

I just realized that people may come to our page without knowing TLA+ at all. So I have updated the front page and added links to Leslie's page as well as links to the examples.

refreshed README.md

---

mod-distribution/pom.xml
mod-infra/pom.xml
mod-tool/pom.xml
pom.xml
tla-assignments/pom.xml
tla-bmcmt/pom.xml
tla-import/pom.xml
tla-pp/pom.xml
tla-types/pom.xml
tlair/pom.xml

Bump version to 0.8.1-SNAPSHOT

---

.github/workflows/main.yml

Ensures that we have a properly compileable book before we allow merging
into CI.

Build the mdbook in CI

---

mod-tool/src/main/scala/at/forsyte/apalache/tla/Tool.scala

fix 288: two more parameters for compatibility with TLC

---

test/tla/NonNullaryLet.tla
test/tla/cli-integration-tests.md
tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/OperAppToLetInDef.scala

Name-wrapping fix

---

README.md

Closes #434
Starts documenting the general structure of our landing site.

Document site structure

---

README.md

Document website and how to update it

---

LICENSE
NOTICE
src/assembly/bin.xml

including {Apalache,Typing.tla}, README.md, LICENSE, and NOTICE

---

README.md

fix the link to features

---

pom.xml

The docs led me astry, and the nonsense config was just ignored.
Igor fixed it.

Fix scalafmt config

---

.github/workflows/main.yml
Makefile
docs/src/apalache/installation/source.md

This is meant to be a speedy build of the jar without running tests,
but I had the flags wrong I think.

Correct flags on apalache-jar make target

---

test/tla/cli-integration-tests.md
test/tla/factorization.tla

A simple test that works fast in Apalache and takes ages in TLC

add factorization to the tests

---

tla-assignments/src/main/scala/at/forsyte/apalache/tla/assignments/Reordering.scala
tla-assignments/src/main/scala/at/forsyte/apalache/tla/assignments/passes/PrimingPassImpl.scala
tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/analyses/ExpansionMarker.scala
tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/analyses/SkolemizationMarker.scala
tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/AbstractTransformer.scala
tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/Cacher.scala
tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/ConstAndDefRewriter.scala
tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/ConstSimplifier.scala
tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/Normalizer.scala
tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/OperAppToLetInDef.scala
tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/Unroller.scala
tla-types/src/main/scala/at/forsyte/apalache/tla/typecheck/integration/TypeRewriter.scala
tlair/src/main/scala/at/forsyte/apalache/tla/lir/TlaDecl.scala
tlair/src/main/scala/at/forsyte/apalache/tla/lir/transformations/standard/IncrementalRenaming.scala

Hotfix: TlaOperDecl.isRecursive propagation

---

tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/SubstRule.scala
tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/Desugarer.scala
tla-pp/src/test/scala/at/forsyte/apalache/tla/pp/TestDesugarer.scala

This PR fixes a few bugs that I ran into while preparing a tutorial.

Integrating types 9: a few bugfixes

---

docs/src/apalache/principles.md
tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/config/CheckerExceptionAdapter.scala

Correct link to idiom guidance on assignments

---

docs/src/lang/sets.md
docs/src/lang/standard-operators.md

A few small fixes in the language manual

A few fixes in the language manual

---

docs/src/lang/logic.md

Made some fixes, removed `frozenset` where possible and converted the Python examples to the doctest format.

Logic chapter in manual: Some fixes and use doctest format

---

CHANGES.md
UNRELEASED.md
mod-distribution/pom.xml
mod-infra/pom.xml
mod-tool/pom.xml
pom.xml
tla-assignments/pom.xml
tla-bmcmt/pom.xml
tla-import/pom.xml
tla-pp/pom.xml
tla-types/pom.xml
tlair/pom.xml

This reverts commit 0a077717366b5ded19fe312f1c60fde58e1fa774.
Release PR #747 was cut after adding an additional merge commmit, which
breaks the release processes.

Revert "[release] 0.15.3 (#747)"

---

docs/src/adr/006rfc-unit-testing.md

fix a link and add contacts in rfc006

---

docs/src/adr/006rfc-unit-testing.md

I've accidentally pushed a malformed link that broke all links

fix a broken link 2

---

docs/src/SUMMARY.md

Fix broken links in manual overview

---

UNRELEASED.md
tla-import/src/main/scala/at/forsyte/apalache/io/json/JsonToTla.scala
tla-import/src/main/scala/at/forsyte/apalache/tla/imp/passes/SanyParserPassImpl.scala
tla-types/src/main/scala/at/forsyte/apalache/tla/typecheck/passes/EtcTypeCheckerPassImpl.scala
tlair/src/main/scala/at/forsyte/apalache/tla/lir/io/TlaType1TagPrinter.scala

Replaced calls to old JSON reader/writer

---

docs/internal/user-stories/user-interview-questions.md

Adds a single question to user interview Qs.

Add background question to user stories

---

tla-assignments/src/main/scala/at/forsyte/apalache/tla/assignments/SmtFreeSymbolicTransitionExtractor.scala
tla-assignments/src/main/scala/at/forsyte/apalache/tla/assignments/passes/TransitionPassImpl.scala
tla-assignments/src/test/scala/at/forsyte/apalache/tla/assignments/TestSmtFreeSTE.scala

- ~[ ] Tests added for any new code~
- ~[ ] Entry added to [UNRELEASED.md](./UNRELEASED.md) for any new functionality~
This PR, on its own, does not add or remove visible functionality. It addresses point (1) of #846. Due to the order of passes, the generalizations cover scenarios which are currently impossible, but will be relevant in phase (2) of #846.

Adapt assignment solving for non-nullary and recursive operators

---

docs/src/adr/002adr-types.md

Add pointers to the tutorial and HOWTO on Snowcat.

add pointers to the tutorial and howto right in RFC002

---

index.md

cosmetic changes to the website
- ~[ ] Tests added for any new code~
- ~[ ] Ran `make fmt-fix` (or had formatting run automatically on all files edited)~
- ~[ ] Entry added to [UNRELEASED.md](./UNRELEASED.md) for any new functionality~

refactored the front page a bit

---

.gitignore
UNRELEASED.md
src/tla/Apalache.tla
test/tla/FoldSeqFun.tla
test/tla/FoldSeqFunBad.tla
test/tla/FoldSeqSeq.tla
test/tla/FoldSeqSeqBad.tla
test/tla/FoldSeqSet.tla
test/tla/FoldSeqSetBad.tla
test/tla/FoldSetFun.tla
test/tla/FoldSetFunBad.tla
test/tla/FoldSetSeq.tla
test/tla/FoldSetSeqBad.tla
test/tla/FoldSetSet.tla
test/tla/FoldSetSetBad.tla
test/tla/Folds.tla
test/tla/cli-integration-tests.md
tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/SymbStateRewriterImpl.scala
tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/FoldSeqRule.scala
tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/FoldSetRule.scala
tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/util/TlaExUtil.scala
tla-bmcmt/src/test/scala/at/forsyte/apalache/tla/bmcmt/TestSymbStateRewriterFoldSeq.scala
tla-bmcmt/src/test/scala/at/forsyte/apalache/tla/bmcmt/TestSymbStateRewriterFoldSet.scala
tla-io/src/main/scala/at/forsyte/apalache/tla/imp/StandardLibrary.scala
tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/FoldOperLetinizer.scala
tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/passes/InlinePassImpl.scala
tla-types/src/main/scala/at/forsyte/apalache/tla/typecheck/etc/ToEtcExpr.scala
tlair/src/main/scala/at/forsyte/apalache/tla/lir/oper/ApalacheOper.scala
tlair/src/main/scala/at/forsyte/apalache/tla/lir/transformations/standard/KeraLanguagePred.scala

Support for FoldSet and FoldSeq

---

docs/src/apalache/features.md

closes #889 and updates the feature list

---

test/tla/FoldSetInInit.tla
test/tla/cli-integration-tests.md

A regression test for the recently fixed bug

add regression test

---

docs/src/apalache/principles.md

closes #821: fix the chapter on principles

---

UNRELEASED.md
test/tla/NoVars.tla
test/tla/cli-integration-tests.md
tla-assignments/src/main/scala/at/forsyte/apalache/tla/assignments/SmtFreeSymbolicTransitionExtractor.scala

Allow specs with 0 variables

---

UNRELEASED.md
test/tla/SelectSeqTests.tla
test/tla/cli-integration-tests.md
tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/SelectSeqAsFold.scala
tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/passes/DesugarerPassImpl.scala

SelectSeq rewritten as fold

---

docs/src/HOWTOs/MsgSetNew.tla
docs/src/HOWTOs/MsgSetOld.tla
docs/src/HOWTOs/howto-handle-messages.md
docs/src/SUMMARY.md
docs/src/idiomatic/003record-sets.md
docs/src/idiomatic/index.md

Added a short tutorial on how to avoid using a set of mixed record types, and use a model of a disjoint union instead, as proposed by @shonfeder.

Idiom: Sets of records

---

docs/src/SUMMARY.md
docs/src/lang/apalache-operators.md

- ~[ ] Tests added for any new code~
- ~[ ] Ran `make fmt-fix` (or had formatting run automatically on all files edited)~
- ~[ ] Entry added to [UNRELEASED.md](./UNRELEASED.md) for any new functionality~
closes #886

Manual entry for Apalache-specific operators

---

UNRELEASED.md
docs/src/apalache/profiling.md
test/tla/cli-integration-tests.md
test/tla/powerset.tla
tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/passes/BoundedCheckerPassImpl.scala

fix the profiler output: a call to rewriter.dispose was missing

---

mod-infra/src/main/scala/at/forsyte/apalache/infra/passes/PassOptions.scala
mod-infra/src/main/scala/at/forsyte/apalache/infra/passes/WriteablePassOptions.scala
tla-assignments/src/main/scala/at/forsyte/apalache/tla/assignments/passes/PrimingPassImpl.scala
tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/passes/BoundedCheckerPassImpl.scala
tla-io/src/main/scala/at/forsyte/apalache/tla/imp/passes/SanyParserPassImpl.scala
tla-io/src/main/scala/at/forsyte/apalache/tla/imp/src/SourceStore.scala
tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/passes/ConfigurationPassImpl.scala
tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/passes/InlinePassImpl.scala
tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/passes/PreproPassImpl.scala
tla-types/pom.xml
tla-types/src/main/scala/at/forsyte/apalache/tla/typecheck/passes/EtcTypeCheckerPassImpl.scala

Towards #1064
See the individual commits for details on each fix.

Fix 3 compiler warnings

---

UNRELEASED.md
test/tla/PolyFold.tla
test/tla/cli-integration-tests.md
tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/LambdaTypeInliner.scala
tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/LetInTypeSynchronizer.scala
tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/passes/InlinePassImpl.scala

If #1088 is closed, this fix also closes issue #1085 in the general case.

Fixed handling of polymorphic operator types in folds

---

docs/src/apalache/known-issues.md
tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/IntDotDotRule.scala

When using dynamic ranges, the solver should fail, but with a normal error message, instead of a stack trace.
Closes #923
closes #425

Changed range error message

---

UNRELEASED.md
test/tla/cli-integration-tests.md
tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/config/CheckerExceptionAdapter.scala
tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/exceptions.scala
tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/ChooseRule.scala
tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/FoldSeqRule.scala
tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/FoldSetRule.scala
tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/SetCtorRule.scala
tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/SetCupRule.scala
tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/SetUnionRule.scala
tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/types/package.scala
tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/Desugarer.scala
tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/ExprOptimizer.scala
tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/InlinerOfUserOper.scala
tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/LambdaTypeInliner.scala
tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/OperAppToLetInDef.scala
tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/ParameterNormalizer.scala
tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/SelectSeqAsFold.scala
tla-types/src/main/scala/at/forsyte/apalache/tla/typecheck/TypeCheckerTool.scala
tla-types/src/main/scala/at/forsyte/apalache/tla/typecheck/etc/ConstSubstitution.scala
tla-types/src/main/scala/at/forsyte/apalache/tla/typecheck/etc/EtcTypeChecker.scala
tla-types/src/main/scala/at/forsyte/apalache/tla/typecheck/etc/ToEtcExpr.scala
tla-types/src/main/scala/at/forsyte/apalache/tla/typecheck/exceptions.scala
tla-types/src/main/scala/at/forsyte/apalache/tla/typecheck/integration/TypeWatchdogTransformationListener.scala
tla-types/src/main/scala/at/forsyte/apalache/tla/typecheck/passes/LoggingTypeCheckerListener.scala
tla-types/src/test/scala/at/forsyte/apalache/tla/typecheck/etc/TestTypeCheckerTool.scala
tlair/src/main/scala/at/forsyte/apalache/tla/lir/TlaType1.scala
tlair/src/main/scala/at/forsyte/apalache/tla/lir/TypedPredefs.scala
tlair/src/main/scala/at/forsyte/apalache/tla/lir/exceptions.scala
tlair/src/main/scala/at/forsyte/apalache/tla/lir/identifiers.scala

closes #1090. Merging `TypeException` and `TypingException`. Many files affected.

closes #1090: merge TypeException and TypingException

---

tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/TypeSubstitutor.scala

MWE was difficult to determine, #359 should come with a test suite for this eventually.

TypeSub ignored OperDecl tags

---

tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/smt/Z3SolverContext.scala

To avoid duplicate declarations of empty sets, they are now cached and reused. Instead of the initially intended `define-const` macro, the already used `declare-const` is used, since Z3''s Java API does not (apparently) expose `define-const`. Closes #1100.

Add cache for empty set declarations

---

test/tla/LamportMutexTyped.tla
test/tla/MC_LamportMutexTyped.tla
test/tla/cli-integration-tests.md

Add Lamport's mutex, as it is an interesting example for typechecking records.

add Lamport's mutex

---

tla-io/pom.xml
tla-io/src/main/scala/at/forsyte/apalache/io/OutputManager.scala

We don't need it anymore now that we're using PureConfig for the
configuration management.
-------

Remove snakeyaml dependency

---

index.md

Update the website with the latest tutorials

add the latest talks

---

README.md

add link to the latest tutorial

---

UNRELEASED.md
mod-tool/src/main/scala/at/forsyte/apalache/tla/Tool.scala
mod-tool/src/main/scala/at/forsyte/apalache/tla/tooling/opt/TypeCheckCmd.scala
test/tla/cli-integration-tests.md
tla-io/src/main/scala/at/forsyte/apalache/tla/imp/passes/SanyParserPassImpl.scala
tla-io/src/main/scala/at/forsyte/apalache/tla/imp/utils.scala
tla-types/src/main/scala/at/forsyte/apalache/tla/typecheck/passes/EtcTypeCheckerPassImpl.scala
tlair/src/main/scala/at/forsyte/apalache/tla/lir/Builder.scala

Also fixes decoding of recursive functions (untracked bug).
Closes #1284

Implement `--output` for `typecheck`

---

UNRELEASED.md
tla-io/src/main/scala/at/forsyte/apalache/io/lir/ItfCounterexampleWriter.scala
tla-io/src/test/scala/at/forsyte/apalache/io/lir/TestItfCounterexampleWriter.scala

Fix the ITF output for singleton functions

---

.scalafmt.conf
UNRELEASED.md
tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/caches/IntRangeCache.scala
tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/SetCtorRule.scala
tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/SetCupRule.scala
tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/SetFilterRule.scala
tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/SetUnionRule.scala
tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/aux/CherryPick.scala
tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/aux/PowSetCtor.scala
tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/util/ConsChainUtil.scala

Fixes `consChain` recursion

---

UNRELEASED.md
test/tla/MegaSpec1.tla
test/tla/cli-integration-tests.md
tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/passes/PreproPassPartial.scala

`PreproPassParial` consistency check fix

---

tla-pp/src/test/scala/at/forsyte/apalache/tla/pp/TestKeramelizer.scala

Closes #1364
This is a workaround for when `IrGenerators` constructs an ill-typed expressions that fails in Keramelizer, as in #1364.

Catch `MalformedTlaError` in property-based tests of Keramelizer

---

tla-assignments/src/main/scala/at/forsyte/apalache/tla/assignments/SmtFreeSymbolicTransitionExtractor.scala

Minor spacing tweak

---

test/tla/TestHash2.tla
test/tla/cli-integration-tests.md

This is an interesting example that appeared in the [TLA+ user group](https://groups.google.com/g/tlaplus/c/cD1bhMcHxqA).  Adding it as an integration test.

add an interesting test

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

Given that we have a labeling system, I think that these bracketed words
in the title are redundant and a bit noisy. So I'm suggesting removing
them.
-------

Remove {[BUG],[FEATURE]} from issue template title

---

docs/src/tutorials/entry-tutorial.md
test/tla/bin-search/BinSearch1.tla.patch
test/tla/bin-search/BinSearch10.tla.patch
test/tla/bin-search/BinSearch2.tla.patch
test/tla/bin-search/BinSearch3.tla.patch
test/tla/bin-search/BinSearch4.tla.patch
test/tla/bin-search/BinSearch5.tla.patch
test/tla/bin-search/BinSearch6.tla.patch
test/tla/bin-search/BinSearch7.tla.patch
test/tla/bin-search/BinSearch8.tla.patch
test/tla/bin-search/BinSearch9.tla.patch
test/tla/bin-search/MC10_8.tla.patch
test/tla/bin-search/MC3_8.tla.patch
test/tla/bin-search/MC4_8.tla.patch
test/tla/bin-search/MC5_8.tla.patch
test/tla/bin-search/MC6_8.tla.patch
test/tla/bin-search/MC7_8.tla.patch
test/tla/bin-search/MC8_8.tla.patch
test/tla/bin-search/MC9_8.tla.patch
test/tla/bin-search/mk-diffs.sh

This PR adds references to the specs in the tutorial, as well as diffs (for a future PR).

Add references to the source files and diffs

---

docs/src/tutorials/entry-tutorial.md

Add references to patches in the tutorial.

References to file diffs

---

README.md

Closes #1435. This PR fixes two broken links and adds a link to the latest tutorial.

fix the links on the landing page

---

tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/SetMembershipSimplifier.scala
tla-pp/src/test/scala/at/forsyte/apalache/tla/pp/TestSetMembershipSimplifier.scala

Add support for `\X` in `SetMembershipSimplifier`

Simplify tuples in TypeOK

---

UNRELEASED.md
test/tla/NestedCallByName.tla
test/tla/cli-integration-tests.md
tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/CallByNameOperatorEmbedder.scala

Fix for improper recursion in embedding

---

tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/smt/Z3SolverContext.scala
tla-io/src/main/scala/at/forsyte/apalache/io/json/impl/UJsonFactory.scala
tlair/src/main/scala/at/forsyte/apalache/tla/lir/TestingPredefs.scala
tlair/src/main/scala/at/forsyte/apalache/tla/lir/TypedPredefs.scala
tlair/src/main/scala/at/forsyte/apalache/tla/lir/UntypedPredefs.scala
tlair/src/main/scala/at/forsyte/apalache/tla/lir/convenience/convenience.scala

Towards https://github.com/informalsystems/apalache/issues/1064. Closes #1473.
Fixes all current compiler feature warnings.
Rationale for each fix in the commit message.

Fix compiler feature warnings

---

mod-tool/src/main/scala/at/forsyte/apalache/tla/tooling/opt/General.scala

Replace `log.smt` with `profile.csv` in `--smtprof` help output.

Fix `--help` of `--smtprof`

---

docs/src/SUMMARY.md
docs/src/adr/017pdr-temporal.md

Given the comments by @thpani and the team, this PR downgrades ADR017 into PDR017, a preliminary design record. It also includes the comments by @thpani that were made after the merge in https://github.com/informalsystems/apalache/pull/1583.

refactor ADR017 into PDR017

---

test/tla/TestInlining.tla

A tiny PR that adds one more test case for inlining with lambdas

add a test case for lambdas

---

test/tla/Test1623.cfg
test/tla/Test1623.tla
test/tla/cli-integration-tests.md
tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/passes/ConfigurationPassImpl.scala

Implement overriding constants from `.cfg` as apalache-native CInit

---

UNRELEASED.md
mod-tool/src/main/scala/at/forsyte/apalache/tla/Tool.scala

~- [ ] Tests added for any new code~
~- [ ] Documentation added for any new functionality~

Move version number printing and include in detailed log

---

docs/src/apalache/index.md
docs/src/apalache/installation/docker.md

Closes #1657
This small fix addresses some shortcomings in the docs for the
docker installation. Thanks to feedback from @tesnimab for pointing
out the issues.

Update docs on docker-based installation

---

docs/src/lang/apalache-operators.md

This PR fixes a broken link to the `folds.md` file in the docs.

Fix broken link to folds' documention

---

docs/src/idiomatic/007if-then-else.md
docs/src/idiomatic/index.md
mod-infra/src/main/scala/at/forsyte/apalache/infra/passes/ToolModule.scala

This just updates my name across some documentation.

Update Gabriela's name

---

tla-types/src/main/scala/at/forsyte/apalache/tla/typecomp/ScopedBuilder.scala
tla-types/src/main/scala/at/forsyte/apalache/tla/typecomp/TypeComputationFactory.scala
tla-types/src/main/scala/at/forsyte/apalache/tla/typecomp/signatures/SeqOperSignatures.scala
tla-types/src/main/scala/at/forsyte/apalache/tla/typecomp/subbuilder/SeqBuilder.scala
tla-types/src/main/scala/at/forsyte/apalache/tla/typecomp/unsafe/UnsafeSeqBuilder.scala
tla-types/src/test/scala/at/forsyte/apalache/tla/typecomp/BuilderTest.scala
tla-types/src/test/scala/at/forsyte/apalache/tla/typecomp/TestSeqBuilder.scala

Typed Builder implementation Part 2: Sequences

---

test/tla/Bug1735.tla
test/tla/TestCommunityFunctions.tla
test/tla/cli-integration-tests.md
tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/SetInRule.scala

BUGFIX: `f \in [S -> T]` didn't check `S \subseteq DOMAIN f`

---

test/tla/cli-integration-tests.md
tla-types/src/main/scala/at/forsyte/apalache/tla/typecheck/etc/ToEtcExpr.scala

See https://github.com/informalsystems/apalache/pull/1717/files#r868373912
-------

Improve type error message when applying equality

---

test/tla/cli-integration-tests.md
tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/SetInRuleWithArrays.scala

Similar to #1736. Closes #1735.

Fix domain check of set memberhsip of function sets in the arrays encoding

---

tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/Desugarer.scala
tla-pp/src/test/scala/at/forsyte/apalache/tla/pp/TestDesugarer.scala

- ~[ ] Entry added to [UNRELEASED.md](./UNRELEASED.md) for any new functionality~

Desugar leadsTo

---

.unreleased/bug-fixes/1794.md
test/tla/Bug1794.tla
test/tla/cli-integration-tests.md
tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/Inliner.scala

BUGFIX: Inlining in ASSUME (#1794)

---

docs/src/adr/010rfc-transition-explorer.md
docs/src/apalache/running.md

Fix link in docs

---

.unreleased/bug-fixes/1839.md
docs/src/adr/015adr-trace.md
tla-io/src/main/scala/at/forsyte/apalache/io/lir/ItfCounterexampleWriter.scala
tla-io/src/test/scala/at/forsyte/apalache/io/lir/TestItfCounterexampleWriter.scala

output some expressions as unserializable

---

tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/passes/TemporalPassImpl.scala
tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/temporal/LoopEncoder.scala
tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/temporal/TableauEncoder.scala

Followup to the comments of #1810 , which was mistakenly merged before comments were incorporated.

Incorporate comments

---

tla-types/src/main/scala/at/forsyte/apalache/tla/typecomp/BuilderUtil.scala
tla-types/src/main/scala/at/forsyte/apalache/tla/typecomp/package.scala
tla-types/src/main/scala/at/forsyte/apalache/tla/typecomp/subbuilder/ActionBuilder.scala
tla-types/src/main/scala/at/forsyte/apalache/tla/typecomp/subbuilder/ArithmeticBuilder.scala
tla-types/src/main/scala/at/forsyte/apalache/tla/typecomp/subbuilder/BaseBuilder.scala
tla-types/src/main/scala/at/forsyte/apalache/tla/typecomp/subbuilder/BoolBuilder.scala
tla-types/src/main/scala/at/forsyte/apalache/tla/typecomp/subbuilder/FunBuilder.scala
tla-types/src/main/scala/at/forsyte/apalache/tla/typecomp/subbuilder/LiteralAndNameBuilder.scala
tla-types/src/main/scala/at/forsyte/apalache/tla/typecomp/subbuilder/SetBuilder.scala
tla-types/src/main/scala/at/forsyte/apalache/tla/typecomp/unsafe/UnsafeBaseBuilder.scala
tla-types/src/main/scala/at/forsyte/apalache/tla/typecomp/unsafe/UnsafeFunBuilder.scala
tla-types/src/main/scala/at/forsyte/apalache/tla/typecomp/unsafe/UnsafeSetBuilder.scala
tla-types/src/test/scala/at/forsyte/apalache/tla/typecomp/BuilderTest.scala
tla-types/src/test/scala/at/forsyte/apalache/tla/typecomp/TestBaseBuilder.scala
tla-types/src/test/scala/at/forsyte/apalache/tla/typecomp/TestBoolBuilder.scala
tla-types/src/test/scala/at/forsyte/apalache/tla/typecomp/TestFunBuilder.scala
tla-types/src/test/scala/at/forsyte/apalache/tla/typecomp/TestHybrid.scala
tla-types/src/test/scala/at/forsyte/apalache/tla/typecomp/TestLiteralAndNameBuilder.scala
tla-types/src/test/scala/at/forsyte/apalache/tla/typecomp/TestSetBuilder.scala

Adds shadowing-guards + tests and better testing coverage of all `require`-guards in builder methods.

Typed Builder implementation Part 6.5: Shadowing and `require` tests

---

tla-io/src/main/scala/at/forsyte/apalache/tla/imp/passes/SanyParserPassImpl.scala

A light refactor of the `execute` method in the `SanyParserPassImpl`.
I prepared this initially to support #1114, but realized it wasn't quite
the right way to meet the needs of the server.
Still, I think it's a nice enough cleanup to be worth integrating.
The refactor just breaks the execution logic into three chunks with some
helper functions and uses a for comprehension over `Either` to sequence
the possible error cases.
I recommend reviewing using the [split view of the diff](https://github.com/informalsystems/apalache/pull/1887/files?diff=split&w=0).

Refactor SanyParserPassImpl

---

.unreleased/bug-fixes/1880.md
test/tla/Bug1880.tla
test/tla/cli-integration-tests.md
tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/Inliner.scala
tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/passes/InlinePassImpl.scala
tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/passes/TemporalPassImpl.scala
tla-pp/src/test/scala/at/forsyte/apalache/tla/pp/TestInliner.scala
tlair/src/main/scala/at/forsyte/apalache/tla/lir/TlaType1.scala

closes #1880 
Also closes #1885

Bugfix: Inline polymorphic operators

---

.unreleased/features/1815.md
.unreleased/features/1823.md

Followup to #1874, which didn't include any entries to the change log,
tho we have some nice features to release :)

Add changelog entries for temporal properties features

---

test/tla/Paxos.tla
test/tla/cli-integration-tests.md

Towards #1895. Just one more test refactored.

refactor Paxos.tla to use variants

---

tla-types/src/main/scala/at/forsyte/apalache/tla/typecomp/ScopedBuilder.scala
tla-types/src/main/scala/at/forsyte/apalache/tla/typecomp/TypeComputationFactory.scala
tla-types/src/main/scala/at/forsyte/apalache/tla/typecomp/signatures/ApalacheInternalOperSignatures.scala
tla-types/src/main/scala/at/forsyte/apalache/tla/typecomp/subbuilder/ApalacheInternalBuilder.scala
tla-types/src/main/scala/at/forsyte/apalache/tla/typecomp/unsafe/UnsafeApalacheInternalBuilder.scala
tla-types/src/test/scala/at/forsyte/apalache/tla/typecomp/TestApalacheInternalBuilder.scala
tlair/src/main/scala/at/forsyte/apalache/tla/lir/oper/ApalacheInternalOper.scala

Typed Builder implementation Part 9: Apalache internal operators

---

tla-types/src/main/scala/at/forsyte/apalache/tla/typecomp/BuilderUtil.scala
tla-types/src/main/scala/at/forsyte/apalache/tla/typecomp/ScopedBuilder.scala
tla-types/src/test/scala/at/forsyte/apalache/tla/typecomp/BuilderTest.scala
tla-types/src/test/scala/at/forsyte/apalache/tla/typecomp/TestHybrid.scala

Typed Builder implementation Part 11: `LET-IN` 

---

tla-types/src/main/scala/at/forsyte/apalache/tla/typecomp/ScopedBuilder.scala
tla-types/src/main/scala/at/forsyte/apalache/tla/typecomp/TypeComputationFactory.scala
tla-types/src/main/scala/at/forsyte/apalache/tla/typecomp/signatures/VariantOperSignatures.scala
tla-types/src/main/scala/at/forsyte/apalache/tla/typecomp/subbuilder/VariantBuilder.scala
tla-types/src/main/scala/at/forsyte/apalache/tla/typecomp/unsafe/UnsafeVariantBuilder.scala
tla-types/src/test/scala/at/forsyte/apalache/tla/typecomp/BuilderTest.scala
tla-types/src/test/scala/at/forsyte/apalache/tla/typecomp/TestVariantBuilder.scala

Typed Builder implementation Part 12: Variants

---

tla-types/src/test/scala/at/forsyte/apalache/tla/typecomp/TestHybrid.scala

Typed Builder implementation part 13.5: Standardized `ScopedBuilder.decl` tests

---

tla-types/src/main/scala/at/forsyte/apalache/tla/types/package.scala

Typed Builder implementation part 13.7: User documentation of `types`

---

tla-types/src/main/scala/at/forsyte/apalache/tla/typecomp/ScopedBuilder.scala
tla-types/src/test/scala/at/forsyte/apalache/tla/typecomp/BuilderTest.scala
tla-types/src/test/scala/at/forsyte/apalache/tla/typecomp/HOWTOFooBuilder.scala

Typed Builder implementation part 13.6: HOWTO for methods

---

tla-io/src/main/scala/at/forsyte/apalache/tla/imp/utils.scala

Just removes some duplicate code
-------

Remove duplicate debug conditional

---

tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/DomainRule.scala
tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/DomainRuleWithArrays.scala

This PR propagates the use of `RecRowT1` in `DomainRule` to `DomainRuleWithArrays`.

Fix cell type in DomainRuleWithArrays

---

.github/workflows/prepare-release.yml

Disable prepare-release in forks

---

build.sbt
mod-infra/src/main/scala/at/forsyte/apalache/infra/log/LogbackConfigurator.scala
project/Dependencies.scala

- Updates slf4j and lockback
- Required one update to an extension of the logback configuration class

Update logging libraries

---

tla-io/src/main/scala/at/forsyte/apalache/tla/imp/SanyImporter.scala

Fixes #1963
This adds a mutex around our invocation of SANY. It is very simple: 
- We add a singleton object to synchronize on
- We call SANY through a method on that object that protects the call with `this.synchronized`
Some pointers to instruction guiding my choice are included in comments.
The tests in #2157 demonstrate the synchronization in effect: for without it we would see test failures from SANY due to concurrent invocations.
:warning: Auto merge enabled.
-------

Add mutex around invocation of SANY

---

mod-infra/src/main/scala/at/forsyte/apalache/infra/passes/options.scala
mod-tool/src/main/scala/at/forsyte/apalache/tla/tooling/opt/CheckCmd.scala
mod-tool/src/main/scala/at/forsyte/apalache/tla/tooling/opt/TestCmd.scala
tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/passes/BoundedCheckerPassImpl.scala
tla-io/src/main/scala/at/forsyte/apalache/io/ConfigManager.scala

Reduce the surface area of our runtime errors a smidge :).
:warning: Automerge enabled.

Use case class to represent algorithm option

---

.unreleased/bug-fixes/smt-log-to-custom-rundir.md
test/tla/cli-integration-tests.md
tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/smt/Z3SolverContext.scala

Write the SMT log also to a custom rundir specified with `--run-dir=`.
Closes #2206

Output SMT log also to custom run directory

---

tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/config/CheckerExceptionAdapter.scala

Catch JsonDeserialization in ExceptionAdapter

---

project/Dependencies.scala
project/build.properties
project/plugins.sbt
project/project/build.properties
project/sbt-changeling/project/build.properties

This consolidates the scala-steward updates into a single PR so we can avoid a 2 day merge marathon.

Merge in scala-steward updates

---

docs/src/SUMMARY.md
docs/src/adr/023adr-trace-evaluation.md

- ~[ ] Tests added for any new code~
- ~[ ] Ran `make fmt-fix` (or had formatting run automatically on all files edited)~
- ~[ ] [Entries added to `./unreleased/`][changelog format] for any new functionality~
closes #2188

ADR23 - Trace evaluation

---

tla-io/src/main/scala/at/forsyte/apalache/io/lir/ItfCounterexampleWriter.scala
tla-io/src/test/scala/at/forsyte/apalache/io/lir/TestItfCounterexampleWriter.scala

Variable type info in ITF CE writer

---

tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/config/CheckerExceptionAdapter.scala
tla-io/src/main/scala/at/forsyte/apalache/io/itf/ItfToTla.scala
tla-io/src/main/scala/at/forsyte/apalache/io/itf/package.scala
tla-io/src/main/scala/at/forsyte/apalache/io/lir/ItfCounterexampleWriter.scala
tla-io/src/test/scala/at/forsyte/apalache/io/itf/TestItfToTla.scala

Closes #2284 + adds ITF error handling to exception adapter

ITF field constants used in writer

---

tlair/src/main/scala/at/forsyte/apalache/tla/typecomp/ScopedBuilder.scala
tlair/src/main/scala/at/forsyte/apalache/tla/typecomp/signatures/ApalacheInternalOperSignatures.scala
tlair/src/main/scala/at/forsyte/apalache/tla/typecomp/subbuilder/ApalacheBuilder.scala
tlair/src/main/scala/at/forsyte/apalache/tla/typecomp/unsafe/UnsafeApalacheBuilder.scala
tlair/src/main/scala/at/forsyte/apalache/tla/typecomp/unsafe/UnsafeApalacheInternalBuilder.scala
tlair/src/main/scala/at/forsyte/apalache/tla/types/package.scala
tlair/src/test/scala/at/forsyte/apalache/tla/typecomp/TestApalacheInternalBuilder.scala

Closes #2290.
Also incidentally discovered and removed spurious `non-epmty` requirement on `distinct`.

`strict` flag for builder

---

tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/arena/ElemPtr.scala

Builder change in ElemPtr

---

tla-io/src/main/scala/at/forsyte/apalache/io/tnt/Tnt.scala
tla-io/src/test/scala/at/forsyte/apalache/io/tnt/TestTnt.scala

Add type mapping

---

test/tla/cli-integration-tests.md
tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/FunAppRule.scala

Unsound FunApp optimization disabled

---

tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/arena/ElemPtr.scala

`ElemPtr` changes

---

tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/arena/ElemPtr.scala
tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/arena/PtrUtil.scala
tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/SetCupRule.scala

SetCupRule with pointers

---

tla-io/src/main/scala/at/forsyte/apalache/io/quint/Quint.scala

Closes #2363
Adds conversion of
- State variable declarations
- Constant declarations
- Assumptions
Closes #2365
As i realized in the course of this that we don't need (indeed can't
support) conversion of type definitions.
-------
- [-] Tests added for any new code: code too trivial to benefit from tests
- [-] Documentation added for any new functionality
- [-] [Entries added to `./unreleased/`][changelog format] for any new functionality

Add conversion from quint defs

---

tlair/src/main/scala/at/forsyte/apalache/tla/typecomp/signatures/FlexibleEquality.scala

Bugfix: 2392

---

tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/arena/PureArenaAdapter.scala
tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/caches/IntRangeCache.scala
tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/SetCtorRule.scala

Introducing FixedPtrs

---

tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/SetUnionRule.scala

UNION rule

---

tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/arena/PtrUtil.scala
tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/aux/MapBase.scala

SetMapRule

---

tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/aux/PowSetCtor.scala

PowSetCtor (Expand) pointers

---

tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/arena/PtrUtil.scala
tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/SetUnionRule.scala

No code changes, just extracting a method that will be useful again in #2377.

Moved reusable code to new method

---

tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/caches/RecordDomainCache.scala
tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/DomainRule.scala
tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/smt/Z3SolverContext.scala

closes #2370 
Includes a 1-line fix to a bug in `Z3SolverContext` (method called on the pre-transformed argument)

Domain Rule

---

tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/FunCtorRule.scala
tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/FunCtorRuleWithArrays.scala

`ElemPtr` rework, pahse 2: Propagating `FixedElemPtr`s in FunCtorRule

---

tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/arena/PtrUtil.scala
tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/FunExceptRule.scala

 ElemPtr rework, pahse 2: Propagating `FixedElemPtr`s in `FunExceptRule`

---

tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/FunExceptRuleWithArrays.scala
tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/RecCtorRule.scala
tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/aux/ProtoSeqOps.scala
tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/aux/RecordAndVariantOps.scala

Some of these were missed, some didn't fit neatly into issues.

Misc. fixes left over from phase 2 of the pointer rework

---

tla-io/src/main/scala/at/forsyte/apalache/io/quint/Quint.scala
tla-io/src/test/scala/at/forsyte/apalache/io/quint/TestQuintEx.scala

Towards #2364
Also adds some clarifying renaming.

Add conversion of quint builtin boolean operator

---

tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/arena/ElemPtr.scala
tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/arena/PtrUtil.scala
tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/aux/CherryPick.scala

Fully remove SmtConstExprPtr

---

tla-io/src/main/scala/at/forsyte/apalache/io/quint/Quint.scala
tla-io/src/test/scala/at/forsyte/apalache/io/quint/TestQuintEx.scala

Contributes to #2438
This includes a non-trivial combinator for converting binary binding
operator from quint to binding operator in ApalacheIR.
-------

Add conversion of quint Set, exists, and forall

---

.unreleased/features/quint-conversions.md

Preparation for a release so i can add integration tests to the quint
side.
Going forward, I'll be sure to add these entries as each fragment is
added.
-------

Add changelog entries for quint conversions

---

.unreleased/features/quint-tuple-ops.md
tla-io/src/main/scala/at/forsyte/apalache/io/quint/Quint.scala
tla-io/src/test/scala/at/forsyte/apalache/io/quint/TestQuintEx.scala

Add quint tuple constructors

---

test/tla/Antipatterns.tla

Added Antipatterns.tla

---

tla-io/src/main/scala/at/forsyte/apalache/io/quint/Quint.scala
tla-io/src/test/scala/at/forsyte/apalache/io/quint/TestQuintEx.scala

Convert quint temporal operators

---

.unreleased/features/quint-records.md
tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/config/CheckerExceptionAdapter.scala
tla-io/src/main/scala/at/forsyte/apalache/io/quint/Quint.scala
tla-io/src/main/scala/at/forsyte/apalache/io/quint/QuintIR.scala
tla-io/src/test/scala/at/forsyte/apalache/io/quint/TestQuintEx.scala

Convert quint record operators

---

tla-io/src/main/scala/at/forsyte/apalache/io/quint/Quint.scala

Closes informalsystems/quint#896
We were not tracking nullary operators defined at the top-level, which was leading to reference to top-level operator hitting the same problem as we saw in the typing of nested definition of nullary operators.
The fix here is to
- Track whether a declaration conversion was for a nullary operator
- If so, add the name of for this operator into the store of nullary operator names used for correcting the types when nullary operator are referenced.
Tests for this have been conducted locally and will be added as integration tests in quint: testing this requires construction of a valid quint module, and IMO that would not be an economical addition to our test coverage here given the need to cover it already on the quint side.
- [-] Tests added for any new code …

Quint conversion: Track nullary operator declarations at top-level

---

LICENSE

Our license file is massively outdated. Fixed that.

tidy the license file

---

.unreleased/bug-fixes/2606.md

Missing `.unreleased` entry

---

.unreleased/bug-fixes/2608.md

Add changelog for #2608, as pointed out in https://github.com/informalsystems/apalache/pull/2608#discussion_r1236951085

Add changelog for #2608

---

tlair/src/main/scala/at/forsyte/apalache/tla/typecomp/unsafe/UnsafeBaseBuilder.scala
tlair/src/test/scala/at/forsyte/apalache/tla/typecomp/TestBaseBuilder.scala

Added unification support for operator application

---

tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/stratifiedRules/aux/RewriterImpl.scala
tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/stratifiedRules/bool/AndStratifiedRule.scala
tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/stratifiedRules/bool/OrStratifiedRule.scala
tla-bmcmt/src/test/scala/at/forsyte/apalache/tla/bmcmt/stratifiedRules/BoolRewriterTest.scala

StratifiedRules: Boolean connectives

---

tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/stratifiedRules/aux/RewriterImpl.scala
tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/stratifiedRules/set/SetFilterStratifiedRule.scala
tla-bmcmt/src/test/scala/at/forsyte/apalache/tla/bmcmt/stratifiedRules/SetRewriterTest.scala

closes #2642 
This PR updates SetFilterRule to the new approach (by introducing a new rule, due to incompatible interfaces).

StratifiedRules: Set filter

---

CONTRIBUTING.md

Remove a left-over reference to `release-me`.

Remove left-over reference to `release-me`

---

tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/aux/Oracle.scala

No code changes. This PR adds a comment, which should help explain the implementation details of `Oracle.caseAssertions`.

Explanation of caseAssertions behavior

---

README.md

Update README.md to point nix users to cosmos.nix

---

.unreleased/features/shai-tla-reply.md
shai/src/main/protobuf/cmdExecutor.proto
shai/src/main/scala/at/forsyte/apalache/shai/v1/CmdExecutorService.scala
shai/src/test/scala/at/forsyte/apalache/shai/v1/TestCmdExecutorService.scala
tla-io/src/main/scala/at/forsyte/apalache/io/lir/PrettyWriter.scala

Closes #2851
Works towards https://github.com/informalsystems/quint/issues/1309
-------

Add Shai command to receive formatted TLA as reply

---

.unreleased/bug-fixes/pretty-printer-id-sanitization.md

This is just a missing changelog entry.

Add CHANGELOG entry for new sanitization from #2860

---

.github/workflows/README.md
.github/workflows/prepare-release.yml

Replacing `apalachebot` with `coffeeinprogress`

a first try to fix the release workflow

---

tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/SetMembershipSimplifier.scala

Fix bogus comment in SetMembershipSimplifier

---

index.md

Fixing the broken links on the website's landing page

Fix two links

---

.unreleased/features/bat-file.md

This adds a release note for the new bat file, which I forgot to do in its own PR :see_no_evil: 

Add changelog entry for the new bat file

---

index.md

The Apalache website was quite outdated. I have refreshed it a bit. Obviously, it needs more work to be done.

refresh the landing page

---

README.md

I don't think that we need the "reloading" image. Also, nobody has donated so far, removing the mentioning of github sponsors.

Polish the landing page
