- Dockerfile
Adds a Dockerfile to simplify setup - potentially allows using Apalache for automated specification checking (for CI-like scenarios).
Although the PR is against the unstable branch, it should work for stable as well.
> [unstable] Add Dockerfile

- CHANGES.md
- README.md
- docs/manual.md
- mod-distribution/pom.xml
- mod-infra/pom.xml
- mod-tool/pom.xml
- mod-tool/src/main/scala/at/forsyte/apalache/tla/Tool.scala
- pom.xml
- tla-assignments/pom.xml
- tla-bmcmt/pom.xml
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/config/CheckerExceptionAdapter.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/package.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/ChooseRule.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/SetInRule.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/types/eager/TrivialTypeFinder.scala
- tla-import/pom.xml
- tla-pp/pom.xml
- tla-types/pom.xml
- tlair/pom.xml
- tlair/src/main/scala/at/forsyte/apalache/tla/lir/io/CounterexampleWriter.scala
- tlair/src/test/scala/at/forsyte/apalache/tla/lir/io/TestCounterexampleWriter.scala
These changes include the CHANGES.md (since this is a published
document), the manual, the readme, and numerous `pom.xml` files.
Since I'm still getting oriented on this project, I wanted to call out those locations, to make sure there's a sanity check on whether they should be changed. I did *not* include two instances in the `scripts` dir: 
```
[sf@comp apalache]$ rg 'github\.com/konnov'
script/release-0.6.0.txt
6:   [benchmarks](https://github.com/konnov/apalache-tests),
script/release-0.5.0.txt
24: * options for fine tuning with `--fine-tuning`, see [tuning](https://github.com/konnov/apalache/blob/unstable/docs/tuning.md)
```
under the assumption that these are not published.
> Update the github URL to reflect move to Informal

- CHANGES.md
- tlair/src/main/scala/at/forsyte/apalache/tla/lir/io/JsonReader.scala
- tlair/src/main/scala/at/forsyte/apalache/tla/lir/io/JsonWriter.scala
- tlair/src/test/scala/at/forsyte/apalache/tla/lir/io/TestCounterexampleWriter.scala
- tlair/src/test/scala/at/forsyte/apalache/tla/lir/io/TestJson.scala
* get rid of special symbols in object keys
* use objects instead of arrays for binary operators
* use key-value objects instead of arrays for pairs of expressions
> Close #153: make JSON TLA+ encoding more suitable for JsonPath queries

- CONTRIBUTING.md
This documents my current setup for writing Scala in Emacs. I think it's
worth having this kind of information documented for potential
contirbutors, and it can help lower the bar to entry significantly.
> Add documentation on configuring Emacs for hacking

- CHANGES.md
- bin/apalache-mc
- docs/manual.md
- src/tla/Apalache.tla
- tla-import/pom.xml
- tla-import/src/main/scala/at/forsyte/apalache/tla/imp/StandardLibrary.scala
- tla-import/src/test/scala/at/forsyte/apalache/tla/imp/TestSanyImporter.scala
- tlair/src/main/scala/at/forsyte/apalache/tla/lir/oper/BmcOper.scala
Following #183, this PR introduces the standard module `Apalache.tla` that gives the user access to (almost all of) internal operators introduced by Apalache. Most importantly, it introduces the assignment operator `x := e`. This opens the way to deal with #181.
> Apalache.tla: the standard module for Apalache

- bin/apalache-mc
- test/run-integration
- test/tla/tla-path-tests/ImportedModule.tla
- test/tla/tla-path-tests/ImportingModule.tla
We ended up muddling some of the bash variable handling in #188, and this sets that right.
It also introduces an integration test that uses the `TLA_PATH`, and fails if it doesn't work as expected to put dependent modules in context.
> Fix TLA_PATH

- CHANGES.md
Trivial followup to 0539ec285ed3e2e1cbf6f7eaccfb6bee9a77cee8, I'm only opening a PR to ensure this is consistent with @konnov's intention. I do think we want the bug fix recorded in the changelog before releasing the fix, just not sure how we want it recorded.
> Add changelong entry for version number bug fix

- CHANGES.md
- mod-distribution/pom.xml
- mod-infra/pom.xml
- mod-tool/pom.xml
- pom.xml
- script/release-0.7.2.txt
- tla-assignments/pom.xml
- tla-bmcmt/pom.xml
- tla-import/pom.xml
- tla-pp/pom.xml
- tla-types/pom.xml
- tlair/pom.xml
* fixed an omitted version number update
--- 
**Note** that this cherry picks in just the bug fixes and changelog updates from unstable, and does not merge all of unstable into master.
> Release 0.7.2

- tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/passes/ConfigurationPassImpl.scala
Useful for users and for us when debugging (as in the case of  #208).
With this change, lexer errors now look like:
```
Configuration error (see the manual):   > Could not parse TLC configuration in BlockingQueue.cfg at position 4.17: string matching regex '\z' expected but '{' found E@00:14:23.070
```
> Add parser position to TLCConfigurationError message

- tla-import/pom.xml
Removes the following warning from the build output:
```
[WARNING]
[WARNING] Some problems were encountered while building the effective model for at.forsyte.apalache:tla-import:jar:0.7.3-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-surefire-plugin is missing. @ line 64, column 21
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
```
> Specify surefire version

- pom.xml
- tla-import/pom.xml
Now we're only one minor version and three patches behind the latest Scala :)
This also removes a profile configuration that seems to be an unneeded complication in the build configuration, afaict. See 27311da for details.
> Update to scala 2.12.12

- CHANGES.md
- Dockerfile
- docs/manual.md
- script/run-docker.sh
- test/run-integration
This builds the vendored dependencies and apalache itself in two
separate stages (as per https://docs.docker.com/develop/develop-images/multistage-build/). 
This lets us reuse previously built images for
z3 and box, so long as the content of the ./3rdparty direcotry
hasn't been changed. In those cases, this reduces the time for building an 
image for our code considerably.
> Make Dockerfile staged

- .travis.yml
- 3rdparty/README.md
- 3rdparty/install-local.sh
- CHANGES.md
- Makefile
- bin/apalache-mc
- docs/manual.md
- pom.xml
- tla-assignments/pom.xml
- tla-bmcmt/pom.xml
- tla-import/pom.xml
- tla-pp/pom.xml
- tla-types/pom.xml
Closes #213 (I hope!)
Our bespoke build and local installation of the Z3 API dependency adds a lot of configuration overhead and brittleness 
to our build. While investigating #213, I read about Z3-Turnkey on https://stackoverflow.com/a/62015869/1187277. The purpose of this library is to provide a Java artifact that
> 1. ships its own native libraries,
> 2. can use them without administrative privileges, and
> 3. can be obtained using Maven.
I'm hopeful that it can simplify our build overall, and address #213.
> Use Z3-TurnKey instead of a bespoke Z3 build

- .github/dependabot.yml
This should help us keep our dependencies up to date.
See https://docs.github.com/en/github/administering-a-repository/about-github-dependabot-version-updates
(When we switch to SBT we can instead use https://github.com/scala-steward-org/scala-steward)
> Enable dependabot for automatic dep updates

- README.md
- logo-apalache.svg
Adds the Apalache logo from informal.systems to the README.
It also includes some auto-formatting, which I didn't bother suppressing. Let me know if you'd like me to.
Looks like this:
> Add Apalache logo to readme

- .github/workflows/main.yml
- Dockerfile
Closes #220, #221
Contributes to #192 and #237
Aside from removing dependency on an external service provider and being able to make use of the github actions ecosystem, this PR also adds the following features to our CI:
- Add macOS to our build matrix
- Run and (integration) test the Dockerfile
> Use github actions for CI

- .github/workflows/main.yml
Towards #172 
This is an attempt to improve iteration time by reducing the time of our CI pipeline.
Instead of running the unit tests and integration sequentially on each platform, this breaks the unit tests and integration tests into two separate jobs, each running in parallel. 
- When running the unit tests, we use `mvn test`. This job is clocking in at around 5 minutes. If this does fail, we'll likely end up with quicker feedback than we've been receiving.
- When running integration tests, we run `mvn package` with `skipTests`, to get the artifacts as quickly as possible, and then run the integration tests using `NO_MVN`. This job is coming in at 12 mins on ubuntu and 15 mins (fastest times so far) on macOs
My unscientific observations so far indicate that this *might* save us about 3 …
> Run integration tests in parallel

- .github/workflows/main.yml
- README.md
Followup to #241 
Looks like
Will need a followup right before we cut the next release, to point master to it's github action pipelines.
> Use GitHub action badge

- bin/apalache-mc
Extracted from #244
@konnov I'd be interested to know what this fixes, actually, since it looks like the code should be strictly equivalent to what it's replacing :D
> Fixing the TLA_PATH

- docs/adr/002adr-types.md
dbcf4d2 also suggests some minor tweaks to the wording.
Note that this will require resolving a tiny merge conflict when rebasing #244 on top of this change.
> Update ADR2 to address type ascriptions for empty collections

- src/tla/Typing.tla
- tla-import/src/main/scala/at/forsyte/apalache/tla/imp/StandardLibrary.scala
- tlair/src/main/scala/at/forsyte/apalache/tla/lir/oper/TlaFunOper.scala
- tlair/src/main/scala/at/forsyte/apalache/tla/lir/oper/TypingOper.scala
- tlair/src/main/scala/at/forsyte/apalache/tla/lir/oper/package.scala
Broken out of #244
See
https://github.com/informalsystems/apalache/blob/unstable/docs/adr/002adr-types.md#23-dealing-with-bound-variables
for the motivation
Original Author: Igor Konnov <igor@informal.systems>
> Add operators for type annotated empty collections

- test/mdx-test.py
This is a followup to #250 -- I had misconfigured the logger,
and so nothing was being logged to the files our stdout.'
Thanks to @konnov  for reporting the broken behavior.
Also adds a flag to enable debugging output to stdout
With this change, `test/mdx-test.py` can be run with the `--debug` flag to get streaming output like the following:
```
[sf@comp apalache-core]$ ./test/mdx-test.py "check Bug20190118 succeeds" --debug
[2020-10-12 16:13:04,922] DEBUG:Output level: DEBUG
[2020-10-12 16:13:04,923] DEBUG:running command: ['ocaml-mdx', 'test', '--verbosity', 'info', '--root', '/home/sf/Sync/informal-systems/apalache/apalache-core/test/tla', '--output', '/home/sf/Sync/informal-systems/apalache/apalache-core/target/test/tla/cli-integration-tests.md.corrected', …
```
> Fix logging for integration tests

- tlair/src/main/scala/at/forsyte/apalache/tla/lir/identifiers.scala
- tlair/src/main/scala/at/forsyte/apalache/tla/lir/oper/BmcOper.scala
- tlair/src/main/scala/at/forsyte/apalache/tla/lir/oper/TlaActionOper.scala
- tlair/src/main/scala/at/forsyte/apalache/tla/lir/oper/TlaArithOper.scala
- tlair/src/main/scala/at/forsyte/apalache/tla/lir/oper/TlaBoolOper.scala
- tlair/src/main/scala/at/forsyte/apalache/tla/lir/oper/TlaControlOper.scala
- tlair/src/main/scala/at/forsyte/apalache/tla/lir/oper/TlaFiniteSetOper.scala
- tlair/src/main/scala/at/forsyte/apalache/tla/lir/oper/TlaFunOper.scala
- tlair/src/main/scala/at/forsyte/apalache/tla/lir/oper/TlaOper.scala
- tlair/src/main/scala/at/forsyte/apalache/tla/lir/oper/TlaSeqOper.scala
- tlair/src/main/scala/at/forsyte/apalache/tla/lir/oper/TlaSetOper.scala
- tlair/src/main/scala/at/forsyte/apalache/tla/lir/oper/TlaTempOper.scala
- tlair/src/main/scala/at/forsyte/apalache/tla/lir/oper/TlcOper.scala
- tlair/src/main/scala/at/forsyte/apalache/tla/lir/oper/TypingOper.scala
- tlair/src/main/scala/at/forsyte/apalache/tla/lir/oper/package.scala
- tlair/src/main/scala/at/forsyte/apalache/tla/lir/package.scala
This is a first changeset from `ik/multicore`. The operators and other basic classes in `lir` made `Serializable`.
> a slice from ik/multicore: operators made Serializable

- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/CoercionWithCache.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/LazyEquality.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/PreproSolverContext.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/StackableContext.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/Z3SolverContext.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/analyses/ExprGradeStoreImpl.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/analyses/FormulaHintsStoreImpl.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/caches/AbstractCache.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/caches/AbstractCacheSnapshot.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/caches/EqCache.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/caches/EqCacheSnapshot.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/caches/ExprCache.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/caches/IntRangeCache.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/caches/IntValueCache.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/caches/RecordDomainCache.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/caches/SimpleCache.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/caches/SimpleCacheSnapshot.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/caches/StrValueCache.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rewriter/Recoverable.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rewriter/SymbStateRewriterSnapshot.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/types/eager/TrivialTypeSnapshot.scala
This is a second PR that is extracted from ik/multicore. Most of the code involves mechanical updates that declare caches `Serializable`. It also defines the trait `Recoverable` that is meant for objects to be saved and restored in different threads. This trait is used by the parallel model checker, which will be extracted in the end of this story. It also cleans up `Z3SolverContext` a bit.
> chunk 2 from ik/multicore: making caches Serializable and Recoverable

- src/tla/Typing.tla
- tla-import/src/main/scala/at/forsyte/apalache/tla/imp/StandardLibrary.scala
- tla-import/src/test/scala/at/forsyte/apalache/tla/imp/TestSanyImporter.scala
I'd missed this update in my previous port of these changes in #260
> ETC-5: Update Typing's Operator typing operator from :> to ##

- tla-types/src/main/scala/at/forsyte/apalache/tla/typecheck/etc/EtcExpr.scala
- tla-types/src/main/scala/at/forsyte/apalache/tla/typecheck/etc/EtcId.scala
This encodes the AST of the labda-calculus like language used as the basis of type checking in the Etc.
Authored by @konnov and broken out of #259
> ETC-6: Add the EtcExpr module

- tla-types/src/main/scala/at/forsyte/apalache/tla/typecheck/TlaType1.scala
- tla-types/src/main/scala/at/forsyte/apalache/tla/typecheck/parser/DefaultType1Parser.scala
- tla-types/src/main/scala/at/forsyte/apalache/tla/typecheck/parser/Type1Lexer.scala
- tla-types/src/main/scala/at/forsyte/apalache/tla/typecheck/parser/tokens.scala
- tla-types/src/test/scala/at/forsyte/apalache/tla/typecheck/TestDefaultType1Parser.scala
Broken out of #259
Originally authored by Igor Konnov <konnov@forsyte.at>
Also includes a white space change to `TlaType1.scala` that I'd not picked up before.
> ETC7: Add Type1 parser and lexer changes

- test/tla/ConfigUnsorted.tla
- test/tla/cli-integration-tests.md
- tla-import/src/main/scala/at/forsyte/apalache/tla/imp/ExprOrOpArgNodeTranslator.scala
- tla-import/src/test/scala/at/forsyte/apalache/tla/imp/TestSanyImporter.scala
- tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/ConstAndDefRewriter.scala
- tlair/src/main/scala/at/forsyte/apalache/tla/lir/io/PrettyWriter.scala
- tlair/src/test/scala/at/forsyte/apalache/tla/lir/io/TestPrettyWriter.scala
This PR does not completely fix the problem discovered by Markus in #285, as the spec uncovers multiple layers of issues with parsing advanced specs. This commit fixes the long-known issue with LAMBDAs. 
@Kukovec can you have a look at the changes and tell us if this solution potentially breaks your code. I can imagine that having a LET-definition in the operator parameters may come a bit unexpected.
> Fixing 285: step 1

- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/analyses/ExpansionMarker.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/types/AnnotationParser.scala
- tla-bmcmt/src/test/scala/at/forsyte/apalache/tla/bmcmt/TestTrivialTypeFinder.scala
- tla-bmcmt/src/test/scala/at/forsyte/apalache/tla/bmcmt/analyses/TestExpansionMarker.scala
Better diagnostics for unexpected type annotations inside type annotations #292 , discovered by @istoilkovska and @andrey-kuprianov
> fix 292: better diagnostics for type annotations in type annotations

- CHANGES.md
- tla-import/src/main/scala/at/forsyte/apalache/tla/imp/OpApplTranslator.scala
- tla-import/src/test/scala/at/forsyte/apalache/tla/imp/TestSanyImporter.scala
Following up on #285 and #295, now `SanyImporter` treats correctly the standard operators that come from the standard library via `LOCAL INSTANCE`, e.g.:
```tla
LOCAL INSTANCE Sequences
```
> fix 295: support for LOCAL INSTANCE Sequences

- tla-import/src/main/scala/at/forsyte/apalache/tla/imp/OpApplTranslator.scala
- tla-import/src/test/scala/at/forsyte/apalache/tla/imp/TestSanyImporter.scala
This PR fixes issue #286. The importer expected an operator application as the first argument of `EXCEPT`, but actually other kinds of expression may also occur there, e.g., the reference `@`. The solution is simply a one-liner. The job of checking expression compatibility for `EXCEPT` has been done by SANY already.
> Accept expressions as the first arguments of EXCEPT

- tla-assignments/src/main/scala/at/forsyte/apalache/tla/assignments/passes/CoverAnalysisPassImpl.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/config/CheckerModule.scala
- tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/passes/InlinePassImpl.scala
Changes the order of passes, so `CoverAnalysisPass` comes before inlining.
> Passes reordered + keep (C)initPrime after InlinePass

- README.md
This adds the link to our zulip stream on the public informal-systems zulip instance.
Since I was touching the README, I also added some styling to center the header section, and to suggest some tweaks to wording in a few passages.
Rendered, the changes look like this:
> Add zulip link and give readme a facelift

- Dockerfile
Make the two phase build clearer, and explain the reason for the
different phases.
Follows from conversation with @andrey-kuprianov and @konnov on slack.
> Improve the Dockerfile documentation

- test/tla/Rec13.tla
- test/tla/cli-integration-tests.md
- tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/passes/UnrollPassImpl.scala
- tlair/src/main/scala/at/forsyte/apalache/tla/lir/package.scala
closes #313 
Adds a temporary workaround, to address the problems described in #345 (unexpected behavior of `TlaOperDecl.copy` when the declaration is recursive)
> Added renaming before the first Unroller call.

- test/tla/cli-integration-tests.md
- test/tla/reorderTest.properties
- test/tla/reorderTest.tla
Replaces the monolithic `APABcastByz.tla` test with a minimal problem-isolating spec.
This PR is expected to fail the integration tests, as it does not fix the problems with SMT-based assignment finding and reordering, but merely improves the tests themselves. 
Tests are expected to pass after #348.
> Added minimal breaking retorderTest, disabled APABcastByz test

- tla-assignments/src/main/scala/at/forsyte/apalache/tla/assignments/SmtFreeSymbolicTransitionExtractor.scala
- tla-assignments/src/main/scala/at/forsyte/apalache/tla/assignments/SymbTransGenerator.scala
- tla-assignments/src/main/scala/at/forsyte/apalache/tla/assignments/passes/TransitionPassImpl.scala
- tla-assignments/src/test/scala/at/forsyte/apalache/tla/assignments/TestSmtFreeSTE.scala
- tla-assignments/src/test/scala/at/forsyte/apalache/tla/assignments/TestSymbTransGenerator.scala
closes #348
closes #354 (together with #364)
As this approach to assignments makes cover analysis irrelevant, this PR implicitly closes/invalidates the following:
issues: #279, #298, #353, #111
open pr: #308
Potentially resolves issue #346: Under this build, the solver returns to expected behavior (EXITCODE: OK), but finds a deadlock in the listed specification. Author clarification required to close.
See also:  #62
> Reworked assignment search

- docs/manual.md
This is a tiny update to the manual. The current version defines an alias for the latest stable build. Added an alias f or the unstable docker image too.
> add alias for the unstable docker image

- CONTRIBUTING.md
Updates the documentation of the release process, filling gaps I noticed during the latest release and updating to remove the section on Docker (since it's automatic now).
---
> Update release process documentation

- docs/src/apalache/installation/jvm.md
> fixed the instructions for windows

- .github/workflows/deploy.yml
While we are working rapidly on the manual, catching up on the current
state of things, we want to deploy manual updates to unstable
immediately without having to wait for a release to master.
As discussed in our meeting on monday.
> Deploy manual from unstable

- .envrc
- CONTRIBUTING.md
- UNRELEASED.md
- script/get-version.sh
- script/release-notes.sh
- script/release-prepare.sh
- script/shared.sh
- script/update-changes.sh
- script/version-bump.sh
- test/.envrc
- test/run-integration
Closes #441
Towards #388
This adds scripts to automate preparing a release and incrementing to the next development version.
This also includes a few cleanups to existing bash scripts, relevant just because of their bashist affiliation.
Once these are in place, almost all of the remaining work for #442 will be in the yaml config for our CI pipeline.
> Automate release preparation

- CONTRIBUTING.md
- UNRELEASED.md
- test/tla/SafeMath.tla
- test/tla/cli-integration-tests.md
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/SymbStateRewriterImpl.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/caches/IntValueCache.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rewriter/ConstSimplifierForSmt.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rewriter/SymbStateRewriterSnapshot.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/FunAppRule.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/IntArithRule.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/IntCmpRule.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/IntConstRule.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/IntDotDotRule.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/deprecated/ImplRule.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/smt/PreproSolverContext.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/smt/Z3SolverContext.scala
- tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/ConstSimplifier.scala
- tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/ConstSimplifierBase.scala
- tlair/src/main/scala/at/forsyte/apalache/tla/lir/io/JsonReader.scala
This PR reworks the constant preprocessor to:
- fix operations on big integers: #450 
- fix preprocessing of string comparisons: #197 
As a bonus, we can check Solidity's [SafeMath](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/math/SafeMath.sol), see [SafeMath.tla](https://github.com/informalsystems/apalache/blob/igor/bigint450/test/tla/SafeMath.tla). And the results are intriguing :-)
`ConstSimplifier` and `ConstSimplifierForSmt` need a massive set of unit tests. Postponed for #451 .
> closed #450 and #197: handling big integers and better preprocessing

- .github/workflows/main.yml
- docs/src/apalache/installation/docker.md
The alias does not work with double quotes since it means `$(pwd)` gets
expanded at the time the alias is created and so the mounted volume
stays the same wherever the command is run.
> Replace double with single quotes in alias command

- .github/workflows/main.yml
Follow up to 8511b49f11fdbb582e107147c735ce5fce5a149b which added
`pull_request` in addition to `push`.
If we only have `push` then we don't get CI running for PRs opened by
external contributors.
If we have both `push` and `pull_request`, then we get CI running
duplicate jobs for PRs from internal contributors.
So we must only enable `pull_request`. An added advantage of this change
is that the CI will now run on the result of merging the feature branch
into our trunk, which is what we want to be testing any how :)
> Only run main.yml workflow on PRs

- tla-assignments/src/main/scala/at/forsyte/apalache/tla/assignments/SmtFreeSymbolicTransitionExtractor.scala
Fixed a bug where assignment strategies contained duplicate elements, causing noticeable slowdowns in `TransitionFinderPass` on formulas with many disjunctions.
> Strategy element duplication fix

- .github/workflows/prepare-release.yml
The release preparation job has been trying to run continuously since it became Monday wherever the server is located.
I apparently forgot my cron syntax. 
With this fix, it should only run once per week, instead of trying to run constantly on Monday.
Followup to #470
> Fix release cron schedule

- README.md
We don't need the master CI badge any more, since we're not releasing from master.
Also updated the section on releases and removed a duplicate link to the website added in #489
> Update readme to reflect new release process

- UNRELEASED.md
- script/release-publish.sh
Closes  #500
The tar operation was automatically relativizing the path, but not the
zip. So I went back to just using a relative path for the jar.
> Fix path of jar in zip artifact

- Makefile
We "ratchet" our formatting checks, which means we only check files that
have changed relative to `origin/unstable`. This makes sure we have
fetched the latest changes before running those checks, so we're getting
an accurate report.
Apparently the checkout action doesn't fetch our remote branches, but we need
unstable for our ratcheted format checking.
This is causing the formatting check to fail on on #503  and #467
> Fix CI formatting check

- UNRELEASED.md
- docs/src/apalache/tlc-config.md
- tla-import/src/main/scala/at/forsyte/apalache/io/tlc/TlcConfigParserApalache.scala
- tla-import/src/main/scala/at/forsyte/apalache/io/tlc/config/TlcConfig.scala
- tla-import/src/main/scala/at/forsyte/apalache/io/tlc/config/TlcConfigLexer.scala
- tla-import/src/test/scala/at/forsyte/apalache/io/tlc/TestTlcConfigParserApalache.scala
> closes #512: parsing Boolean values in TLC config files

- UNRELEASED.md
- tla-import/src/main/scala/at/forsyte/apalache/io/tlc/config/TlcConfigLexer.scala
- tla-import/src/test/scala/at/forsyte/apalache/io/tlc/TestTlcConfigParserApalache.scala
> bugfix for a bug with - in a regex

- UNRELEASED.md
- test/tla/ExistTuple476.tla
- test/tla/cli-integration-tests.md
- tla-types/src/main/scala/at/forsyte/apalache/tla/typecheck/etc/ToEtcExpr.scala
- tla-types/src/test/scala/at/forsyte/apalache/tla/typecheck/etc/TestToEtcExpr.scala
This PR closes #482. It just applies the projection solution for set comprehensions to quantifiers.
> close #482: reusing projections from set comprehensions

- .github/workflows/deploy.yml
- docs/README.md
- docs/src/lang/logic.md
Closes #479 
Last weekend I hacked together a little command line utility for replacing and looking up GitHub emoji names, because I couldn't find any CLIs utilities to this in a unixy way and it seemed useful. You can find it at https://github.com/shonfeder/emojitsu .
This PR adds that utility into our deployment of the mdbook docs, so that the emoji names will be replaced with their unicode equivalents during deployment (if available).
I cheated a deployment into the CI for this PR, and you can see the results here: https://apalache.informal.systems/docs/idiomatic/index.html#the-idioms
> Emojify docs

- UNRELEASED.md
- test/tla/PascalTriangle.tla
- test/tla/cli-integration-tests.md
- tla-types/src/main/scala/at/forsyte/apalache/tla/typecheck/etc/ToEtcExpr.scala
- tla-types/src/test/scala/at/forsyte/apalache/tla/typecheck/etc/TestToEtcExpr.scala
This PR closes two related issues #582 and #583. That is, support for recursive functions of multiple arguments in the type checker.
> close #582, close #583

- tla-assignments/pom.xml
- tla-assignments/src/main/scala/at/forsyte/apalache/tla/assignments/ModuleAdapter.scala
- tla-import/src/main/scala/at/forsyte/apalache/tla/imp/AssumeTranslator.scala
- tla-import/src/main/scala/at/forsyte/apalache/tla/imp/ModuleTranslator.scala
- tla-import/src/main/scala/at/forsyte/apalache/tla/imp/NullOpDefTranslator.scala
- tla-import/src/test/scala/at/forsyte/apalache/io/TestPrettyWriterWithAnnotations.scala
- tla-pp/pom.xml
- tla-pp/src/test/scala/at/forsyte/apalache/tla/pp/TestCaching.scala
- tla-pp/src/test/scala/at/forsyte/apalache/tla/pp/TestConstAndDefRewriter.scala
- tla-pp/src/test/scala/at/forsyte/apalache/tla/pp/TestExprOptimizer.scala
- tlair/src/main/scala/at/forsyte/apalache/tla/lir/TlaDecl.scala
- tlair/src/main/scala/at/forsyte/apalache/tla/lir/TlaEx.scala
- tlair/src/main/scala/at/forsyte/apalache/tla/lir/TypeTag.scala
- tlair/src/main/scala/at/forsyte/apalache/tla/lir/convenience/convenience.scala
- tlair/src/main/scala/at/forsyte/apalache/tla/lir/transformations/standard/IncrementalRenaming.scala
- tlair/src/main/scala/at/forsyte/apalache/tla/lir/transformations/standard/ModuleByExTransformer.scala
- tlair/src/test/scala/at/forsyte/apalache/tla/lir/TestAux.scala
- tlair/src/test/scala/at/forsyte/apalache/tla/lir/TestLirValues.scala
- tlair/src/test/scala/at/forsyte/apalache/tla/lir/transformations/standard/TestDeclarationSorter.scala
This is a step toward the integration of the type checker #521. This PR adds type tags to `TlaDecl`, similar to what we did with `TlaEx`. It includes structural changes to the code, which are not visible to the users.
> add type tags to TlaDecl

- UNRELEASED.md
- tla-types/src/main/scala/at/forsyte/apalache/tla/typecheck/etc/ToEtcExpr.scala
- tla-types/src/test/scala/at/forsyte/apalache/tla/typecheck/etc/TestToEtcExpr.scala
This PR adds type signatures for the operators that are defined in the module [TLC](https://github.com/jameshfisher/tlaplus/blob/master/org.lamport.tla.toolbox/StandardModules/TLC.tla). Some of these signatures are pretty useless. For instance, `TLC!Any` has the type `() => a`, which does not help the type checker. Also, `TLC!Assert` does not have a well-defined type, so we label it with `(a, Str) => Bool`.
> close #601: type signatures for the TLC module

- tla-bmcmt/src/test/scala/at/forsyte/apalache/tla/bmcmt/TestRewriterKeraSet.scala
- tlair/src/main/scala/at/forsyte/apalache/tla/lir/TlaDecl.scala
- tlair/src/main/scala/at/forsyte/apalache/tla/lir/TlaEx.scala
- tlair/src/main/scala/at/forsyte/apalache/tla/lir/transformations/standard/DeepCopy.scala
- tlair/src/test/scala/at/forsyte/apalache/tla/lir/IrGenerators.scala
- tlair/src/test/scala/at/forsyte/apalache/tla/lir/TestTransformations.scala
- tlair/src/test/scala/at/forsyte/apalache/tla/lir/transformations/standard/TestDeclarationSorter.scala
- tlair/src/test/scala/at/forsyte/apalache/tla/lir/transformations/standard/TestDeepCopy.scala
- tlair/src/test/scala/at/forsyte/apalache/tla/lir/transformations/standard/TestFlatLanguagePred.scala
- tlair/src/test/scala/at/forsyte/apalache/tla/lir/transformations/standard/TestIncrementalRenaming.scala
- tlair/src/test/scala/at/forsyte/apalache/tla/lir/transformations/standard/TestIncrementalRenamingScalacheck.scala
- tlair/src/test/scala/at/forsyte/apalache/tla/lir/transformations/standard/TestInlinerofUserOper.scala
- tlair/src/test/scala/at/forsyte/apalache/tla/lir/transformations/standard/TestKeraLanguagePred.scala
- tlair/src/test/scala/at/forsyte/apalache/tla/lir/transformations/standard/TestPrimePropagation.scala
More ground work towards integration of the new type checker:
1. `DeepCopy` is now copying types.
2. Add `TestDeepCopy` to test that `DeepCopy` does a complete copy, including types, but does not copy the identifiers.
3. `IrGenerators` are now generating tag types: either `Untyped()` or `Typed[Int](i)` for a random number `i`.
3. Move the test (yep, the only one!) for `InlinerOfUserOper` to its own class.
4. Add missing annotation `@RunWith(classOf[JUnitRunner])` to several tests. They were not running automatically!
> Ground work for #521

- script/release-prepare.sh
Last week there was some trouble with the release process. This adds
instructions to the release PRs to reduce the chance of error (as a stop
gap to improved automation).
> Add instructions to release PRs

- docs/src/apalache/profiling.md
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/passes/BoundedCheckerPassImpl.scala
The profiling feature was not transferred from the old model checker code to the new one. This PR fixes this problem.
> recovered the profiling code

- docs/src/SUMMARY.md
Followup to #571, which added a link to HOWTOs/index.md but didn't
include that page in the summary, resulting in a 404.
-------
> Fix link to HOWTO's

- script/release-prepare.sh
Follow up to #612
The wrong phrase ended up as the title of release PRs. The first
`--message` argument given to `hub` will end up as the title of the PR,
which should be the commit. This is change returns the commit message of
the release commit to that position, as intended.
-------
> Fix the release PR title

- UNRELEASED.md
- mod-tool/src/main/scala/at/forsyte/apalache/tla/Tool.scala
- mod-tool/src/main/scala/at/forsyte/apalache/tla/tooling/opt/CheckCmd.scala
- test/tla/Bug20190118.tla
- test/tla/Bug20201118.tla
- test/tla/Fix333.tla
- test/tla/Fix365_ExistsSubset.tla
- test/tla/Fix365_ExistsSubset2.tla
- test/tla/Fix365_ExistsSubset3.tla
- test/tla/Fix531.tla
- test/tla/SafeMath.tla
- test/tla/UnchangedExpr471.tla
- test/tla/cli-integration-tests.md
- test/tla/factorization.tla
- test/tla/mis.tla
- test/tla/y2k.tla
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/config/CheckerExceptionAdapter.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/config/CheckerModule.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/passes/PostTypeCheckerPassImpl.scala
- tla-types/src/main/scala/at/forsyte/apalache/tla/typecheck/etc/ToEtcExpr.scala
- tla-types/src/main/scala/at/forsyte/apalache/tla/typecheck/passes/EtcTypeCheckerPassImpl.scala
- tla-types/src/main/scala/at/forsyte/apalache/tla/typecheck/passes/TypeCheckerModule.scala
- tla-types/src/test/scala/at/forsyte/apalache/tla/typecheck/etc/TestToEtcExpr.scala
- tla-types/src/test/scala/at/forsyte/apalache/tla/typecheck/etc/TestTypeCheckerTool.scala
This PR makes one more step towards the integration #521:
- The command `check` has a new option `--with-snowcat`, which enables the type checker in the beginning and the end of the pipeline
- Some of the model checker's tests are adapted to Snowcat. Some are still failing, so they are running without the option `--with-snowcat`.
- The types are still not propagated to the model checker itself
> One more step to #521

- UNRELEASED.md
- mod-tool/src/main/scala/at/forsyte/apalache/tla/Tool.scala
- mod-tool/src/main/scala/at/forsyte/apalache/tla/tooling/opt/TypeCheckCmd.scala
- tla-types/src/main/scala/at/forsyte/apalache/tla/typecheck/passes/EtcTypeCheckerPassImpl.scala
Snowcat is not optional any longer. Removed the options to disable it as well as CLI warnings.
> removed the optional flags and warnings for Snowcat

- UNRELEASED.md
- test/tla/Paxos.tla
- test/tla/Unchanged660.tla
- test/tla/cli-integration-tests.md
- tla-types/src/main/scala/at/forsyte/apalache/tla/typecheck/etc/ToEtcExpr.scala
- tla-types/src/test/scala/at/forsyte/apalache/tla/typecheck/etc/TestToEtcExpr.scala
A fix for the annoying complaint by the type checker. It was really easy. I believe that this the effect of designing the type checker right.
> close #660: UNCHANGED <<...>> treats the brackets as a tuple

- .github/ISSUE_TEMPLATE/bug_report.md
It wasn't clear from the template that the apalache version should be
included. This aims to make that clear, and a few other points, while
also improving the formatting of the template and making it easier for
reporters to use (hopefully) by putting the instructions in comments.
-------
> Clarify instructions on issue template

- CHANGES.md
- UNRELEASED.md
- mod-distribution/pom.xml
- mod-infra/pom.xml
- mod-tool/pom.xml
- pom.xml
- tla-assignments/pom.xml
- tla-bmcmt/pom.xml
- tla-import/pom.xml
- tla-pp/pom.xml
- tla-types/pom.xml
- tlair/pom.xml
This reverts commit c8ca2080dcc0c9b9b0762e4ac8de09c7cb4660de.
The release preparation branch was squashed in instead of merged, so we
so we lost the release commit. The easiest way to fix is to revert the
offending commit and cut the release fresh.
> Revert "[release] 0.15.0 (#695)"

- docs/src/HOWTOs/howto-write-type-annotations.md
- docs/src/SUMMARY.md
- docs/src/apalache/typechecker-snowcat.md
- docs/src/apalache/types-and-annotations.md
Updated the manual to reflect that Snowcat and the new types is the way to do things right now.
> closes #688: update the manual with the new types

- UNRELEASED.md
- docs/src/lang/booleans.md
- docs/src/lang/conditionals.md
- docs/src/lang/control-and-nondeterminism.md
- docs/src/lang/functions.md
- docs/src/lang/integers.md
- docs/src/lang/logic.md
- docs/src/lang/records.md
- docs/src/lang/sequences.md
- docs/src/lang/sets.md
- docs/src/lang/standard-operators.md
- docs/src/lang/tuples.md
This PR adds types of the standard operators in the language manual.
> Add types in the language manual

- UNRELEASED.md
- docs/src/HOWTOs/howto-write-type-annotations.md
- docs/src/tutorials/snowcat-tutorial.md
- test/tla/MissionariesAndCannibalsTyped.tla
This PR adds Recipe 6 on type aliases to the HOWTO on type annotations.
> update the HOWTO with type aliases

- test/tla/Deadlock712.tla
- test/tla/cli-integration-tests.md
Added a test that demonstrates #712.
> a simple test demonstrating 712

- docs/src/HOWTOs/howto-write-type-annotations.md
- docs/src/tutorials/snowcat-tutorial.md
A few fixes in the documentation after the bugs found by @istoilkovska
> fix the typo in typeAlias and add a warning on multiline comments

- script/release-publish.sh
Closes #716
This provides a stable link to download the latest artifacts.
> Add artifacts with no version suffix to release

- UNRELEASED.md
- mod-tool/src/main/scala/at/forsyte/apalache/tla/Tool.scala
- mod-tool/src/main/scala/at/forsyte/apalache/tla/tooling/opt/TestCmd.scala
- src/tla/Apalache.tla
- test/tla/TestGen.tla
- test/tla/cli-integration-tests.md
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/SymbStateRewriterImpl.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/GenRule.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/aux/ValueGenerator.scala
- tla-bmcmt/src/test/scala/at/forsyte/apalache/tla/bmcmt/TestSymbStateRewriterApalacheGen.scala
- tla-import/src/main/scala/at/forsyte/apalache/tla/imp/StandardLibrary.scala
- tla-types/src/main/scala/at/forsyte/apalache/tla/typecheck/etc/ToEtcExpr.scala
- tla-types/src/test/scala/at/forsyte/apalache/tla/typecheck/etc/TestToEtcExpr.scala
- tlair/src/main/scala/at/forsyte/apalache/tla/lir/oper/ApalacheOper.scala
- tlair/src/main/scala/at/forsyte/apalache/tla/lir/transformations/standard/KeraLanguagePred.scala
This PR closes #622. Perhaps, it also addresses #191, but I am not sure. What happens here:
- Add the operator `Apalache!Gen`. A call to `Gen(n)` produces a data structure of the proper type (basically, a tree) whose elements can also be data structures, and the number of elements is bounded by `n` at every level. For example, `Gen(5)` of type `Set(Int -> Bool)` produces a set of up to 5 functions, whose domains have up to 5 integers.
- Add the command `test <spec> <before> <action> <assertion>` to run a quick test for an action in isolation.
- Add an example that uses both `Gen` and `test` to do something great, see `TestGen.tla`.
This feature requires a proper documentation and probably a tutorial. I feel that we should experiment with it a bit.
> Generators of bounded data structures and the command 'test'

- UNRELEASED.md
- test/tla/UntypedConst.tla
- test/tla/UntypedVar.tla
- test/tla/cli-integration-tests.md
- tla-types/src/main/scala/at/forsyte/apalache/tla/typecheck/etc/ToEtcExpr.scala
This PR closes issue #705. The type checker complains about a missing annotation for a constant or a variable, instead of showing an error later.
> Closes 705: error on missing annotations

- UNRELEASED.md
- tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/ExprOptimizer.scala
- tla-pp/src/test/scala/at/forsyte/apalache/tla/pp/TestExprOptimizer.scala
Closes #748. That was a coding bug. Additionally, `ExprOptimizer` transforms `Cardinality(a..b)` to `b - a + 1`.
> closes #748: no exception on `Cardinality(a..b) > i`

- docs/src/apalache/running.md
Expanded the section on inductive invariants a bit, to say that the property must be checked against the inductive invariant.
> make the manual precise about inductive invariants

- UNRELEASED.md
- mod-tool/src/main/scala/at/forsyte/apalache/tla/Tool.scala
- test/tla/cli-integration-tests.md
This PR fixes bug #762. It creates the directory `$HOME/.tlaplus` if such a directory does not exist. Also, this PR adds exception processing around the statistics collector.
PS: I will create a PR in tlaplus to create the directory in tla2tools too, as it is an obvious issue.
> closes #762: create $HOME/.tlaplus if it does not exist

- UNRELEASED.md
- pom.xml
I think I have enough watching maven building things 3 times to get scoverage reports, which we have not been reading for years. We should integrate coverage into CI, which is planned for #373, but we should not impede builds on user machines.
Here is what I have on my machine:
```
mvn clean && mvn package  -Dmaven.test.skip=true
mvn clean && mvn package  -Dmaven.test.skip=true
```
Looks like a good improvement :P
> remove scoverage from maven builds

- UNRELEASED.md
- docs/src/HOWTOs/howto-write-type-annotations.md
- docs/src/adr/002adr-types.md
- tla-types/src/main/scala/at/forsyte/apalache/tla/typecheck/parser/Type1Lexer.scala
- tla-types/src/test/scala/at/forsyte/apalache/tla/typecheck/TestDefaultType1Parser.scala
Closes #773. This PR introduces one-line comments in the type grammar, in order to comment on long records, e.g.
```tla
(*
@type:
(
// the column of an n-th queen, for n in the sequence domain
Seq(Int),
// the index (line number) of the first queen
Int,
// the index (line number) of the second queen
Int
) => Bool;
*)
Attacks(queens,i,j)
```
> One-line comments in types

- UNRELEASED.md
- tla-types/src/main/scala/at/forsyte/apalache/tla/typecheck/etc/EtcTypeChecker.scala
- tlair/src/main/scala/at/forsyte/apalache/tla/lir/transformations/standard/DeclarationSorter.scala
- tlair/src/test/scala/at/forsyte/apalache/tla/lir/transformations/standard/TestDeclarationSorter.scala
This PR fixes two bugs in the declaration sorter. Closes #758 and #645.
> Fixing DeclarationSorter

- UNRELEASED.md
- tlair/src/main/scala/at/forsyte/apalache/tla/lir/io/PrettyWriter.scala
- tlair/src/test/scala/at/forsyte/apalache/tla/lir/io/TestPrettyWriter.scala
> closes #746: pretty printer outputs EXCEPT correctly

- UNRELEASED.md
- tla-assignments/src/main/scala/at/forsyte/apalache/tla/assignments/passes/PrimingPassImpl.scala
- tla-assignments/src/main/scala/at/forsyte/apalache/tla/assignments/passes/TransitionPassImpl.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/passes/AnalysisPassImpl.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/passes/VCGenPassImpl.scala
- tla-import/src/main/scala/at/forsyte/apalache/io/annotations/PrettyWriterWithAnnotations.scala
- tla-import/src/main/scala/at/forsyte/apalache/tla/imp/passes/SanyParserPassImpl.scala
- tla-import/src/test/scala/at/forsyte/apalache/io/TestPrettyWriterWithAnnotations.scala
- tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/passes/ConfigurationPassImpl.scala
- tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/passes/DesugarerPassImpl.scala
- tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/passes/InlinePassImpl.scala
- tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/passes/OptPassImpl.scala
- tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/passes/PreproPassImpl.scala
- tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/passes/UnrollPassImpl.scala
- tla-pp/src/test/scala/at/forsyte/apalache/tla/pp/TestTlcConfigImporter.scala
- tlair/src/main/scala/at/forsyte/apalache/tla/lir/io/CounterexampleWriter.scala
- tlair/src/main/scala/at/forsyte/apalache/tla/lir/io/PrettyWriter.scala
- tlair/src/main/scala/at/forsyte/apalache/tla/lir/io/TextLayout.scala
- tlair/src/main/scala/at/forsyte/apalache/tla/lir/io/TlaDeclAnnotator.scala
- tlair/src/main/scala/at/forsyte/apalache/tla/lir/io/TlaWriter.scala
- tlair/src/main/scala/at/forsyte/apalache/tla/lir/io/TlaWriterFactory.scala
- tlair/src/test/scala/at/forsyte/apalache/tla/lir/io/TestPrettyWriter.scala
This PR fixes two annoying bugs in the pretty writer:
Having that we can now feed the results of TLA+ passes back to the TLA+ parser. Two issues remain:
The workflow tasks:
> Fix pretty printer: write annotations correctly and extend the standard modules

- UNRELEASED.md
- bin/apalache-mc
- docs/src/apalache/running.md
- script/run-docker.sh
- test/tla/cli-integration-tests.md
Closes #790
This change alters the runner script to allow users to tune the JVM when running
Apalache. The runner script now appends its args whatever is already in the
JVM_ARGS environment variable. If a max heapsize is set by the user, it lets
that take precedence. 
-------
> Allow supplying the JVM args when running Apalache

- Dockerfile
- UNRELEASED.md
Prior to this change were were only using JDK 9 for the runtime. Afaict, there's no reason for us to so such an old version.
> Use the latest openjdk version for the runtime

- docs/src/apalache/features.md
Some clarifications and slight rewording on the documentation of supported features.
There are also two places where I am not sure what is meant, I'll call those out with comments.
> Suggested tweaks to the supported features docs

- UNRELEASED.md
- docs/src/HOWTOs/howto-write-type-annotations.md
- docs/src/adr/002adr-types.md
- test/tla/MissionariesAndCannibalsTyped.tla
The motivation for this change is given in the documentation. In brief,
this convention makes it easier for users to reason about where type
aliases should go, and prevents against name clashes that can lead
aliases to disappear.
> Document the `TypeAliases` operator convention

- .github/workflows/main.yml
This should be resolved in our github action setup now, and removing
the update will shave 50s or so off our macos builds.
> Remove homebrew update

- script/release-publish.sh
We've had a couple release pipeline failures because this directory
didn't exist. This change ensures it does exist.
> Make target dir in release script

- UNRELEASED.md
- tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/ConstAndDefRewriter.scala
This PR fixes #823 by adding type information into the overriding error message in the event of a type mismatch.
> Add type information to overriding error message

- UNRELEASED.md
- mod-tool/src/main/scala/at/forsyte/apalache/tla/Tool.scala
> Fix #830: produce no log on the help message

- UNRELEASED.md
- test/tla/FormulaRefs.tla
- test/tla/cli-integration-tests.md
- tla-io/src/main/scala/at/forsyte/apalache/tla/imp/OpApplTranslator.scala
- tla-io/src/test/scala/at/forsyte/apalache/tla/imp/TestSanyImporter.scala
Closes #876. Instead of producing a null expression, throw a parse error.
> Closes 876: parse error on TLAPS syntax

- UNRELEASED.md
- docs/src/lang/records.md
- test/tla/Bug874.tla
- test/tla/cli-integration-tests.md
- tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/ExprOptimizer.scala
Fixes #874
The fix is achieved by replacing the `IllegalArgumentException` with the more
fitting `TlaInputError`. The new error includes the offending record access, and
source location. See the included integration test for an example.
> Add user error for non-existent record field access

- UNRELEASED.md
- test/tla/Bug832.tla
- test/tla/Bug860.tla
- test/tla/cli-integration-tests.md
- tla-io/src/main/scala/at/forsyte/apalache/io/typecheck/parser/DefaultType1Parser.scala
Closes #860
This introduces a slight refactoring of the type annotation parser,
reducing the complexity of the top-level `typeExpr` parser, and
eliminating the ambiguity that was leading to the `MatchError` reported
in #860.
The principle changes are
- factoring the function and operator parsing into separate combinators
- differentiating a type expression wrapped in parentheses from the
parentheses wrapped list of type expressions that are unique to
operator arguments.
-------
> Fix #860: Unhandled exception when type-checking incorrect annotation syntax for operators

- UNRELEASED.md
- test/tla/Bug925.tla
- test/tla/cli-integration-tests.md
- tla-types/src/main/scala/at/forsyte/apalache/tla/typecheck/etc/TypeUnifier.scala
- tla-types/src/test/scala/at/forsyte/apalache/tla/typecheck/etc/TestTypeUnifier.scala
Fix infinite recursion in the type unifier
> closes #925: fix infinite recursion in the type unifier

- .github/workflows/main.yml
This should fix the failing MacOS CI builds.
I would like to update the CI pipeline to drop the ocaml/opam dependency all
together (this should be quite easy using a prebuilt mdx), but this fix
should work for now.
This fixes the CI failure for the moment.
-------
> Use setup-ocaml v2

- docs/src/lang/standard-operators.md
Fix the manual by removing the legacy operators, which are not supported by the tools.
> remove \supset, \supseteq, and \subset

- docs/src/apalache/features.md
The fact that `f@@g` prefers `f` to `g` is very unlike similar operators in other languages, and can be a cause of headaches for beginners.
> Update features.md to clarify semantics of `@@` operator

- docs/src/HOWTOs/howto-write-type-annotations.md
- docs/src/adr/002adr-types.md
- docs/src/apalache/types-and-annotations.md
- docs/src/idiomatic/003record-sets.md
- docs/src/idiomatic/MsgSetNew.tla
- docs/src/idiomatic/MsgSetOld.tla
- docs/src/specs/search/ParBMC.tla
- docs/src/tutorials/TwoPhase.tla
- docs/src/tutorials/snowcat-tutorial.md
Updates the use of TLA+ set union operator in the documentation. Closes #974.
> Replace \cup with \union in the documentation

- UNRELEASED.md
- test/tla/RecordExcept987.tla
- test/tla/cli-integration-tests.md
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/FunExceptRule.scala
> closes #987: use SortedMap.keySet instead of SortedMap.keys

- UNRELEASED.md
- test/tla/Bug985.tla
- test/tla/cli-integration-tests.md
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/analyses/SkolemizationMarker.scala
- tla-bmcmt/src/test/scala/at/forsyte/apalache/tla/bmcmt/analyses/TestSkolemizationMarker.scala
Closes #985: do not skolemize let-definitions that are used as values. The solution to introduce two versions of let-definitions: one that is skolemized and another that is not skolemized. The downside is that we have redundant definitions. We will have to introduce another pass that removes unused let-definitions.
> closes #985: do not skolemize let-definitions that are used as values

- .github/workflows/README.md
- .github/workflows/container.yml
Closes #1008
Introduces a CI workflow to build and publish docker containers to [our GitHub Packages](https://github.com/orgs/informalsystems/packages?repo_name=apalache).
Once this is working, I'll do a followup to document the location change.
> Add workflow to publish docker images to GitHub

- .github/workflows/main.yml
- README.md
- UNRELEASED.md
- docs/src/apalache/installation/docker.md
- docs/src/apalache/running.md
- script/run-docker.sh
Followup to #1011
This updates documentation and scripts to use the new docker tagging scheme
required by our move from docker hub to the github container registry.
-------
> Update all docker container references to point to GitHub container registry

- .github/workflows/release.yml
Otherwise the container publication action won't trigger when the
release is published.
Followup to #1013 and #1011
> Use apalache bot for releases

- UNRELEASED.md
- docs/src/apalache/running.md
- mod-tool/src/main/scala/at/forsyte/apalache/tla/Tool.scala
- mod-tool/src/main/scala/at/forsyte/apalache/tla/tooling/opt/ParseCmd.scala
- test/tla/cli-integration-tests.md
- tla-io/src/main/scala/at/forsyte/apalache/io/OutputManager.scala
- tla-io/src/main/scala/at/forsyte/apalache/io/lir/TlaWriterFactory.scala
- tla-io/src/main/scala/at/forsyte/apalache/tla/imp/passes/SanyParserPassImpl.scala
Closes #1072
Follow up to #1025, which caused a regression in the handling of the `--output` flag. Instead of writing the specified file, as it used (and as it seems it should), it was only writing to the `intermediate` subdirectory of the run directory, and then only when the `--write-intermediate` flag was also given.
This restores the previous behavior. I think the guiding principle for this kind of UI decision re: output files might be something like:
- Files that we generate automatically during runs should only ever be written to the rundir
- But if we are allowing users to get specific information out of apalche written to a file, then we should allow them to specify any file that for this output that is convenient for their process.
This PR also introduces a few utilities to the …
> Fix regression #1072 - parse output file not being created

- UNRELEASED.md
- test/tla/cli-integration-tests.md
- tla-io/src/main/scala/at/forsyte/apalache/tla/imp/passes/SanyParserPassImpl.scala
Followup to #1073
That fix introduced *another* regression test, which caused the of the
parser to always go to TLA. :(
-------
> Fix output format detection

- test/tla/Poly1107.tla
- test/tla/cli-integration-tests.md
- tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/InlinerOfUserOper.scala
- tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/LambdaTypeInliner.scala
Inlining was performing type substitution only on the body of a declaration, which caused the type tag of a polymorphic declaration to potentially desync from the types used inside the body, whenever that operator was instantiated with another polymorphic operator.
Followup to #1104. 
Closes #1088
> Fixes type synchronization after inlining

- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/SeqModelChecker.scala
Now that we output full filenames, the model checker prints unreadable sequences of filenames. This PR introduces a linefeed between filenames.
> improve error logging by the model checker

- UNRELEASED.md
- tla-io/src/main/scala/at/forsyte/apalache/io/OutputManager.scala
The previous code wasn't actually writing to the expected files, it was
just creating the writer!
:facepalm: 
Closes https://github.com/informalsystems/apalache-tests/issues/76
> Fix writing to custom rundir

- UNRELEASED.md
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/SymbStateDecoder.scala
- tla-bmcmt/src/test/scala/at/forsyte/apalache/tla/bmcmt/TestSymbStateDecoder.scala
This is towards a fix of #962, which reported functions with duplicate indices appearing in counterexamples.
My current understanding of the root cause of the problem is that this is because the spec in question (https://github.com/informalsystems/modelator/blob/c9b54c1c4cd753af833ae4a16b626e4d3a5cab94/modelator/tests/integration/tla/IBC_ics02.tla) adds duplicate indices to the function in its updates, and we are not currently constructing sets or functions in a way that de-dupes in such cases.
The two small changes currently included in this draft illustrate the problem. The test case added fails prior to the deduplication. However, deduplication in the case of `EXCEPT`-based updates is much more subtle, afaict. I *think* it should be possible in principle, but I'm not clear on the …
> Fix #962: Duplicate indices in functions

- UNRELEASED.md
- test/tla/MC3_TwoPhaseUFO.tla
- test/tla/ModelVal.tla
- test/tla/TwoPhaseUFO.tla
- test/tla/cli-integration-tests.md
- tla-types/src/main/scala/at/forsyte/apalache/tla/typecheck/ModelValueHandler.scala
- tla-types/src/test/scala/at/forsyte/apalache/tla/typecheck/TestModelValueHandler.scala
> Closes #1130:   Improve the format of uninterpreted constants to name_OF_TYPE

- UNRELEASED.md
- test/tla/Bug1136.tla
- test/tla/cli-integration-tests.md
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/smt/Z3SolverContext.scala
closes #1136. Simply translate it in `Z3SolverContext`.
> closes #1136: translate a^b for non-constants

- CONTRIBUTING.md
- docs/internal/dev/README.md
- docs/internal/dev/using-bloop.md
Bloop is an incremental build server that has (for me) helped alleviate
approximately %70 of the pain of developing in the context of the JVM+maven.
This just adds a few notes documenting the common usage patterns I've so far
found worth committing to memory.
-------
> Add dev documentation on use of bloop

- docs/src/adr/013adr-configuration.md
This ADR proposes adoption of the `PureConfig` library for configuration
management. Please see the ADR for details on the proposal.
Towards #1069
> ADR013: Configuration management system

- docs/src/adr/011adr-smt-arrays.md
Update to ADR11 describing how TLA+ functions and sequences are to be encoded using SMT arrays. The high level description is the main point of this PR. The `Code changes` subsection will be further detailed as the implementation progresses. Closes #1154.
> ADR section describing the encoding of TLA+ functions and sequences using SMT arrays

- UNRELEASED.md
- test/tla/SetAddDel.tla
- test/tla/cli-integration-tests.md
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/SetCupRule.scala
It seems that the only remaining incorrect use of implications when dealing with SMT arrays is in set union rule, which is fixed by this PR. Occurrences of implications in rules not yet supported by the arrays encoding will be looked at when these rules are reworked. Closes #1162.
> Replace implactions by ITE in array updates in set union rule

- UNRELEASED.md
- tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/Normalizer.scala
- tla-pp/src/test/scala/at/forsyte/apalache/tla/pp/TestNormalizer.scala
Here are some new tests for the normalizer, which currently has poor coverage as stated in https://github.com/informalsystems/apalache/issues/649. Scenarios that have some change in the expression are covered with individual tests, while expressions that should be left unchanged are all covered in a single test.
This also fixes a bug were temporal expressions with negated `\box` operators were being incorrectly normalized (see [discussion](https://github.com/informalsystems/apalache/pull/1165#discussion_r767738234)), and a bug where declarations inside negated `LET` expressions were not being normalized at all.
Fixes https://github.com/informalsystems/apalache/issues/649
> New test scenarios for Normalizer

- UNRELEASED.md
- docs/src/adr/009adr-outputs.md
- docs/src/apalache/config.md
- docs/src/apalache/running.md
- mod-tool/src/main/scala/at/forsyte/apalache/tla/Tool.scala
- mod-tool/src/main/scala/at/forsyte/apalache/tla/tooling/opt/ConfigCmd.scala
- mod-tool/src/main/scala/at/forsyte/apalache/tla/tooling/opt/General.scala
- test/tla/cli-integration-tests.md
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/SymbStateRewriterImpl.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/profiler/RuleStatLocator.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rewriter/RewriterConfig.scala
- tla-io/pom.xml
- tla-io/src/main/scala/at/forsyte/apalache/io/ConfigManager.scala
- tla-io/src/main/scala/at/forsyte/apalache/io/OutputManager.scala
Closes #1069
This adds the configuration management component, based around `PureConfig`,
decided for in #1156:
as the collection of loadable application configurations.
`syncFromCli` method.
> Add ConfigManager

- mod-tool/src/main/scala/at/forsyte/apalache/tla/Tool.scala
- mod-tool/src/main/scala/at/forsyte/apalache/tla/tooling/opt/ServerCmd.scala
- test/tla/cli-integration-tests.md
Closes #1115
This just adds the boilerplate to plumb in a the new `server` subcommand, and
run it through the integration tests.
I'm not updating the docs ore lease notes at this point, because the cli subcommand is just a dummy at this point.
-------
> Add server subcommand

- docs/src/adr/011adr-smt-arrays.md
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/SymbStateRewriterImplWithArrays.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/analyses/ExpansionMarker.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/caches/IntRangeCache.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rewriter/ConstSimplifierForSmt.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/FunCtorRule.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/SetCtorRule.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/SetCupRule.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/SetFilterRule.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/SetUnionRule.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/aux/CherryPick.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/aux/PowSetCtor.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/smt/PreproSolverContext.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/smt/Z3SolverContext.scala
- tla-bmcmt/src/test/scala/at/forsyte/apalache/tla/bmcmt/TestSymbStateRewriterSet.scala
- tlair/src/main/scala/at/forsyte/apalache/tla/lir/Builder.scala
- tlair/src/main/scala/at/forsyte/apalache/tla/lir/oper/ApalacheOper.scala
This PR adds two new IR operators, `storeInSetOneStep` and `storeInSetLastStep`, which are variants of `storeInSet`. The existing store operator updates one entry of a SMT array. The new operators, which need to be used in conjunction, allow for the update of an arbitrary number of entries to be encoded into a single clause, thus avoiding the creation of unnecessary intermediary arrays. These new operators are intended to be used only for sequences of updates, thus the `storeInSet` operator remains useful for single updates. Closes #1171.
The arrays encoding will change from
```
(assert (= ite cond_1 (= (set_1 (store set_0 elem_1 true))) (= (set_1 set_0))))
(assert (= ite cond_2 (= (set_2 (store set_1 elem_2 true))) (= (set_2 set_1))))
(assert (= ite cond_3 (= (set_3 (store set_2 elem_3 …
```
> Add IR operators for compound set update

- test/tla/cli-integration-tests.md
- tla-types/src/main/scala/at/forsyte/apalache/tla/typecheck/passes/EtcTypeCheckerPassImpl.scala
If a type error is present Snowcat outputs `Snowcat asks you to fix the types. Meow.`, while if everything is ok it outputs `Your types are great!`. This PR fixes the imbalance in cat puns by updating the ok message to `Your types are purrfect!`.
> Make Snowcat purr when it is happy

- docs/src/SUMMARY.md
- docs/src/adr/015adr-trace.md
closes #1188
This ADR introduces a simplified format for counterexamples and traces of distributed systems in general.
> closes #1188: an ADR on the trace format

- mod-tool/src/main/scala/at/forsyte/apalache/tla/Tool.scala
This tiny refactor is just some incidental cleanup on the CLI plumbing.
- It removes the `injectorFacotry`
- It reorders the arguments to `handleExceptions`
In the current state of the code, the injectorFactory looks like it's
just adding unhelpful indirection. Removing it allows us to save about
10 lines of code and remove an unreachable throw.
The arguments to `handleExceptions` are reordered to reflect the the
underlying logic better. I.e., we call the `runner` on the `injector`
and `cmd`, so the `runner` is now supplied first.
-------
> Factor out the injectorFactory

- UNRELEASED.md
- test/tla/cli-integration-tests.md
- tla-io/src/main/scala/at/forsyte/apalache/io/ConfigManager.scala
@Kukovec reported that `~` was not be expanded in configured paths correctly.
Indeed, this was an oversight on my part. I failed to correctly override
pureconfig's reader for `Path` and `File` types. This PR fixes that mistake.
Followup to #1160
> Fix expansion of ~ in configured paths

- tla-pp/pom.xml
Closes #1219 
51228a7 had the unintended consequence of triggering the maven/surefire
design bug reported in https://issues.apache.org/jira/browse/MJAR-138.
The effect of this was to break some of our build targets that skip
tests by setting `maven.test.skip=true`, because it would not build the
tlair jar when tests were skipped, but would then still require that the
jar be present to compile.
This fix implemented the workaround described at
https://issues.apache.org/jira/browse/MJAR-138?focusedCommentId=16160394&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-16160394
-- namely, we add a maven profile that only includes the dependency when
`mavne.test.skip=false`.
-------
> Fix build config to allow skipping tests

- UNRELEASED.md
- tla-io/src/main/scala/at/forsyte/apalache/io/lir/ItfCounterexampleWriter.scala
- tla-io/src/test/scala/at/forsyte/apalache/io/lir/TestItfCounterexampleWriter.scala
A quickfix introduced by a bug in the ITF counterexample writer
> bugfix for the empty function in the ITF writer

- tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/ConstSimplifierBase.scala
- tla-pp/src/test/scala/at/forsyte/apalache/tla/pp/TestConstSimplifier.scala
This fixes a problem in out test suite where scalacheck would generate expressions with exponentiation of big numbers and make some tests really slow. This happens because we began using `BigInt.pow` for all scenarios in https://github.com/informalsystems/apalache/pull/1191 and `BigInt.pow` has a huge size limit, therefore trying to compute giant operations. `Math.pow` uses doubles and has a much more reasonable size limit, ensuring any combination of numbers is computable in feasible time.
> Use doubles to calculate constant exponentiation

- tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/ConstSimplifierBase.scala
- tla-pp/src/test/scala/at/forsyte/apalache/tla/pp/TestConstSimplifier.scala
This fixes https://github.com/informalsystems/apalache/issues/1235 by using `BigInt#pow` to obtain consistent results without floating point problems, but only after using `Math.pow` to estimate the result size and ensure its not too big and, therefore, too slow to compute.
> Fix exponentiation inconsistency

- docs/src/adr/011adr-smt-arrays.md
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/SetFilterRule.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/smt/Z3SolverContext.scala
- tlair/src/main/scala/at/forsyte/apalache/tla/lir/Builder.scala
- tlair/src/main/scala/at/forsyte/apalache/tla/lir/oper/ApalacheOper.scala
This PR rewrites the set filter rule to use SMT map, in order to improve solving efficiency. See the update to ADR011 for details. Closes #1229.
> Rewrite filter rule to use SMT map

- .github/workflows/container.yml
This is a followup to #1234, which accidentally broke the continuous
deployment of docker containers to the github container registry.
This happened because we are now generating our docker files based 
on the sbt build configuration, but the current github workflow expects
a Dockerfile in the root of the project. The proposed fix here (to be
tested once the PR is merged into unstable) is to generate the docker
file using our make target, and then point the github action to the 
"context" (directory) where the build file and its related artifacts are stored
in our artifact dir.
This patch fixes that buy first building the docker image, before
invoking the github action to upload the image to the registry
-------
> Fix docker continuous deployment

- build.sbt
- tla-bmcmt/src/test/scala/at/forsyte/apalache/tla/bmcmt/TestSymbStateRewriterAssignment.scala
- tla-bmcmt/src/test/scala/at/forsyte/apalache/tla/bmcmt/trex/ExecutorBase.scala
- tla-bmcmt/src/test/scala/at/forsyte/apalache/tla/bmcmt/trex/TestTransitionExecutorWithIncrementalAndOOPSLA19.scala
- tla-bmcmt/src/test/scala/at/forsyte/apalache/tla/bmcmt/trex/TestTransitionExecutorWithOfflineAndOOPSLA19.scala
- tlair/src/test/scala/at/forsyte/apalache/tla/lir/TestTransformations.scala
Igor hit a case earlier where the build of a test was failing but there was so
much noise in the output that it wasn't clear what was causing the failure. 
This pr adds some setup/teardown to tests that write noisly to stdout, and some
config flags to make the test output more concise and easier to read.
There are still some tests in `tla-io` dumping stuff to stdout, but afaict those tests seem to be written in such a way that I can't redirect stdout without breaking the tests...
> Improve clarity of test output

- bin/apalache-mc
- build.sbt
I was including the file in the fat jar as `Apalacha.tla` :facepalm: 
This PR also removes the part of the runner script that appends the location of the Apalache.tla modules into the path, since we don't need that and it adds more complexity to the end user artifact.
> Fix a typo in packaging `Apalache.tla` in jar

- UNRELEASED.md
- test/tla/Test1259.tla
- test/tla/cli-integration-tests.md
- tla-types/src/main/scala/at/forsyte/apalache/tla/typecheck/etc/ConstraintSolver.scala
- tla-types/src/test/scala/at/forsyte/apalache/tla/typecheck/etc/TestEtcTypeChecker.scala
Closes #1259 and #951. After all, it is a one-line fix. But given how hard it was to find, we should consider making quantified type variables explicit in the annotations and types.
> Fix unexpected polymorphism

- .github/workflows/main.yml
We're seeing some rate limiting from codecov. This might just be a hard limit of
the service, but thought adding in a codecov token might help.
-------
> Add codecov token

- test/tla/Test1275.tla
- test/tla/cli-integration-tests.md
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/config/CheckerExceptionAdapter.scala
- tla-io/src/main/scala/at/forsyte/apalache/tla/imp/AnnotationExtractor.scala
- tla-io/src/main/scala/at/forsyte/apalache/tla/imp/ParserExceptionAdapter.scala
- tla-io/src/test/scala/at/forsyte/apalache/tla/imp/TestSanyImporterAnnotations.scala
- tla-types/src/main/scala/at/forsyte/apalache/tla/typecheck/passes/EtcTypeCheckerAdapter.scala
Since TLA+ Toolbox is producing comments that look very much like ill-formed annotations, this PR downgrades the exception in `AnnotationExtractor` to a `log.error` message. Just in case, `AnnotationParseError` is still processed in all adapters.
> downgrade the exception to a log message

- test/mdx-test.py
Call `read()` on `process.stderr` file object
> Fix error output of mdx-test.py

- UNRELEASED.md
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/OrRule.scala
The newly implemented simplifications for `Or` expressions allow a generic expression to arise from simplification
since expressions like `\/ x` and `x \/ true` are now simplified to `x`. However, `OrRule` calls a simplification over an `Or` expression and expects the result to be either a value (`TRUE` or `FALSE`) or another `Or` expression. This expectation breaks with the newly introduced simplification.
Fixes https://github.com/informalsystems/apalache/issues/1285
> Bugfix for #1285

- docs/src/HOWTOs/uninterpretedTypes.md
Closes #1218
Update documentation on new format of uninterpreted constants introduced by #1130.
> Update documentation on uninterpreted types

- .gitignore
- test/tla/cli-integration-tests.md
I took the liberty of reviewing the `.gitignore` file, and pruned file formats that shouldn't be appearing in the directories at all anymore. Removing them from `.gitignore` also lets us see if these files still get produced, which would be a bug at this point (e.g. the missing `rm` in the tests file).
> Cleaned up `.gitignore`

- bin/run-in-docker-container
- script/run-docker.sh
Aims to fix the docker integration issues hit in #1317, and this PR is into
that feature branch.
This is probably the desired behavior for the docker container in any case,
since it allows it to function even more accurately as a mimic of the
uncontained executable.
-------
> Mount user's ~/.tlaplus dir in docker container

- UNRELEASED.md
- tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/Desugarer.scala
- tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/passes/DesugarerPassImpl.scala
- tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/passes/PreproPassImpl.scala
- tla-pp/src/test/scala/at/forsyte/apalache/tla/pp/TestDesugarer.scala
- [] Tests added for any new code
As per our discussions, `UNCHANGED x` now produces `x' := x`, instead of `x' = x`, when `x` is a `NameEx`. The behavior in the case of `UNCHANGED F[x]` remains unchanged; `(F[x]') = F[x]`
> `UNCHANGED` now introduces Apalache assignments, if possible

- UNRELEASED.md
- test/tla/TestSets.tla
- tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/ExprOptimizer.scala
- tla-pp/src/test/scala/at/forsyte/apalache/tla/pp/TestExprOptimizer.scala
Closes #1360. Simply preprocess `Cardinality(SUBSET S)`.
> Rewrite Cardinality(SUBSET S) into 2^Cardinality(S)

- build.sbt
This is a temporary fix for #1368, which lets `make package` go through on my computer. This needs a more thorough analysis though.
It is still producing error messages while unpacking:
```
[info] Unpacking package /Users/.../apalache/target/universal/apalache-0.20.4-SNAPSHOT.tgz to /Users/.../apalache/target/universal
[error] x apalache-0.20.4-SNAPSHOT/
[error] x apalache-0.20.4-SNAPSHOT/LICENSE
[error] x apalache-0.20.4-SNAPSHOT/bin/
[error] x apalache-0.20.4-SNAPSHOT/lib/
[error] x apalache-0.20.4-SNAPSHOT/lib/apalache.jar
[error] x apalache-0.20.4-SNAPSHOT/bin/apalache-mc
[info] Symlinking /Users/.../apalache/target/universal/current-pkg -> /Users/.../apalache/target/universal/apalache-0.20.4-SNAPSHOT
[success] Total time: 8 s, completed Feb 18, 2022 9:42:51 AM
```
> Remove --overwrite in apalacheCurrentPackage task to fix failing builds on MacOS

- CHANGES.md
- UNRELEASED.md
- script/release-publish.sh
Followup to #1357
We are now using the archives that are generated automatically by
sbt-native-packager. These don't include a `v` before the version in the
archive name. I missed this discrepancy when adjusting the release
script to the new packaging process.
This PR fixes the release script and reverts the changelog. Once this is merged
into master, we'll cut a new release, that will increment the tag and use the
same release notes for the next patch version.
> Revert CHANGES.md for tag v0.21.0 and fix release script

- tla-io/src/test/scala/at/forsyte/apalache/io/json/TestUJsonToTla.scala
- tla-pp/src/test/scala/at/forsyte/apalache/tla/pp/TestConstSimplifier.scala
- tla-pp/src/test/scala/at/forsyte/apalache/tla/pp/TestKeramelizer.scala
- tlair/src/test/scala/at/forsyte/apalache/tla/lir/IrGenerators.scala
- tlair/src/test/scala/at/forsyte/apalache/tla/lir/TestTlaDeclLevelFinder.scala
- tlair/src/test/scala/at/forsyte/apalache/tla/lir/TestTlaExLevelFinder.scala
- tlair/src/test/scala/at/forsyte/apalache/tla/lir/transformations/standard/TestIncrementalRenamingScalacheck.scala
Closes #1355
* Extends `IrGenerators` with function operators.
* Adds them to PBT specs where applicable.
> Extend `IrGenerators` with function operators

- CHANGES.md
- UNRELEASED.md
I forgot to increment the patch version for the next release, and so I hit a
tag collision when trying to cut the next release.
This just reverts the change log.
> Fix release 0.21.0 again

- tlair/src/test/scala/at/forsyte/apalache/tla/lir/IrGenerators.scala
`TlaFunOper.{funDef,recFunDef}` introduced in #1386 seem to cause lots of malformed expressions in PBT that slow down unit tests. Jure suggested this may happen in [#1386 (comment)](https://github.com/informalsystems/apalache/pull/1386#discussion_r811016316).
Therefore, disable them for now.
> Exclude operators causing malformed expressions from PBT

- mod-tool/src/main/scala/at/forsyte/apalache/tla/tooling/opt/General.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/SymbStateRewriterImpl.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/CardinalityConstRule.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/CardinalityRule.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/IntCmpRule.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/QuantRule.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/SeqOpsRule.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/SetExpandRule.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/SetInRule.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/aux/CherryPick.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/aux/MapBase.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/aux/PropositionalOracle.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/smt/Z3SolverContext.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/util/IntTupleIterator.scala
- tla-io/src/main/scala/at/forsyte/apalache/tla/imp/src/SourceStore.scala
- tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/UniqueNameGenerator.scala
- tlair/src/main/scala/at/forsyte/apalache/tla/lir/identifiers.scala
- tlair/src/main/scala/at/forsyte/apalache/tla/lir/io/Printer.scala
- tlair/src/main/scala/at/forsyte/apalache/tla/lir/transformations/TransformationTracker.scala
Towards #1064
The main thrust of this changeset is to fix compiler warnings of the form
``` sh
local var foo in method bar is never updated: consider using immutable val
```
This PR addresses the warnings by replacing the identified cases of unneeded
`var` with `val`.
I also made two unrelated fixes in
- 67ec68849cdb08a5b0cf4cdba44bc41ebffa52ab
- 6ff163b3fda56a9c06d69877f93b9bc77f977a98
These are special cases of unused values, too complicated for scalafix to
address automatically. See the individual commits for details.
> Fix compiler warnings for unused mutable variables

- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/aux/IntOracle.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/aux/OracleFactory.scala
Towards #1064
Identified by compiler warnings, this parameter is not used in the
method, or required by an interface.
-------
> Remove unused `SymbStateRewriter` arg to IntOracle.create

- UNRELEASED.md
- test/tla/Test1425.tla
- test/tla/bakery-pluscal/BakeryTyped.tla
- test/tla/bakery-pluscal/BakeryWoTlaps.tla
- test/tla/bakery-pluscal/README.md
- test/tla/cli-integration-tests.md
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/QuantRule.scala
- tla-bmcmt/src/test/scala/at/forsyte/apalache/tla/bmcmt/TestSymbStateRewriterAssignment.scala
This PR adds specs in `test/tla/bakery-pluscal`. This is an example of how one can check Pluscal specs with Apalache. This is the example for the issue #1412, which will be addressed in a separate PR.
The fix in [QuantRule.scala](https://github.com/informalsystems/apalache/compare/ik/pluscal1412?expand=1#diff-5a1e4fbfceb53d647606bc9106d8bb6880857e5737ef39804bafa5c253c0e49a) was already merged. However, I accidentally branched it off this branch.
> add the Bakery pluscal spec to test/tla

- tlair/src/test/scala/at/forsyte/apalache/tla/lir/IrGenerators.scala
This fixes an infinite (non-`size`-decreasing) chain of generator calls via `genTlaEx` -> `genLetInEx` -> `genTlaOperDecl` -> `genTlaEx`, where in `genTlaEx` a non-resized reference of `genTlaEx` is passed via the `exGen` parameters of `genLetInEx` and `genTlaOperDecl`, where it is (recursively) called.
It seems this infinite chain was only eventually broken by the ScalaCheck RNG.
We fix this by resizing `genTlaEx` in `genTlaOperDecl`.
I checked the call graph for other such cycles, but haven't found any.
This PR also re-enables function constructors in PBT, which where disabled for performance regression in #1401.
Hypothetically, this regression was not introduced directly the additional operators, but by the infinite chain of generator calls fixed in this PR.
Closes #1402
> Prevent infinite chain of generator calls and re-enable function constructors in PBT

- UNRELEASED.md
- docs/src/apalache/features.md
- test/tla/TestSequences.tla
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/FunExceptRule.scala
- tla-bmcmt/src/test/scala/at/forsyte/apalache/tla/bmcmt/TestSymbStateRewriterSequence.scala
Close #324. This PR implement the missing feature that allows one to write `[seq EXCEPT ![e1] = e2]`, where `seq` is a sequence.
> Implement EXCEPT applied to sequences

- tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/SetMembershipSimplifier.scala
- tla-pp/src/test/scala/at/forsyte/apalache/tla/pp/TestSetMembershipSimplifier.scala
Going forward with #723, this PR adds code to simplify the following in `TypeOK`:
- power sets (`SUBSET`),
- function sets (`[S1 -> s2]`), and
- nested expressions of these and previously supported expressions
:bulb: Probably easiest to review commit-by-commit. The first 2 commits contain refactoring that will become useful for the later commits.
> Simplify `SUBSET` and sets of functions `[S1 -> S2]` in `TypeOK`

- tla-pp/src/test/scala/at/forsyte/apalache/tla/pp/TestSetMembershipSimplifier.scala
Simple refactoring that splits `TestSetMembershipSimplifier` into multiple, smaller unit tests.
This is in prep for supporting records in #723
> Split TestSetMembershipSimplifier

- README.md
Remove #723 as beginner task on the landing page, as it's (almost) fully implemented
> Remove implemented beginner task from landing page

- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/smt/Z3SolverContext.scala
- tla-bmcmt/src/test/scala/at/forsyte/apalache/tla/bmcmt/TestSymbStateRewriterRecFun.scala
- tla-bmcmt/src/test/scala/at/forsyte/apalache/tla/bmcmt/rules/aux/TestPropositionalOracle.scala
- tla-bmcmt/src/test/scala/at/forsyte/apalache/tla/bmcmt/rules/aux/TestSparseOracle.scala
- tla-bmcmt/src/test/scala/at/forsyte/apalache/tla/bmcmt/rules/aux/TestUninterpretedConstOracle.scala
- tla-bmcmt/src/test/scala/at/forsyte/apalache/tla/bmcmt/smt/TestRecordingSolverContext.scala
- tla-pp/src/test/scala/at/forsyte/apalache/tla/pp/TestConstSimplifier.scala
- tla-types/src/test/scala/at/forsyte/apalache/tla/typecheck/TestDefaultType1Parser.scala
- tlair/src/main/scala/at/forsyte/apalache/tla/lir/predef/standardSets.scala
Towards #1064. Fixes all compiler warnings related to
- empty files (00f4926)
- catching all `Throwables` (ece65b5)
- Using `val` instead of `var` for immutable values (542d6e7)
- Type arguments eliminated by erasure (cb0742498ec5543423e814738b24fdc44fefbb06)
Further info in the commit comments.
> Fix some classes of compiler warnings

- UNRELEASED.md
- tla-io/src/main/scala/at/forsyte/apalache/io/annotations/parser/CommentPreprocessor.scala
- tla-io/src/test/scala/at/forsyte/apalache/io/annotations/TestCommentPreprocessor.scala
Closes #1304. This PR handles the cases when an annotation is starting either right after a linefeed, or right after the comment token. The logic of this preprocessor is getting harder to understand.
> Fix the comment preprocessor

- CONTRIBUTING.md
- Makefile
- Updates the `.PHONY` Makefile targets to reflect the status quo
- Updates `CONTRIBUTING.md` to reflect that we're running scalafix as part of the `fmt-fix` target
> Cleanup Makefile targets & supporting docs

- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/SymbStateDecoder.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/vmt/EUFRule.scala
- tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/Desugarer.scala
- tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/passes/ConfigurationPassImpl.scala
- tla-pp/src/test/scala/at/forsyte/apalache/tla/pp/TestDesugarer.scala
- tla-pp/src/test/scala/at/forsyte/apalache/tla/pp/TestUnroller.scala
Towards #1064 
Fix compiler warnings on non-exhaustive matches.
Rationale for each fix in the commit message.
> Fix compiler warnings on non-exhaustive matches

- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/DomainRule.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/RecFunDefAndRefRule.scala
- tla-bmcmt/src/test/scala/at/forsyte/apalache/tla/bmcmt/TestVCGenerator.scala
- tla-bmcmt/src/test/scala/at/forsyte/apalache/tla/bmcmt/rules/aux/TestPropositionalOracle.scala
- tla-bmcmt/src/test/scala/at/forsyte/apalache/tla/bmcmt/rules/aux/TestSparseOracle.scala
- tla-bmcmt/src/test/scala/at/forsyte/apalache/tla/bmcmt/rules/aux/TestUninterpretedConstOracle.scala
- tla-io/src/test/scala/at/forsyte/apalache/tla/imp/TestSanyImporter.scala
- tla-io/src/test/scala/at/forsyte/apalache/tla/imp/TestSanyImporterStandardModules.scala
Towards #1064. Fixes/silences compiler warnings of the shape
pattern var v in value V is never used: use a wildcard `_` or suppress this warning with `v@_`
Similar modifications are grouped into the same commit.
> Fix compiler warnings for unused pattern vars

- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/Arena.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/LazyEquality.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/SymbStateDecoder.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/SymbStateRewriterAuto.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rewriter/SymbStateRewriterListener.scala
- tla-io/src/main/scala/at/forsyte/apalache/io/OutputManager.scala
- tla-io/src/main/scala/at/forsyte/apalache/io/lir/TlaDeclAnnotator.scala
- tla-io/src/main/scala/at/forsyte/apalache/tla/imp/ModuleTranslator.scala
- tla-io/src/main/scala/at/forsyte/apalache/tla/imp/NullOpDefTranslator.scala
- tla-io/src/test/scala/at/forsyte/apalache/tla/imp/TestSanyImporter.scala
- tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/TlcConfigImporter.scala
- tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/passes/ConfigurationPassImpl.scala
- tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/passes/ReTLAInlinePassImpl.scala
- tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/passes/ReTLAPreproPassImpl.scala
- tla-pp/src/test/scala/at/forsyte/apalache/tla/pp/TestTlcConfigImporter.scala
- tla-pp/src/test/scala/at/forsyte/apalache/tla/pp/TestUniqueNameGenerator.scala
- tla-types/src/main/scala/at/forsyte/apalache/tla/typecheck/etc/EtcTypeChecker.scala
- tlair/src/main/scala/at/forsyte/apalache/tla/lir/formulas/Base.scala
- tlair/src/main/scala/at/forsyte/apalache/tla/lir/oper/TlaOper.scala
Towards #1064. First chunk of fixes for compiler warnings of the shape
parameter value arg in {class, method} MySymbol is never used
Rationale for the fix in the commit message.
> Fix unused parameter compiler warnings

- UNRELEASED.md
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/SymbStateRewriter.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/SymbStateRewriterAuto.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/SymbStateRewriterImpl.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/caches/DefaultValueCache.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rewriter/SymbStateRewriterSnapshot.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/ChooseRule.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/FunAppRule.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/IfThenElseRule.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/QuantRule.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/RecCtorRule.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/SeqOpsRule.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/aux/CherryPick.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/aux/DefaultValueFactory.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/aux/ProtoSeqOps.scala
Closes #1348. This PR introduces `DefaultValueCache` that caches calls to `DefaultValueFactory`. Since caches operate over arenas, not states, this PR required some refactoring of `DefaultValueFactory`.
> Cache default values

- tla-bmcmt/src/test/scala/at/forsyte/apalache/tla/bmcmt/TestArena.scala
- tla-bmcmt/src/test/scala/at/forsyte/apalache/tla/bmcmt/TestArenaWithArrays.scala
- tla-bmcmt/src/test/scala/at/forsyte/apalache/tla/bmcmt/TestArenaWithOOPSLA19.scala
- tla-bmcmt/src/test/scala/at/forsyte/apalache/tla/bmcmt/smt/TestRecordingSolverContext.scala
- tla-bmcmt/src/test/scala/at/forsyte/apalache/tla/bmcmt/smt/TestRecordingSolverContextWithArrays.scala
- tla-bmcmt/src/test/scala/at/forsyte/apalache/tla/bmcmt/smt/TestRecordingSolverContextWithOOPSLA19.scala
- tla-io/src/main/scala/at/forsyte/apalache/tla/imp/StandardLibrary.scala
- tla-types/src/main/scala/at/forsyte/apalache/tla/typecheck/etc/ToEtcExpr.scala
- tla-types/src/test/scala/at/forsyte/apalache/tla/typecheck/etc/TestToEtcExpr.scala
Towards #1473, #1064
Fixes all current compiler deprecation warnings.
This addresses two kinds of warnings; rationale for each fix in the commit message.
> Fix compiler deprecation warnings

- tlair/src/test/scala/at/forsyte/apalache/tla/lir/transformations/standard/TestDeclarationSorter.scala
`DeclarationSorter` writes a witness file `dependencies.dot` when it detects cyclic dependencies.
In unit tests with cyclic input: assert that this file is written, then remove it.
Ensures a clean working directory after running `make test`.
> Clean graphviz output after cyclic declaration tests

- test/mdx-test.py
Small fix for `mdx-test.py`: `corrected_file` and `test_file` were flipped when converting from Path to string.
I think the call to `diff` below is still fine, because it now reports `test.md` as `---` and `test.md.corrected` as `+++`, as I would expect:
$ test/mdx-test.py --test test/tla/test.md
--- /Users/.../test.md
+++ /Users/.../test.md.corrected
@@ -1,5 +1,6 @@
```sh
$ pwd
+/Users/.../tla
```
> Fix flipped test_file and corrected_file

- docs/src/SUMMARY.md
- docs/src/tutorials/index.md
This link currently does not work: [https://apalache.informal.systems/docs/tutorials/index.html](https://www.google.com/url?q=https://apalache.informal.systems/docs/tutorials/index.html&sa=D&source=docs&ust=1647614328718738&usg=AOvVaw3LIEqwpST0_p703Xk0NjPn). This fixes the problem and update the index context to list our newest tutorials.
> Fix tutorials index on docs

- src/tla/__apalache_folds.tla
- src/tla/__apalache_internal.tla
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/SymbStateRewriterImpl.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/SeqOpsRule.scala
- tla-bmcmt/src/test/scala/at/forsyte/apalache/tla/bmcmt/TestSymbStateRewriterSequence.scala
- tla-io/src/main/scala/at/forsyte/apalache/tla/imp/StandardLibrary.scala
- tla-types/src/main/scala/at/forsyte/apalache/tla/typecheck/etc/ToEtcExpr.scala
- tla-types/src/test/scala/at/forsyte/apalache/tla/typecheck/etc/TestToEtcExpr.scala
- tlair/src/main/scala/at/forsyte/apalache/tla/lir/oper/ApalacheInternalOper.scala
- tlair/src/main/scala/at/forsyte/apalache/tla/lir/transformations/standard/KeraLanguagePred.scala
- tlair/src/test/scala/at/forsyte/apalache/tla/lir/transformations/standard/TestKeraLanguagePred.scala
This PR adds two internals operators that are required by #1486 and #1527.
> add __ApalacheSeqCapacity and __NotSupportedByModelChecker

- .github/workflows/auto-update.yml
This should help alleviate the tedium resulting from the PR
updating/merging race condition.
When changes are pushed to our default branch, this action is meant to
check any PRs that have 'auto-merge' enabled, and trigger their update.
If everything works as intended, then once a PR is ready for merge and
we've enabled `auto-merge`, this action will do the work of ensuring the
PR is kept up to date in case a different PR is merged in before the CI
can complete.
-------
> Add auto-update github action

- .github/workflows/auto-update.yml
Without this, the updates triggered by this action won't allow the
subsequent CI to kick off. This is a limitation on what reactions
GitHub's API will trigger in response to the GITHUB_TOKEN.
> Use the apalache bot token for auto update

- mod-tool/src/main/scala/at/forsyte/apalache/tla/Tool.scala
- mod-tool/src/main/scala/at/forsyte/apalache/tla/tooling/opt/AbstractCheckerCmd.scala
Closes #1507
May provide clearer diagnostics for bug reports too.
With this change, the output now looks like this:
```sh
$  SMT_ENCODING=arrays apalache-mc check --next=Next --init=Init Foo.tla | rg "Checker options"
Checker options: (SMT_ENCODING=arrays) check --next=Next --init=Init Foo.tla I@16:45:25.503
```
-------
> Add all CLI args and env config to checker options

- .envrc
- .github/workflows/main.yml
- CONTRIBUTING.md
- build.sbt
Closes #1064
This setting is controlled via the environment variable
`APALACHE_FATAL_WARNINGS`, making it possible for developers to opt in
or out of having compiler warnings fail their builds locally.
Instructions on configuration have been added to CONTRIBUTING.md
-------
> Make warnings fatal in CI

- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/aux/DefaultValueFactory.scala
This is a one-line fix for the bug discovered in #1539.
> fix a bug in default values

- CONTRIBUTING.md
We're always using sentence case in [CHANGES.md](https://github.com/informalsystems/apalache/blob/unstable/CHANGES.md); update [CONTRIBUTING.md](CONTRIBUTING.md) accordingly.
> Fix capitalization of changelog entries

- UNRELEASED.md
- test/tla/TestSequences.tla
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/LazyEquality.scala
- tla-bmcmt/src/test/scala/at/forsyte/apalache/tla/bmcmt/TestSymbStateRewriterSequence.scala
Closes #1547. This bug was happening when two sequences had the capacity larger than their actual lengths.
> Fix the bug in equality of sequences

- UNRELEASED.md
- test/tla/TestSequences.tla
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/LazyEquality.scala
- tla-bmcmt/src/test/scala/at/forsyte/apalache/tla/bmcmt/TestSymbStateRewriterSequence.scala
My previous fix in #1548 was partially correct. This one hopefully fixes #1547.
> Fix the equality of sequences once again

- mod-tool/src/main/scala/at/forsyte/apalache/tla/Tool.scala
- test/tla/cli-integration-tests.md
Fixes #1504 – statistics collection was reported as `ON` even when disabled.
We previously only checked for existence of `~/.tlaplus/esc.txt` to report `ON`.
This fixes it to also check the file for a valid identifier (not `NO_STATISTICS`).
> Fix stats collection debug output

- UNRELEASED.md
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/EqRule.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/IntArithPacker.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/IntArithRule.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/IntCmpRule.scala
Closes #1342 
Pack arithmetic expressions in `IntCmpRule` and `EqRule`. Translate TLA+ arithmetic comparisons into a single SMT constraint, without introducing intermediate cells.
Uses the same logic for packing arithmetic expressions as #1541, which is refactored into a trait in 835e717.
> Pack integer arithmetic comparisons in IntCmpRule

- UNRELEASED.md
- build.sbt
- src/tla/__rewire_bags_ext_in_apalache.tla
- test/tla/TestBagsExt.tla
- test/tla/cli-integration-tests.md
- tla-io/src/main/scala/at/forsyte/apalache/tla/imp/StandardLibrary.scala
Closes #1524. This PR rewires the few operators of `BagsExt`. The following two operators are not supported as they require unbounded loops:
- `MapThenFoldBag`
- `FoldBag`
> support for BagsExt

- docs/src/SUMMARY.md
- docs/src/adr/016adr-retla.md
This is a technical PR, which clarifies the name of ADR016.
> Rename adr16 into ReTLA

- docs/src/apalache/tuning.md
Github markdown didn't pick up the nested list here.
> Properly indent nested markdown list

- docs/src/apalache/installation/source.md
Fix the instructions for building from source:
* Correct the Scala version `12.0` -> `2.12.0`
* Re-introduce instructions to source the shell env (otherwise unit tests will fail)
> Fix build from source docs

- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/SymbStateRewriterImplWithArrays.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/analyses/ExpansionMarker.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/caches/ModelValueCache.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rewriter/ConstSimplifierForSmt.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/CardinalityConstRule.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/SetAsFunRule.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/SetInRule.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/aux/UninterpretedConstOracle.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/aux/ValueGenerator.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/smt/PreproSolverContext.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/smt/Z3SolverContext.scala
- tla-types/src/main/scala/at/forsyte/apalache/tla/typecheck/etc/ToEtcExpr.scala
- tla-types/src/test/scala/at/forsyte/apalache/tla/typecheck/etc/TestToEtcExpr.scala
- tlair/src/main/scala/at/forsyte/apalache/tla/lir/Builder.scala
- tlair/src/main/scala/at/forsyte/apalache/tla/lir/oper/ApalacheInternalOper.scala
- tlair/src/main/scala/at/forsyte/apalache/tla/lir/oper/ApalacheOper.scala
The core of this PR is the move of six IR operators from `ApalacheOper` to `ApalacheInternalOper`. This affected many files. Most of them were handled by simple substitution, but I took the opportunity to rework some of the cases in which the touched operators were used, aiming to make the code clearer. Closes #1287.
> Move internal operators to ApalacheInternalOper

- UNRELEASED.md
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/smt/Z3SolverContext.scala
Closes #1594. This PR fixes a logging error and adds a missing constant declaration, both in `Z3SolverContext`. See the linked issue for details.
> Fix SMT logging in the arrays encoding

- UNRELEASED.md
- build.sbt
Change build.sbt to use [Files.createSymbolicLink](https://docs.oracle.com/javase/7/docs/api/java/nio/file/Files.html#createSymbolicLink(java.nio.file.Path,%20java.nio.file.Path,%20java.nio.file.attribute.FileAttribute...))
for compatibility with more OS's
> Switch symlink creation to use os-independent Files.createSymbolicLink

- tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/ExprOptimizer.scala
- tla-pp/src/test/scala/at/forsyte/apalache/tla/pp/TestExprOptimizer.scala
Changed the behaviour and modified the corresponding unit test
> Fix bug in cardinality optimization

- UNRELEASED.md
- src/tla/Variants.tla
- test/tla/TestVariants.tla
- tla-io/src/main/scala/at/forsyte/apalache/io/typecheck/parser/DefaultType1Parser.scala
- tla-io/src/main/scala/at/forsyte/apalache/io/typecheck/parser/Type1Lexer.scala
- tla-io/src/main/scala/at/forsyte/apalache/io/typecheck/parser/tokens.scala
- tla-types/src/test/scala/at/forsyte/apalache/tla/typecheck/TestDefaultType1Parser.scala
- tla-types/src/test/scala/at/forsyte/apalache/tla/typecheck/etc/TestToEtcExpr.scala
- tla-types/src/test/scala/at/forsyte/apalache/tla/typecheck/etc/TestTypeUnifier.scala
- tlair/src/main/scala/at/forsyte/apalache/tla/lir/TlaType1.scala
- tlair/src/test/scala/at/forsyte/apalache/tla/lir/TlaType1Gen.scala
Closes #1601. This PR contains the parser extension for new records, rows, and variants:
- The parser itself is in `DefaultType1Parser`.
- The new syntax co-exists with the old syntax.
- The parser tests are in `TestDefaultType1Parser`.
- I had to modify the lexer as well, but it is the technical part.
- I also had to modify `TlaType1.toString` to make the output compatible with the parser.
This PR builds on top of the PR #1592. When both are accepted, I will merge both of them.
The next thing is to update [ADR002](https://github.com/informalsystems/apalache/blob/unstable/docs/src/adr/002adr-types.md) with the extended syntax.
The big plan is explained in [ADR014](https://github.com/informalsystems/apalache/blob/unstable/docs/src/adr/014adr-precise-records.md) and …
> Parsing row types, records, and variants

- CONTRIBUTING.md
As per our discussion in today's meeting, this PR documents our convention for
locking PRs until we a chance to review them (when desired) and for our use of
the CODEOWNERS file.
It also includes an unrelated update to the documentation of our branching model.
> Document review locking and code curation

- UNRELEASED.md
- test/tla/RecMem1627.tla
- test/tla/cli-integration-tests.md
- tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/ExprOptimizer.scala
- tla-pp/src/test/scala/at/forsyte/apalache/tla/pp/TestExprOptimizer.scala
Closes #1627. This PR introduces an optimization for record membership, which is quite common in `TypeOK`:
```tla
r \in { [a |-> x, b |-> y]: x \in S, y \in T }
\* becomes
DOMAIN r = { "a", "b" } /\ r.a \in S /\ r.b \in T
```
> Optimize membership for record sets

- UNRELEASED.md
- docs/src/apalache/running.md
- docs/src/apalache/tuning.md
- mod-tool/src/main/scala/at/forsyte/apalache/tla/Tool.scala
- mod-tool/src/main/scala/at/forsyte/apalache/tla/tooling/opt/CheckCmd.scala
- test/tla/cli-integration-tests.md
We currently have 2 tuning flags, `--tuning=<file>` and `--tuning-options=key1=val1:key2=val2`. However, `--tuning-options` is called `--tune-here` throughout the documentation (the mismatch was already in the original PR).
As [discussed below](https://github.com/informalsystems/apalache/pull/1579#discussion_r838815069):
* Rename `--tuning` to `--tuning-options-file`.
* Fix references to `--tune-here` in the docs (to `--tuning-options`).
> Rename `--tuning-options` to `--tune-here`

- docs/src/adr/002adr-types.md
Move inline <code>```</code> to a new line.
This caused the bibliography to print as part of the code block, and links not being rendered.
> Fix Markdown end-of-codeblock

- mod-tool/src/main/scala/at/forsyte/apalache/tla/Tool.scala
- mod-tool/src/main/scala/at/forsyte/apalache/tla/tooling/opt/General.scala
- test/tla/cli-integration-tests.md
- tla-io/src/main/scala/at/forsyte/apalache/io/ConfigManager.scala
- tlair/src/main/scala/at/forsyte/apalache/tla/lir/Feature.scala
As per our discussion in the meeting today, this integrates the `--feature` CLI
flag into the configuration manager, allowing users to enable features via their
global or local config files.
Along the way, it reworks some of the base PR in order to improve code reuse,
and also fixes uncaught exceptions resulting from invalid config files.
Note that  this PR is into Igor's feature branch.
It should be easiest to review by commit, but the changes are hopefully pretty clear and well motivated anyhow.
> Integrate features flag into ConfigManager

- tla-bmcmt/src/test/scala/at/forsyte/apalache/tla/bmcmt/CrossTestEncodings.scala
Small improvements to the encodings comparison #1588:
- print RNG seeds
- label inputs
- use expected comparison `?=`
> Small improvements to the encodings comparison

- CONTRIBUTING.md
- mod-infra/src/test/resources/logback-test.xml
- tla-bmcmt/src/test/resources/logback-test.xml
Add silent logback configs for unit tests in in `mod-infra` and `tla-bmcmt`.
Since these are per (sub-)project, I'm starting with a minimal set for the unit tests in `TestPassChainExecutor` and `CrossTestEncodings`.
Closes #1666.
> Add silent logback config for unit tests

- test/tla/TestFunctions.tla
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/types/package.scala
Closes #1694. Actually, powersets are expanded before they reach functions. Hence `FunT` can be safely refactored in #1693.
> make sure that FunT does not need PowSetT

- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/smt/Z3SolverContext.scala
This PR refactors updates to `cellCache` to not happen during iterations. Closes #1595.
> Refactor Z3SolverContext cellCache

- UNRELEASED.md
- test/tla/OracleFunSet.tla
- test/tla/cli-integration-tests.md
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/smt/Z3SolverContext.scala
This PR makes elements of type `FinFunSetT` be encoded as SMT arrays. Closes #1680.
> Encode function sets as SMT arrays

- build.sbt
- tla-types/src/test/scala/at/forsyte/apalache/tla/typecheck/etc/TestTypeCheckerTool.scala
Towards #1577
Stop forking JVMs for unit tests.
This enables unit tests to run in parallel (forked tests [run sequentially by default](https://www.scala-sbt.org/1.x/docs/Testing.html#Forking+tests)).
This fixes some paths, because tests now run from the project root (instead of subproject directories).
Due to [this race in SANY](https://github.com/tlaplus/tlaplus/issues/688) we still need to run some unit tests sequentially.
> Stop forking JVMs for unit tests

- CHANGES.md
- build.sbt
- docs/src/adr/004adr-annotations.md
- docs/src/adr/010rfc-transition-explorer.md
- docs/src/apalache/features.md
- docs/src/apalache/installation/docker.md
- docs/src/apalache/principles/assignments.md
- docs/src/lang/sequences.md
- src/tla/Apalache.tla
- test/tla/SafeMath.tla
- tla-assignments/src/main/scala/at/forsyte/apalache/tla/assignments/SmtFreeSymbolicTransitionExtractor.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/config/CheckerExceptionAdapter.scala
- tlair/src/main/scala/at/forsyte/apalache/tla/lir/TlaType1.scala
Fixes #1643, fixes #1645
Fix outdated URLs in source code + docs
After this, all URLs found by the regex from #1645 are working.
> Fix outdated URLs

- UNRELEASED.md
- mod-infra/src/main/scala/at/forsyte/apalache/infra/DefaultExceptionAdapter.scala
- mod-infra/src/main/scala/at/forsyte/apalache/infra/ExceptionAdapter.scala
- mod-tool/src/main/scala/at/forsyte/apalache/tla/Tool.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/config/CheckerExceptionAdapter.scala
- tla-io/src/main/scala/at/forsyte/apalache/tla/imp/ParserExceptionAdapter.scala
- tla-types/src/main/scala/at/forsyte/apalache/tla/typecheck/passes/EtcTypeCheckerAdapter.scala
Handle `java.lang.OutOfMemoryError` (i.e., out of heap memory) gracefully:
* Refactor exception adapters to accept `Throwable` ➞ [0cd916f](https://github.com/informalsystems/apalache/pull/1711/commits/0cd916f33fa8e22d3b2928c170d0413eba6fe570)
(`OutOfMemoryError` derives from `Error`, not `Exception`)
* Add cases to the exception adapters ➞ [7ccc716](https://github.com/informalsystems/apalache/pull/1711/commits/7ccc716dd063b4bfcce27642cfdf9aa73a12d592)
* Add an early catch handler for when logging and injection aren't set up yet ➞ [3236762](https://github.com/informalsystems/apalache/pull/1711/commits/3236762e76ec5b2cf1afa9f327e2a6efe980b51e)
Fixes #466
> Handle heap memory exhaustion gracefully

- mod-tool/src/main/scala/at/forsyte/apalache/tla/Tool.scala
- mod-tool/src/main/scala/at/forsyte/apalache/tla/tooling/ExitCodes.scala
Rename (unused) `ExitCodes.NO_ERROR` to `ExitCodes.OK` and use it in `Tool` instead of the locally declared constant.
> Refactor `ExitCodes.OK`

- UNRELEASED.md
Note support of AArch64 through #751 and #1718 in the release notes.
⚠️ Set to auto-merge.
> Note support for aarch64 in release notes

- .gitignore
Folders that should not be pushed to the repo, containing local data for Metals and VSCode
> Add .metals and .vscode to gitignore

- .github/workflows/main.yml
- Makefile
Closes #1741
Removes the fatal warnings configuration from all our other CI jobs, and instead
runs a separate job that just compiles the code (including test code) with
fatal warnings enabled. This should provide fast feedback for compiler warnings
without interfering with other tests.
> Add separate CI workflow to check for compiler warnings

- tla-types/src/main/scala/at/forsyte/apalache/tla/typecomp/BuilderUtil.scala
- tla-types/src/main/scala/at/forsyte/apalache/tla/typecomp/ScopedBuilder.scala
- tla-types/src/main/scala/at/forsyte/apalache/tla/typecomp/TypeComputationFactory.scala
- tla-types/src/main/scala/at/forsyte/apalache/tla/typecomp/package.scala
- tla-types/src/main/scala/at/forsyte/apalache/tla/typecomp/signatures/ArithOperSignatures.scala
- tla-types/src/main/scala/at/forsyte/apalache/tla/typecomp/signatures/BaseOperSignatures.scala
- tla-types/src/main/scala/at/forsyte/apalache/tla/typecomp/signatures/BoolOperSignatures.scala
- tla-types/src/main/scala/at/forsyte/apalache/tla/typecomp/signatures/SeqOperSignatures.scala
- tla-types/src/main/scala/at/forsyte/apalache/tla/typecomp/signatures/SetOperSignatures.scala
- tla-types/src/main/scala/at/forsyte/apalache/tla/typecomp/unsafe/ProtoBuilder.scala
- tla-types/src/main/scala/at/forsyte/apalache/tla/typecomp/unsafe/UnsafeSetBuilder.scala
- tla-types/src/test/scala/at/forsyte/apalache/tla/typecomp/BuilderTest.scala
- tla-types/src/test/scala/at/forsyte/apalache/tla/typecomp/TestBaseBuilder.scala
- tla-types/src/test/scala/at/forsyte/apalache/tla/typecomp/TestSeqBuilder.scala
- tla-types/src/test/scala/at/forsyte/apalache/tla/typecomp/TestSetBuilder.scala
In order to support `Builder` construction of expressions with type variables we needed to redesign the old approach to signatures. Now, instead of constructing a signature as `OperT1(from, to)`, where `from` contains freshly generated typevars, which have to be unified (and would need to be substituted later if we continued with the old approach), we construct signatures as (partial) functions `from => to`. 
This also simplifies the code, as there is no longer a need for a) `varPool`s and b) arity-hints.
> Typed Builder implementation Part 3.5: Polymorphism support

- docs/src/adr/0190-harmonize-changelog.md
Closes #1538
This ADR evaluates all the options we've discussed to remove friction
from merge conflicts in the changelog. It also sets out the solution we
see to have agreed upon in our meetings. But not this is only a proposal
at this stage, and the decision can be altered if we come up with a
better approach.
Please leave comments or suggest change if you see ways to improve upon
the plan or reasons to select a different choice.
> Add ADR 019 proposing improvement of changelog

- docs/src/apalache/installation/docker.md
- docs/src/apalache/running.md
Closes #1796
Remove outdated references to dockerhub and instead point all docker
references to the ghcr location.
> Fix references to docker container

- .unreleased/bug-fixes/1819.md
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/smt/Z3SolverContext.scala
This PR makes makes the solver context query Z3 if a model evaluation returns an undefined result. See the linked issue for details. Closes #1819.
> Handle undefined results from model evaluation

- .unreleased/bug-fixes/1840.md
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/SetInRuleWithArrays.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/aux/CherryPick.scala
This PR makes cherry picking of functions equate the function's domain, for which SMT constraints are generated, to the domain components of the function's relation, for which no SMT constraints are generated. Without the newly added lazy equality constraints, equivalent but not identical records are treated differently by the decoder, leading to spurious counter-examples.
The PR also contain a small fix to the use of SMT equality in set membership, which ensures that lazy equality is used for sets and functions, which can themselves contain records.
Closes #1840.
> Fix function cherry picking relation propagation

- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/DumpCounterexamplesModelCheckerListener.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/DumpFilesModelCheckerListener.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/passes/BoundedCheckerPassImpl.scala
After #1838, fix some comments + appropriately rename `DumpFilesModelCheckerListener`
> Fix comments + rename `DumpFilesModelCheckerListener`

- mod-infra/src/main/scala/at/forsyte/apalache/infra/ExceptionAdapter.scala
- mod-infra/src/main/scala/at/forsyte/apalache/infra/Executor.scala
- mod-infra/src/main/scala/at/forsyte/apalache/infra/exceptions.scala
- mod-tool/src/main/scala/at/forsyte/apalache/tla/Tool.scala
- mod-tool/src/main/scala/at/forsyte/apalache/tla/tooling/opt/AbstractCheckerCmd.scala
- mod-tool/src/main/scala/at/forsyte/apalache/tla/tooling/opt/CheckCmd.scala
- mod-tool/src/main/scala/at/forsyte/apalache/tla/tooling/opt/ConfigCmd.scala
- mod-tool/src/main/scala/at/forsyte/apalache/tla/tooling/opt/General.scala
- mod-tool/src/main/scala/at/forsyte/apalache/tla/tooling/opt/ParseCmd.scala
- mod-tool/src/main/scala/at/forsyte/apalache/tla/tooling/opt/PassExecutorCmd.scala
- mod-tool/src/main/scala/at/forsyte/apalache/tla/tooling/opt/ServerCmd.scala
- mod-tool/src/main/scala/at/forsyte/apalache/tla/tooling/opt/SimulateCmd.scala
- mod-tool/src/main/scala/at/forsyte/apalache/tla/tooling/opt/TestCmd.scala
- mod-tool/src/main/scala/at/forsyte/apalache/tla/tooling/opt/TranspileCmd.scala
- mod-tool/src/main/scala/at/forsyte/apalache/tla/tooling/opt/TypeCheckCmd.scala
As preparation for #1114, we'll need to abstract the parsing logic, making it possible to parse from a supplied string, rather than reading from a file. However, the current state of the logic in the `Tool.scala` module makes it quite difficult to consider how the logic of the various subcommands can be effectively abstracted (at least, it has been difficult for me). This PR tries to follow the tactic [first make the change easy, then make the easy change](https://twitter.com/kentbeck/status/250733358307500032?lang=en).
The general tendency of this change makes the logic quite a bit clearer than before: It enables viewing (or discovering) all of the essential logic belonging to a subcommand by looking at the module that defines the subcommand; and it removes the convoluted knot of …
> Refactor CLI pipeline

- docs/src/apalache/features.md
- docs/src/apalache/running.md
- mod-tool/src/main/scala/at/forsyte/apalache/tla/tooling/opt/AbstractCheckerCmd.scala
- test/tla/NoTemporalOperatorsInTemporalProp.tla
- test/tla/cli-integration-tests.md
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/VCGenerator.scala
- tla-io/src/main/scala/at/forsyte/apalache/io/lir/CounterexampleWriter.scala
- tla-io/src/main/scala/at/forsyte/apalache/io/lir/ItfCounterexampleWriter.scala
- tla-io/src/main/scala/at/forsyte/apalache/io/lir/NameReplacementMap.scala
- tla-io/src/main/scala/at/forsyte/apalache/io/lir/PrettyWriter.scala
- tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/NormalizedNames.scala
- tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/passes/ConfigurationPassImpl.scala
- tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/passes/TemporalPassImpl.scala
- tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/temporal/TableauEncoder.scala
This PR is meant to clean up the git troubles encountered in #1830 and #1873. If we move forward with this PR, it should replace those two.
The "fix" attempted here was to squash merge all changes from branch `1815-with-unstable-merged-in` into a new branch off of unstable.
To try to confirm that his branch includes all the changes, I created a new branch off `unstable` and merged in `1815-with-unstable-merged-in` then did a git diff:
```diff
$  git diff 1815-with-unstable-merged-in..1815-try-to-fix-git
diff --git a/mod-tool/src/main/scala/at/forsyte/apalache/tla/tooling/opt/AbstractCheckerCmd.scala b/mod-tool/src/main/scala/at/forsyte/apalache/tla/tooling/opt/AbstractCheckerCmd.scala
index 570db1cef..4bb18e190 100644
--- a/mod-tool/src/main/scala/at/forsyte/apalache/tla/tooling/opt/Abstra …
```
> Add counterexample writer and --temporal flag

- .unreleased/bug-fixes/1871.md
- test/tla/TemporalPropsOverActions.tla
- test/tla/cli-integration-tests.md
- tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/Desugarer.scala
- tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/temporal/TableauEncoder.scala
- tla-pp/src/test/scala/at/forsyte/apalache/tla/pp/TestDesugarer.scala
- tla-pp/src/test/scala/at/forsyte/apalache/tla/pp/TestTableauEncoder.scala
Fixes buggy behaviour when actions are inside temporal operators by subtly changing the encoding.
It necessitates a change from the way the encoding is specified in the paper, which is necessary due to the technicalities of TLA+.
Essentially, double-priming is not allowed, while in LTL stacking next operators is no issue, so the subtle changes account for this.
> Add support for actions under temporal operators

- tla-bmcmt/src/test/scala/at/forsyte/apalache/tla/bmcmt/TestVCGenerator.scala
- tla-io/src/main/scala/at/forsyte/apalache/tla/imp/SanyImporter.scala
- tla-io/src/test/scala/at/forsyte/apalache/tla/imp/TestSanyImporter.scala
- tla-io/src/test/scala/at/forsyte/apalache/tla/imp/TestSanyImporterAnnotations.scala
- tla-io/src/test/scala/at/forsyte/apalache/tla/imp/TestSanyImporterInstances.scala
- tla-io/src/test/scala/at/forsyte/apalache/tla/imp/TestSanyImporterStandardModules.scala
- tla-pp/src/test/scala/at/forsyte/apalache/tla/pp/TestConstAndDefRewriter.scala
- tla-pp/src/test/scala/at/forsyte/apalache/tla/pp/TestTlcConfigImporter.scala
- tla-types/src/test/scala/at/forsyte/apalache/tla/typecheck/etc/TestTypeCheckerTool.scala
Supports #1114
Currently, the `SanyImporter.loadFromSource` method takes both a module name and
a `scala.io.Source`, before delegating to Sany to parse a `TlaModule` from the
given source.
Shai will want to use the `SanyImporter.loadFromSource` to load the blob
representing the module it receives via gRPC, but requiring users to submit the
module name separately seems clunky and like needless leakage of an
implementation detail into the API.
This small change lets us infer the module name from the content of the source
(rather than from files) without requiring the caller to supply the module name
explicitly. Since this method was only used in tests up to this point, this
change is very low impact.
I recommend reviewing by commit:
- 2cfc8cd819c743016ae8bfb691e6a2f9447efbfe includes the …
> Infer module name in SanyImporter.loadFromSource

- .unreleased/features/1870.md
- .unreleased/features/1898.md
- .unreleased/features/remove-posttype.md
This is a followup to several PRs that added redundant bullet points to
the change long entries. This change removes the redundant bullet points.
This is a precondition for preparing this week's release.
See https://github.com/informalsystems/apalache/pull/1904#discussion_r912921195 for the erroneous formatting.
> Fix formatting of changelog entries

- tla-types/src/main/scala/at/forsyte/apalache/tla/typecomp/subbuilder/LiteralAndNameBuilder.scala
- tla-types/src/main/scala/at/forsyte/apalache/tla/typecomp/unsafe/UnsafeLiteralAndNameBuilder.scala
- tla-types/src/test/scala/at/forsyte/apalache/tla/typecomp/TestLiteralAndNameBuilder.scala
> Typed Builder implementation Part 8.1: Uninterpreted constants

- mod-infra/src/main/scala/at/forsyte/apalache/infra/passes/PassOptions.scala
- mod-infra/src/main/scala/at/forsyte/apalache/infra/passes/SourceOption.scala
- mod-infra/src/main/scala/at/forsyte/apalache/infra/passes/WriteablePassOptions.scala
- mod-tool/src/main/scala/at/forsyte/apalache/tla/tooling/opt/AbstractCheckerCmd.scala
- mod-tool/src/main/scala/at/forsyte/apalache/tla/tooling/opt/ParseCmd.scala
- mod-tool/src/main/scala/at/forsyte/apalache/tla/tooling/opt/TestCmd.scala
- mod-tool/src/main/scala/at/forsyte/apalache/tla/tooling/opt/TypeCheckCmd.scala
- tla-io/src/main/scala/at/forsyte/apalache/tla/imp/passes/SanyParserPassImpl.scala
- tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/passes/ConfigurationPassImpl.scala
The key change here is to replace the "filename" option, storing a
string, with an instance of the newly added `SourceOption` class, that
lets us statically encode a data source which is (currently] either a
file or a string.
The immediate use for this will be supporting Shai to load modules from
a string (while maximizing code reuse), but this could also be used
to read in specs (or other data) from stdin or a socket etc.
This change, again, aims to be minimally invasive while extending functionality
in generally (and specifically) useful ways. As such, no tests are included
here, since no new functionality is yet exposed (i.e., the PR doesn't expose the
ability to load specs from stdin).
Tests to exercise the relevant portion in the `SanyParserPassImpl` will be
forthcoming in #1855. …
> Add a `SourceOption` type for loading specs from non-file sources

- .unreleased/documentation/1930.md
- docs/src/SUMMARY.md
- docs/src/lang/apalache-extensions.md
- docs/src/lang/variants.md
Closes #1923. Add the manual page on variants.
> Add manual page on variants

- mod-infra/src/main/scala/at/forsyte/apalache/infra/passes/SourceOption.scala
- tla-io/src/main/scala/at/forsyte/apalache/tla/imp/SanyImporter.scala
- tla-io/src/main/scala/at/forsyte/apalache/tla/imp/passes/SanyParserPassImpl.scala
- tla-io/src/test/scala/at/forsyte/apalache/tla/imp/TestSanyImporter.scala
- tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/passes/ConfigurationPassImpl.scala
Supports #1114
The server API is able must support load a model by receiving a string
representing the root module and a sequence of strings representing any
auxiliary modules needed due to imports or refinement. This changeset extends
our SanyParser wrapper to support loading auxiliary modules supplied as a
sequence of `scala.io.Source`s.
-------
> Support loading auxiliary modules from Source

- .github/ISSUE_TEMPLATE/bug_report.md
Adds a checklist to help guide our triage of bugs. Also adds a note to users,
nudging them to try running apalache on the latest version.
> Update bug issue template with triage checklist

- .unreleased/documentation/1942.md
- docs/src/tutorials/snowcat-tutorial.md
- test/tla/LamportMutexTyped.tla
Closes #1939. This PR update the tutorial on the type checker, using the new records and giving pointers to variants. I have made it shorter and, hopefully, simpler.
> Update the types tutorial

- .unreleased/bug-fixes/1959-sany-tmpdir.md
- tla-io/src/main/scala/at/forsyte/apalache/tla/imp/SanyImporter.scala
This should provide a workaround for the concurrency bug noted
https://github.com/tlaplus/tlaplus/issues/688, while we wait on an upstream fix.
Note that this only allows concurrent executions of SANY in parallel processes.
AFAICT, the deeper issue noted at
https://github.com/informalsystems/apalache/issues/1114#issuecomment-1180534894
will still prevent concurrent runs of SANY within the same JVM.
-------
> Set a unique java.io.tmpdir for each call to SANY

- tla-types/src/test/scala/at/forsyte/apalache/tla/typecomp/BuilderTest.scala
- tla-types/src/test/scala/at/forsyte/apalache/tla/typecomp/TestApalacheInternalBuilder.scala
- tla-types/src/test/scala/at/forsyte/apalache/tla/typecomp/TestFunBuilder.scala
- tla-types/src/test/scala/at/forsyte/apalache/tla/typecomp/TestSetBuilder.scala
closes #1969
Makes type parameters of `BuilderTest` methods more generic, but otherwise introduces no new code.
> Typed Builder implementation Part 11.6: Generalize the BuilderTest framework

- shai/README.md
- shai/src/main/scala/at/forsyte/apalache/shai/RpcServer.scala
- shai/src/main/scala/at/forsyte/apalache/shai/TransExplorerService.scala
- shai/src/test/resources/logback-test.xml
Closes #1849 
Shai needs to log critical activities so we can monitor and debug the server.
This PR gives the `TransExplorerService` access to the existing logging
infrastructure we use throughout Apalache by providing a very thin ZIO wrapper
around an injected `Logger` instance.
- Create a private object that wraps calls to a provided `Logger` inside ZIO effects
- Add some simple formatting to the logged message
- Add basic logging for the existing RPC handlers
Should be straight forward and the changeset is small. I'd particular be
interested in learning if I should be managing the logging message formatting
differently or if there's a better way for me to be making the logger available
to the server.
> Shai: Add logging

- tla-types/src/main/scala/at/forsyte/apalache/tla/typecomp/ScopedBuilder.scala
- tla-types/src/main/scala/at/forsyte/apalache/tla/typecomp/package.scala
closes #1912
Note: I noticed the `ScopedBuilder.parser` was a `def` instead of a `val` so I just fixed it.
> Documentation for `typecomp`

- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/FunAppRuleWithArrays.scala
This PR removes the possibility of applying SMT select to a value outside a function's domain when encoding function application.
> Fix unguarded constraining

- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/search/ModelCheckerParams.scala
Remove `ModelCheckerParams.stepMatchesFilter` as dead code (looks like the functionality moved to `FilteredTransitionExecutor`).
> Remove dead code

- .unreleased/documentation/2009.md
- docs/src/HOWTOs/howto-write-type-annotations.md
- docs/src/adr/002adr-types.md
- docs/src/tutorials/snowcat-tutorial.md
- test/tla/LamportMutexTyped.tla
- test/tla/MissionariesAndCannibalsTyped.tla
Closes #1978. In this PR, we update the type alias syntax in:
[unreleased]: https://github.com/informalsystems/apalache/tree/main/.unreleased
> update the alias syntax in the docs

- .github/workflows/main.yml
- tla-types/src/main/scala/at/forsyte/apalache/tla/typecomp/ScopedBuilder.scala
- tla-types/src/main/scala/at/forsyte/apalache/tla/typecomp/package.scala
Followup to recent documentation work that had broken scaladoc links which we
didn't catch because CI wasn't failing on the scaladoc warnings.
There are a couple cases where I couldn't fix the references due to one of two
things:
- The links were to private methods
- The links were to overloaded method and the reference was therefore ambiguous.
I spent about 20 mins trying to figure out how to make the links unambiguous,
but couldn't find a solution that worked.
> Fix documentation links

- mod-infra/src/main/scala/at/forsyte/apalache/infra/passes/options.scala
Contributes towards #1174
This adds traits with values to represent all the options that we are
currently setting in the `at.forsyte.apalache.tla.tooling.opt.Cmd*`
classes. None of those options are actually transferred over here.
The proposed design uses traits to specify all the options, with the idea that
various subprograms can depend on mixins of the traits to statically declare the
configurations they respond to.
This changeset just prepares the representation of the options, with the aim of
obtaining feedback and clearing the way for the changeogver. The followup PR
will remove the `PassOptions` class, replacing it with objects that implement
the configuration traits needed by the respective subcommands.
> Add static representation of configuration options

- docs/src/apalache/tuning.md
Format and clarify tuning manual page.
**Reviewing**: The first and last commit are purely mechanical and don't change the prose. The remaining changes are relatively small and should be self-explanatory.
This is in preparation of #2031, where I need to explain the extended invariant filter.
> Format and fix tuning docs

- .github/pull_request_template.md
I keep forgetting the new changelog format, so this adds a link to the formatting guidelines in [CONTRIBUTING.md](https://github.com/informalsystems/apalache/tree/main/CONTRIBUTING.md#how-to-record-a-change) to our PR template.
The link replaces the previous link to [`./unreleased/`](https://github.com/informalsystems/apalache/tree/main/.unreleased) – the directory is empty after cutting a release and not much help (unless I'm overlooking a use case).
> Link to changelog format in PR template

- .unreleased/breaking-changes/extd-inv-filter.md
- docs/src/apalache/tuning.md
- mod-tool/src/main/scala/at/forsyte/apalache/tla/tooling/opt/TestCmd.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/InvariantKind.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/SeqModelChecker.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/trex/ConstrainedTransitionExecutor.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/trex/FilteredTransitionExecutor.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/trex/TransitionExecutor.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/trex/TransitionExecutorImpl.scala
- tla-bmcmt/src/test/scala/at/forsyte/apalache/tla/bmcmt/trex/TestFilteredTransitionExecutor.scala
- tla-bmcmt/src/test/scala/at/forsyte/apalache/tla/bmcmt/trex/TestTransitionExecutorImpl.scala
Closes #2031. Towards https://github.com/informalsystems/apalache-cloud/issues/106.
We currently expose an [invariant filter](https://apalache.informal.systems/docs/apalache/tuning.html#invariant-filter) via tuning flags. It accepts a regular expression recognizing words over step numbers. Apalache then only checks state and action invariants in the step numbers accepted by the filter.
We extend the invariant filter syntax to also specify which invariants to check in a step.
We achieve this by extending the regular expression to accepting words (really, triples) of the shape `${stepNo}->${invariantKind}${invariantNo}`. This is similar to the existing [transition filter](https://apalache.informal.systems/docs/apalache/tuning.html#transition-filter) syntax that accepts words …
> Extend the invariant filter to specify particular invariants

- .github/ISSUE_TEMPLATE/bug_report.md
- mod-tool/src/main/scala/at/forsyte/apalache/tla/Tool.scala
- tla-io/src/main/scala/at/forsyte/apalache/io/ReportGenerator.scala
- Collapse the log output in our bug report template by [wrapping it in `<details>`](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections).
- Sync the template with the Github issue template in `.github/ISSUE_TEMPLATE/bug_report.md`.
- Fix some typos.
> Improve the bug report template

- src/universal/bin/apalache-mc
Instead of explicitly setting JVM max heap memory with `-Xmx`, it can be set via `-XX:MaxRAMPercentage`. The latter [is useful](https://docs.cloudbees.com/docs/cloudbees-ci-kb/latest/best-practices/jvm-memory-settings-best-practice) [for containers](https://dzone.com/articles/best-practices-java-memory-arguments-for-container), where the JVM is the only process running and should occupy a sizeable portion of total container memory.
This avoids setting `-Xmx4096m` in `apalache-mc` if `-XX:MaxRAMPercentage` is present in `JVM_ARGS`, as the absolute setting would override the relative `-XX:MaxRAMPercentage`.
> Avoid setting `-Xmx` if `-XX:MaxRAMPercentage` is supplied

- .unreleased/breaking-changes/2047-001-rename-save-runs.md
- .unreleased/breaking-changes/2047-002-check-output-traces.md
- .unreleased/breaking-changes/save-runs.md
- docs/src/apalache/running.md
- mod-tool/src/main/scala/at/forsyte/apalache/tla/tooling/opt/CheckCmd.scala
- mod-tool/src/main/scala/at/forsyte/apalache/tla/tooling/opt/SimulateCmd.scala
- test/tla/cli-integration-tests.md
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/DumpFilesModelCheckerListener.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/SeqModelChecker.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/search/ModelCheckerParams.scala
We introduced example trace output in #1838. As described in #2039 and #2019, this creates a unexpected performance bottleneck if the SMT call for constructing the trace takes a long time.
Oddly enough, writing the trace was made optional for `simulate` via the `--save-runs` flag   (defaulting to `false`) in #1838, but always enabled for `check`.
With this PR, we lift `--save-runs` to `check`, making example trace output optional also for `check`.
We also make some UX improvements that
* fix the case where the last symbolic run of `simulate` was output twice,
* add log output around the example trace output, and
* adjust example output log levels from `ERROR` to `INFO`.
Fixes …
> Make example trace output optional via `--save-runs`

- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/SetFilterRule.scala
This PR removes a redundant membership check in the set filter rule, as suggested by @konnov a while back.
> Update of set filter rule with SMT arrays 

- docs/src/tutorials/entry-tutorial.md
- docs/src/tutorials/pluscal-tutorial.md
Closes #1996 
For tutorials spanning multiple source files, provide a download link to a ZIP archive containing all the source files.
The ZIP is generated on-demand from checked-in sources via [download-directory/download-directory.github.io](https://github.com/download-directory/download-directory.github.io).
> Add tutorial source downloads as ZIP archives

- docs/src/tutorials/temporal-properties.md
Add syntax-highlighting for TLA+ in the temporal properties tutorial.
> Highlight TLA+ in temporal properties tutorial

- .unreleased/breaking-changes/2064-detailed-log-iso8601.md
- mod-infra/src/main/scala/at/forsyte/apalache/infra/log/LogbackConfigurator.scala
We currently only print time in `detailed.log`. This makes it impossible to profile runtime on specs where the computation referred to by a single log line may take >24h.
This PR changes the `detailed.log` format to print a full ISO 8601 timestamp, e.g.
```
2022-08-10T17:29:11,635 [main] INFO  a.f.a.t.b.SeqModelChecker - State 10: Checking 1 state invariants
```
Closes #2063
> Print full ISO 8601 timestamp in detailed.log

- COORDINATION.md
- docs/src/SUMMARY.md
- docs/src/adr/002adr-types.md
- docs/src/adr/005adr-json.md
- docs/src/adr/007adr-restructuring.md
- docs/src/adr/008adr-exceptions.md
- docs/src/adr/009adr-outputs.md
- docs/src/adr/012adr-adopt-adr-template.md
- docs/src/adr/013adr-configuration.md
- docs/src/adr/014adr-precise-records.md
- docs/src/adr/015adr-trace.md
- docs/src/adr/016adr-retla.md
- docs/src/adr/017pdr-temporal.md
- docs/src/adr/018adr-inlining.md
- docs/src/adr/019adr-harmonize-changelog.md
- docs/src/adr/020adr-arenas.md
- docs/src/adr/021rfc-prioritization.md
- docs/src/adr/022adr-unification-of-configs-and-options.md
- docs/src/adr/NNNadr-template.md
We are missing several ADRs from the website's menu, so I'm linking all of them there. In this process, I fixed some small numbering problems.
I also found a problem in how the ADR template's way of defining authors and revision dates is rendered. It currently looks like this:
So I've updated the template and existing entries to use a markdown table which renders like this:
> Organize website decision records

- mod-infra/src/main/scala/at/forsyte/apalache/infra/passes/options.scala
Works towards #2040
This PR factors out just the addition of the `OptionGroup` classes and related
traits into its own PR. There is ongoing work to in #2074 to integrate the
options provider defined here into the rest of the code base, but this hunk can
be factored out for a more digestable PR review.
You can see how these the `OptionGroups` are being used by taking a peak at #2074.
- Add case classes to represent required sets of options, "option groups", with
the groupings and namings closely following the existing `PassOption` options
map. (If we want, we can refactor to adjust the names and hierarchy much
easier once this in place.)
- Add traits that specify combinations of options and classes to construct those
combinations.
> Add specification of the OptionGroup classes and traits

- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/analyses/ExpansionMarker.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/SetExpandRule.scala
This is a small change in the warning about expanding power sets and function sets. The previous warning is annoying, especially when `SUBSET S` is applied to `S` of cardinality of 1 or 2.
> improve the warning about large sets

- mod-tool/src/main/scala/at/forsyte/apalache/tla/tooling/opt/CheckCmd.scala
- test/tla/cli-integration-tests.md
As part of the options rework, we turned all the clist `opt`s into `Option`s (#2065).
As a result, `CheckCmd` didn't access the default value of 10 when printing computation length.
This applies a fix by getting `"checker.length"` from pass options instead.
Also adds 2 integration tests, one with default length and one with explicit `--length`.
Fixes #2087
> Fix computation length output

- mod-infra/src/main/scala/at/forsyte/apalache/infra/Executor.scala
The `ExceptionAdapter` currently throws away the stack trace of
exceptions it intercepts, and only the message is preserved. As a
result, bug reports and logs are less useful than they could be.
This small change just adds a debug level of the full exception before
passing it on to the `AdaptedException` structure for reporting by the
tool. The new traceback output is included in the debug output we
generate for filing bug reports, but are not shown in the user's console
under normal operation.
> Add debug logging of adapted exceptions

- docs/src/HOWTOs/howto-write-type-annotations.md
- docs/src/adr/002adr-types.md
- docs/src/tutorials/snowcat-tutorial.md
Closes #2093.
This PR contains updates regarding the transition to Type Systems 1.2:
The manual contains two other documents that are using the old syntax for record types. They are postponed for #2099 and #2100.
> Update ADR002, tutorial, and howto

- build.sbt
- src/tla/README.md
Towards #2097
This replaces the hard-coded copying of our custom TLA modules into the
tla2sany directory with a general solution for any `.tla` files in our
`src/tla` directory.
> Deduplicate assembly of custom TLA modules

- docs/src/apalache/running.md
Followup to #2074
This just updates the manual docs to inform users that they can supply a
comm separated list of arguments to the `--init` and `--temporal` flags.
If I'd realized how few additions this needed, I would have just
rolled it into #2074.
-------
> Update manual for multi-argument init and temporal

- .scalafmt.conf
- build.sbt
- mod-infra/src/main/scala/at/forsyte/apalache/infra/tlc/config/TlcConfig.scala
- mod-tool/src/main/scala/at/forsyte/apalache/tla/tooling/opt/AbstractCheckerCmd.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/Arena.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/SymbStateRewriterImpl.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/passes/ReTLAToVMTTranspilePassImpl.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/profiler/RuleStatLocator.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/aux/CherryPick.scala
- tla-bmcmt/src/test/scala/at/forsyte/apalache/tla/bmcmt/CrossTestEncodings.scala
- tla-bmcmt/src/test/scala/at/forsyte/apalache/tla/bmcmt/TestSeqModelCheckerTrait.scala
- tla-bmcmt/src/test/scala/at/forsyte/apalache/tla/bmcmt/TestSymbStateRewriterAssignment.scala
- tla-bmcmt/src/test/scala/at/forsyte/apalache/tla/bmcmt/TestSymbStateRewriterFun.scala
- tla-bmcmt/src/test/scala/at/forsyte/apalache/tla/bmcmt/analyses/TestExpansionMarker.scala
- tla-io/src/main/scala/at/forsyte/apalache/tla/imp/AnnotationExtractor.scala
- tla-io/src/test/scala/at/forsyte/apalache/io/lir/TestPrettyWriter.scala
- tla-io/src/test/scala/at/forsyte/apalache/tla/imp/TestSanyImporterStandardModules.scala
- tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/Keramelizer.scala
- tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/NormalizedNames.scala
- tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/passes/ConfigurationPassImpl.scala
- tla-pp/src/test/scala/at/forsyte/apalache/tla/pp/TestDesugarer.scala
- tla-pp/src/test/scala/at/forsyte/apalache/tla/pp/TestKeramelizer.scala
- tla-pp/src/test/scala/at/forsyte/apalache/tla/pp/TestSourceLocator.scala
- tla-pp/src/test/scala/at/forsyte/apalache/tla/pp/TestTypeSubstitutor.scala
- tla-types/src/test/scala/at/forsyte/apalache/tla/typecheck/etc/TestToEtcExpr.scala
- tlair/src/main/scala/at/forsyte/apalache/tla/lir/TlaType1.scala
- tlair/src/test/scala/at/forsyte/apalache/tla/lir/IrGenerators.scala
- tlair/src/test/scala/at/forsyte/apalache/tla/lir/TestModule.scala
- tlair/src/test/scala/at/forsyte/apalache/tla/lir/TlaType1Gen.scala
Some times we need to construct a case class or apply a method with very
many arguments. In this cases, it is generally easier to read the
applications and grock the inputs if we use "config-style", which puts
each parameter on its own line.
This will help with readability of the configuration construction from the CLI
parsing in #2065
-------
> Enforce config-style formatting for > 5 args

- .unreleased/breaking-changes/2125-err-on-invalid-config-keys.md
- test/tla/cli-integration-tests.md
- tla-io/src/main/scala/at/forsyte/apalache/io/ConfigManager.scala
Previously, unexpected keys in a configuration source were silently
ignored. This led to invalid configuration values (e.g., due to
configuration format updates or due to typos) being silently ignored.
This addition ensures we raise an error on unexpected keys in
configuration sources.
This was spun out of ongoing work on #2121.
-------
> Raise an error on invalid keys in configuration

- build.sbt
- mod-infra/src/main/scala/at/forsyte/apalache/infra/passes/options.scala
- mod-tool/src/main/scala/at/forsyte/apalache/tla/Tool.scala
- mod-tool/src/main/scala/at/forsyte/apalache/tla/tooling/opt/AbstractCheckerCmd.scala
- mod-tool/src/main/scala/at/forsyte/apalache/tla/tooling/opt/CheckCmd.scala
- mod-tool/src/main/scala/at/forsyte/apalache/tla/tooling/opt/ParseCmd.scala
- mod-tool/src/main/scala/at/forsyte/apalache/tla/tooling/opt/TestCmd.scala
- mod-tool/src/main/scala/at/forsyte/apalache/tla/tooling/opt/TypeCheckCmd.scala
- tla-io/src/main/scala/at/forsyte/apalache/io/OutputManager.scala
- tla-io/src/main/scala/at/forsyte/apalache/tla/imp/passes/SanyParserPassImpl.scala
Closes #2128
To implement #2013 and friends, we'll need to be able to parse model checking configuration inputs from JSON data. The preceding work on #1174 etc. made it possible to obtain every configuration input required, with the notable exception of spec represented as a string! Currently, the configuration only supports input data via a file name. This won't work for the RPC server, since the client may not have access to the same file system as the server. This PR moves us towards the needed functionality by expanding the `ApalacheConfig` so that it takes a `SourceOption`. Follow up work planned in #2121 will add a converter to enable pure config to de-serialize the desired data.
> Make ApalacheConfig take a `SourceOption` for input  instead of a file

- .unreleased/features/2134-cfg-dump-on-debug.md
- mod-infra/src/main/scala/at/forsyte/apalache/infra/passes/options.scala
- mod-tool/src/main/scala/at/forsyte/apalache/tla/Tool.scala
- mod-tool/src/main/scala/at/forsyte/apalache/tla/tooling/opt/ApalacheCommand.scala
- test/tla/cli-integration-tests.md
- tla-io/src/main/scala/at/forsyte/apalache/io/ConfigManager.scala
Closes #2129
When receiving data from RPC calls, we plan to use our configuration loading
system to read out the application configuration from a JSON payload. This will
need to include the source of the specification, which we represent as a value
of type `SourceOption`. The changes introduced here improve the serialization of
values of this type.
This PR also adds an option `--dump-config=<FILE>` that will write the derived
config of a command into the specified file. This has proved useful for testing,
I think could be useful for other purposes. However, I'm holding off on writing
documentation for it, in case reviewers think the CLI flag shouldn't introduced.
> Add de/serialization of `SourceOption` values

- shai/src/main/scala/at/forsyte/apalache/shai/v1/CmdExecutorService.scala
- shai/src/main/scala/at/forsyte/apalache/shai/v1/RpcServer.scala
- shai/src/main/scala/at/forsyte/apalache/shai/v1/TransExplorerService.scala
With #2156 in place, we don't need to put a semaphore around invocations
of our pass executions any more, since the synchronization is assured via
the much more focused scope of invocations of SANY.
> Shai: Remove semaphore

- .unreleased/bug-fixes/2169.md
- test/tla/CommentedTypeAnnotation.tla
- test/tla/cli-integration-tests.md
- tla-io/src/main/scala/at/forsyte/apalache/io/annotations/AnnotationParser.scala
- tla-io/src/main/scala/at/forsyte/apalache/io/annotations/parser/AnnotationLexer.scala
- tla-io/src/main/scala/at/forsyte/apalache/io/annotations/parser/CommentPreprocessor.scala
- tla-io/src/main/scala/at/forsyte/apalache/io/annotations/parser/tokens.scala
- tla-io/src/main/scala/at/forsyte/apalache/tla/imp/AnnotationExtractor.scala
- tla-io/src/test/scala/at/forsyte/apalache/io/annotations/TestAnnotationParser.scala
- tla-io/src/test/scala/at/forsyte/apalache/io/annotations/TestCommentPreprocessor.scala
- tla-io/src/test/scala/at/forsyte/apalache/io/annotations/parser/TestAnnotationLexer.scala
- tla-io/src/test/scala/at/forsyte/apalache/tla/imp/TestSanyImporterAnnotations.scala
Fixes #2162
We heard you like comments in your type annotations inside of comments, so we added support for single-line comments, beginning with `//`, that can be used inside of type annotations inside of multi- and single-line TLA+ comments, so you can comment your annotations while annotating inside your comments.
This required tweaking the lexer and preprocessor so that we preserve new lines (and avoid inserting duplicate new lines, added by SANY), and then updating a bunch of finicky tests to accommodate quirks to intermediate strings.
> Fix support for one-line comments in type annotations

- shai/src/main/scala/at/forsyte/apalache/shai/v1/CmdExecutorService.scala
Followup to #2138, suggested by @thpani in a comment
https://github.com/informalsystems/apalache/pull/2138#discussion_r975077165
-------
> Use IllegalArgumentException for Unrecognized command in CmdExecutorService

- project/plugins.sbt
Without this configuration, devs may hit an error like
```
[error] java.lang.RuntimeException: found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[error]
[error] 	* org.scala-lang.modules:scala-xml_2.12:2.1.0 (early-semver) is selected over {1.3.0, 1.0.6, 1.2.0}
[error] 	    +- org.scoverage:scalac-scoverage-reporter_2.12:2.0.2 (depends on 2.1.0)
[error] 	    +- com.github.sbt:sbt-native-packager:1.9.11 (sbtVersion=1.0, scalaVersion=2.12) (depends on 2.1.0)
[error] 	    +- org.scala-sbt:testing_2.12:1.6.2                   (depends on 1.3.0)
[error] 	    +- org.scala-sbt:sbinary_2.12:0.5.1                   (depends on 1.0.6)
[error] 	    +- org.scala-sbt:main_2.12:1.6.2                      (depends on 1.3.0)
[error] 	    +- …
```
> Resolve possible XML dependency conflict

- tla-io/src/main/scala/at/forsyte/apalache/io/json/JsonDeserializationError.scala
- tla-types/src/main/scala/at/forsyte/apalache/tla/typecomp/ScopedBuilder.scala
- tla-types/src/main/scala/at/forsyte/apalache/tla/typecomp/json/BuilderCallByName.scala
- tla-types/src/main/scala/at/forsyte/apalache/tla/typecomp/json/JsonToTlaViaBuilder.scala
- tla-types/src/main/scala/at/forsyte/apalache/tla/typecomp/json/UJsonToTlaViaBuilder.scala
- tla-types/src/test/scala/at/forsyte/apalache/tla/typecomp/TestUJsonToTlaViaBuilder.scala
Due to the `tla-io` package being a dependency for `tla-types`, these classes must temporarily be placed in `tla-types` (or higher). Once package refactoring is addressed, these classes should replace the ones in `io.json`, which currently use the old builder.
Additionally, the deserialization tests _should_ use generators, but we currently lack ways to generate type-correct TLAIR, which would mean that deserializing serialized auto-generated expressions would throw, more often than not.
closes #2201
> `ScopedBuilder`-based JSON reader

- .github/workflows/deploy.yml
We've started encountering the [brownout of `ubuntu-18.04`](https://github.com/actions/runner-images/issues/6002) in our `deploy` Github workflow:
https://github.com/informalsystems/apalache/actions/runs/3249911017
Bump to `ubuntu-latest`.
All other workflows already use `-latest`.
> Bump ubuntu version in `deploy` workflow

- shai/src/main/protobuf/transExplorer.proto
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/Checker.scala
Two tiny fixes here:
- Use lower-case consistently for gRPC service methods (this doesn't make a difference
for Scala code generation but does for Python)
- Use the same field name and representation for returning counterexamples
coming from deadlock and violation errors 
> Small cleanup on Shai RPCs

- mod-infra/src/main/scala/at/forsyte/apalache/infra/passes/options.scala
- mod-infra/src/test/scala/at/forsyte/apalache/infra/passes/TestOptions.scala
- passes/src/main/scala/at/forsyte/apalache/tla/passes/imp/SanyParserPassImpl.scala
- test/tla/cli-integration-tests.md
Closes #2222
After noodling around to confirm that detecting ".itf.json" would be reasy
enough, it seemed to make sense to offer the solution as a PR.
-------
> Extend SourceOption.FileSource for itf.json

- .unreleased/breaking-changes/2199-parse-error-output.md
- passes/src/main/scala/at/forsyte/apalache/tla/passes/imp/SanyParserPassImpl.scala
- passes/src/main/scala/at/forsyte/apalache/tla/passes/typecheck/EtcTypeCheckerAdapter.scala
- shai/src/main/protobuf/cmdExecutor.proto
- shai/src/main/protobuf/transExplorer.proto
- shai/src/main/scala/at/forsyte/apalache/shai/v1/CmdExecutorService.scala
- shai/src/main/scala/at/forsyte/apalache/shai/v1/TransExplorerService.scala
- shai/src/test/scala/at/forsyte/apalache/shai/v1/TestCmdExecutorService.scala
- shai/src/test/scala/at/forsyte/apalache/shai/v1/TestTransExplorerService.scala
- test/tla/cli-integration-tests.md
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/config/CheckerExceptionAdapter.scala
- tla-io/src/main/scala/at/forsyte/apalache/tla/imp/ParserExceptionAdapter.scala
Closes #2199, #2204
(See #2234 for additional notes on context and the motivation for this approach).
- Catches `SanyException`s from the highest level of the SANY parser
pass and makes these available in the `PassResult`.
- Promotes the general RPC error data into protbuf specs, allowing more
consistentcy and reducing the amount of dynamic JSON.
- Includes some light refactoring as incidental cleanup.
- Updates tests.
-------
> Shai: Return parsing pass error data in RPCs

- src/tla/Variants.tla
I was just running TLC for a spec with variants and `VariantFilter` definition is broken, so this fixes it.
I don't think we are testing this untyped version, so I didn't change any tests. Let me know if I should.
> Fix untyped implementation for VariantFilter

- project/Dependencies.scala
Replaces #2219
This just adds a trivial tweak to the dependencies to enable the update to go thru.
> Update/scalatest 3.2.14

- test/tla/MegaSpec1.tla
- test/tla/cli-integration-tests.md
Closes #2253
This just adds a simple round-trip test of our ability to parse a spec into type-preserving JSON representation of the IR and then check the the spec using that generated JSON as input.
> Test roundtrip JSON serialization and deserialization

- .unreleased/features/server-configure-port.md
- mod-infra/src/main/scala/at/forsyte/apalache/infra/passes/options.scala
- mod-tool/src/main/scala/at/forsyte/apalache/tla/tooling/opt/ServerCmd.scala
- shai/src/main/scala/at/forsyte/apalache/shai/v1/RpcServer.scala
- shai/src/test/scala/at/forsyte/apalache/shai/v1/TestCmdExecutorService.scala
- shai/src/test/scala/at/forsyte/apalache/shai/v1/TestTransExplorerService.scala
- test/tla/cli-integration-tests.md
- Adds `server` section to our configuration enabling configuration of
server settings via config file.
- Adds a corresponding `Server` `OptionGroup` to validate config values.
- Adds a `port` CLI argument, to allow supplying the port at time of
command invocation.
- Adds an `RpcServer` class so that the port can be configured when
the class is instantiated.
-------
> Make the server port configurable

- mod-infra/src/main/scala/at/forsyte/apalache/infra/passes/options.scala
- mod-infra/src/test/scala/at/forsyte/apalache/infra/passes/TestOptions.scala
- mod-tool/src/main/scala/at/forsyte/apalache/tla/tooling/opt/AbstractCheckerCmd.scala
- mod-tool/src/main/scala/at/forsyte/apalache/tla/tooling/opt/ApalacheCommand.scala
- mod-tool/src/main/scala/at/forsyte/apalache/tla/tooling/opt/CheckCmd.scala
- mod-tool/src/main/scala/at/forsyte/apalache/tla/tooling/opt/ParseCmd.scala
- mod-tool/src/main/scala/at/forsyte/apalache/tla/tooling/opt/ServerCmd.scala
- mod-tool/src/main/scala/at/forsyte/apalache/tla/tooling/opt/SimulateCmd.scala
- mod-tool/src/main/scala/at/forsyte/apalache/tla/tooling/opt/TestCmd.scala
- mod-tool/src/main/scala/at/forsyte/apalache/tla/tooling/opt/TraceeCmd.scala
- mod-tool/src/main/scala/at/forsyte/apalache/tla/tooling/opt/TranspileCmd.scala
- mod-tool/src/main/scala/at/forsyte/apalache/tla/tooling/opt/TypeCheckCmd.scala
- test/tla/cli-integration-tests.md
Closes #2175
This fixes the processing of CLI configuration params to avoid unhandled
exceptions. The solution is to be honest about the possible failure of
the the `toConfig` method, which maps CLI param inputs to an
instance of `Options.ApalacheConfig`: Since this conversion can fail, 
we let it return a `Try` and this fix ensures that error is handled 
correctly.
Along the way, it removes the atavistic `collectTuningOptions` method,
which shouldn't be needed with the new config management scheme. This
also enables a slight cleanup on the Tracee command.
> Fix unhandled exception on invalid file formats

- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/tracee/UJsonTraceReader.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/tracee/tracee.scala
- tla-io/src/main/scala/at/forsyte/apalache/io/itf/ItfToTla.scala
- tla-io/src/main/scala/at/forsyte/apalache/io/itf/package.scala
- tla-io/src/main/scala/at/forsyte/apalache/io/json/JsonRepresentation.scala
- tla-io/src/main/scala/at/forsyte/apalache/io/json/impl/UJsonRep.scala
- tla-io/src/main/scala/at/forsyte/apalache/io/lir/package.scala
- tla-io/src/test/scala/at/forsyte/apalache/io/itf/TestItfToTla.scala
closes #2272
Alternative to #2273, uses `Either`.
> ITF trace reader - `Either`-based alternative

- docs/src/apalache/parameters.md
The module actually goes until line 15: https://github.com/informalsystems/apalache/blob/0795560e3382fc22b5b5ecabc02346bd5b2849d8/test/tla/y2k_instance.tla#L1-L15
Btw, at a quick glance it doesn't appear that the contributing guidelines mention anything about PRs for docs.
> Fix snippet in `docs/apalache/parameters.md`

- .github/workflows/main.yml
Our nix installation in the CI was failing, presumably due to updates in the underlying runners that conflicted with the quite outdated version of the github action we were using to install nix. This PR just updates the nix action, which also allows us drop some of the configuration, since flakes is now supported without requiring a special URL.
Closes #2318 
:warning: Auto merge enabled
> Fix failing nix setup in integration tests

- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/FunCtorRuleWithArrays.scala
- tlair/src/main/scala/at/forsyte/apalache/tla/lir/oper/ApalacheInternalOper.scala
closes #2329 
The bug shows up in tests when the `ScopedBuilder` is used. Since those tests will come as part of a separate refactoring PR, they are omitted here.
> Fix array rule

- tla-io/src/main/scala/at/forsyte/apalache/io/quint/QuintIR.scala
- tla-io/src/test/scala/at/forsyte/apalache/io/quint/TestQuintEx.scala
followup to #2351
adds simple unit tests, following @gabrielamafra's suggestion to illustrate and validate basic logic
> Add simple unit tests for quint exp conversion

- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/arena/ElemPtr.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/SetFilterRule.scala
closes #2381
Membership guarantees via fixed-pointers do not survive filter. Therefore, the post-filter set must only contain `SmtExprElemPtr`s.
> SetFilterRule

- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/TupleOrSeqCtorRule.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/aux/CherryPick.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/aux/DefaultValueFactory.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/aux/ProtoSeqOps.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/aux/RecordAndVariantOps.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/aux/ValueGenerator.scala
Miscellaneous instances of `SmtConstElemPtr` replaced with the other kinds. For the most part, any value produced by `gen-` methods should just use fixed pointers, no point in having overapproximation in generated values.
After both this and #2416 get merged we can remove that pointer sort entirely.
>  ElemPtr rework, pahse 3: Removing SmtConstElemPtrs in `gen-` methods and function-cherrypick

- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/arena/ElemPtr.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/arena/PtrUtil.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/DomainRule.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/SetCupRule.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/SetFilterRule.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/aux/CherryPick.scala
Also contains minor tweaks to `PtrUtil` and an unused method, which handles set-cherrypick in a different way. Currently, due to a lack of understanding of how it impacts performance, the method is not called, but we should revisit it in the future (#2415).
>  ElemPtr rework, pahse 3: Removing `SmtConstElemPtr`s in CherryPick(Set)

- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/arena/PtrUtil.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/arena/PureArenaAdapter.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/aux/CherryPick.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/smt/Z3SolverContext.scala
In addition to adding automatic caching to `ElemPtr`s in `PtrUtil`, this PR also changes the way `Z3SolverContext` handles `in`-relation cells. Previously, attempting to assert and expression containing an `in_X_Y` pointer name would throw, unless `declareInPredIfNeeded` was called at some point in the past. This seems completely pointless and unnecessary, so `getInPred` now just calls `declareInPredIfNeeded` if it doesn't already have the expression cached, instead of throwing.
> Adds pointer caching

- .unreleased/bug-fixes/2430-long-lines.md
- test/tla/Bug2429.tla
- test/tla/cli-integration-tests.md
- tla-pp/src/test/scala/at/forsyte/apalache/tla/pp/TestSourceLocator.scala
- tlair/src/main/scala/at/forsyte/apalache/tla/lir/src/RegionTree.scala
- tlair/src/main/scala/at/forsyte/apalache/tla/lir/src/SourcePosition.scala
- tlair/src/main/scala/at/forsyte/apalache/tla/lir/src/SourceRegion.scala
- tlair/src/test/scala/at/forsyte/apalache/tla/lir/TestSourcePosition.scala
- tlair/src/test/scala/at/forsyte/apalache/tla/lir/TestSourceRegion.scala
Our handling of source positions currently mangles lines and columns into a single integer,
reserving the 3 least-significant digits for the column number.
This causes issues when parsing a file containing lines longer than 999 characters long.
This PR changes `SourcePosition` to represent the line and column numbers as separate integer fields.
We also add comprehensive unit tests for the `SourcePosition` and `SourceRegion` classes.
Fixes #2429
> Fix source position handling

- tla-io/src/main/scala/at/forsyte/apalache/io/ReportGenerator.scala
In our bug report template, Github Markdown fails to recognize the code fence immediately following the `<details>` tag. Insert a newline.
⚠️ Auto-merge is turned on.
> Fix markup in bug report template

- tla-io/src/main/scala/at/forsyte/apalache/io/quint/Quint.scala
- tla-io/src/main/scala/at/forsyte/apalache/io/quint/QuintIR.scala
- tla-io/src/test/scala/at/forsyte/apalache/io/quint/TestQuintEx.scala
Closes #2442
Along the way to adding conversion of builtin quint integer operators I hit upon
a simplification in the test setup, which also motivated addressing the
improvement to the IR interface which @thpani suggested in
https://github.com/informalsystems/apalache/pull/2425#discussion_r1112670162 --
so the IR now accepts a `Seq` anywhere it previously required an `Int`.
The new additions are contained in 7b1111d, the other two commits are just refactoring and cleaup.
-------
> Convert Quint integer operators

- tla-io/src/main/scala/at/forsyte/apalache/io/quint/Quint.scala
- tla-io/src/test/scala/at/forsyte/apalache/io/quint/TestQuintEx.scala
Closes #2438
All remaining set operator are added here, with the exception of `oneOf`, which
will be addressed in #2450.
Thanks to @konnov and @bugarela for the assist on reasoning thru the less
straight forward operators, `oneOf` and `chooseSome`.
-------
> Add conversion of remaining quint set operators

- .unreleased/bug-fixes/print-types.md
- src/tla/__rewire_tlc_in_apalache.tla
- test/tla/PrintTypes.tla
- test/tla/cli-integration-tests.md
> Fix type signatures of `Print` and `PrintT`.

- .unreleased/bug-fixes/quint-empty-sets.md
- tla-io/src/main/scala/at/forsyte/apalache/io/quint/Quint.scala
- tla-io/src/test/scala/at/forsyte/apalache/io/quint/TestQuintEx.scala
The converter for quint empty types was constructing types wrapped in a
Set. This fixes that error, and expands the test to check for this.
Going forward, I write the quint integration while I expand the
converter to catch this earlier.
-------
> Fix typing for quint empty sets

- .unreleased/features/quints-variadic-quants.md
- tla-io/src/main/scala/at/forsyte/apalache/io/quint/Quint.scala
- tla-io/src/main/scala/at/forsyte/apalache/io/quint/QuintIR.scala
- tla-io/src/test/scala/at/forsyte/apalache/io/quint/TestQuintEx.scala
Closes #2454
Allows converting quint's variadic binding operators with `forall` and `exists`. E.g. `s.forall((x, y, z) = ...)`.
Builds on #2460 
> Add support for quint's variadic binding operators

- .unreleased/features/quint-list-ops.md
- tla-io/src/main/scala/at/forsyte/apalache/io/quint/Quint.scala
- tla-io/src/test/scala/at/forsyte/apalache/io/quint/TestQuintEx.scala
Closes #2440
Implementations for `select`, `range`, and `foldr` are not yet included here,
since they will need more involved conversion rules, as per https://github.com/informalsystems/apalache/issues/2437
> Add conversion of quint list operator

- test/tla/Bug1058.tla
- test/tla/cli-integration-tests.md
- tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/ConstSimplifierBase.scala
- tla-pp/src/test/scala/at/forsyte/apalache/tla/pp/TestConstSimplifier.scala
closes #1058 
Recall that `[A -> B]` is defined as the set of functions `f`, for which `D(f) = A` and `\A x \in A: f(x) \in B`. If `B = {}`, then `f(x) \in B` can never be true, so `\A x \in A: f(x) \in B` is `\A x \in A: FALSE`, which depends on whether `A` is exactly empty or not.
The PR introduces a preprocessing step, which rewrites `[A -> {}]` into 
1. `{}`, if `A` is not statically empty
1. `[{} -> Gen(1)]` if `A = {}`. The reason is that the only member of `[{} -> B]` for _any_ `B` is the empty function. In terms of Apalache, this means a function, which evaluates to an arbitrary (type-correct) value everywhere, so we can freely replace `B` with a set of of arbitrary type-correct values (produced via `Gen`).
[changelog format]: …
> Simplification of function sets with statically empty codomains

- tla-io/src/main/scala/at/forsyte/apalache/io/quint/Quint.scala
- tla-io/src/test/scala/at/forsyte/apalache/io/quint/TestQuintEx.scala
Towards #2437, #2479
As discussed synchronously, add an in-code translation for `select`/`SelectSeq`.
> Translate quint `select`

- tla-io/src/main/scala/at/forsyte/apalache/io/quint/Quint.scala
- tla-io/src/test/scala/at/forsyte/apalache/io/quint/TestQuintEx.scala
Towards #2437, #2479
Add in-code translation for Quint `assert`.
> Translate Quint `assert`

- tla-io/src/main/scala/at/forsyte/apalache/io/quint/Quint.scala
- tla-io/src/test/scala/at/forsyte/apalache/io/quint/TestQuintEx.scala
Towards #2437, #2479
As discussed synchronously, add an in-code translation for Quint `foldr`.
I will rebase onto `main` once #2483 is reviewed & merged.
> Translate Quint `foldr`

- tla-io/src/main/scala/at/forsyte/apalache/io/quint/Quint.scala
- tla-io/src/test/scala/at/forsyte/apalache/io/quint/TestQuintEx.scala
Towards #2437, #2479, closes #2489
Add in-code translation for Quint `range`.
> Translate Quint `range`

- tla-io/src/main/scala/at/forsyte/apalache/io/quint/Quint.scala
- tla-io/src/test/scala/at/forsyte/apalache/io/quint/TestQuintEx.scala
We were only handling incrementing integer literals, which is
inadequate, since it doesn't account for expressions such as variables
of compound expressions.
Followup to #2474 
-------
> Fix index increment logic in Quint index conversion

- .unreleased/bug-fixes/quint-indexing.md
- .unreleased/features/quint-ops.md
- tla-io/src/main/scala/at/forsyte/apalache/io/quint/Quint.scala
- tla-io/src/test/scala/at/forsyte/apalache/io/quint/TestQuintEx.scala
Closes #2439 
Closes #2437
Thanks to @konnov for the guidance and @thpani for managing the hairiest part around `put`.
This also includes a fix for misnamed quint addition operator `isum` -> `iadd`.
-------
> Convert quint Map operators (TLA functions)

- .unreleased/features/quint-nondet.md
- tla-io/src/main/scala/at/forsyte/apalache/io/quint/Quint.scala
- tla-io/src/test/scala/at/forsyte/apalache/io/quint/TestQuintEx.scala
Closes #2450
Also includes reorg of the long conversion functions into named functions so we
can keep the builtin conversion case analyses easier to scan. This is isolated
in b22cd39.
> Add conversion of quint nondet binders

- .unreleased/bug-fixes/quint-let-binding.md
- tla-io/src/main/scala/at/forsyte/apalache/io/quint/Quint.scala
- tla-io/src/test/scala/at/forsyte/apalache/io/quint/TestQuintEx.scala
Closes #2501
See 0b69554d378748d9642701f769c950a3bdeda06a for a description of the problem
and the approach taken to solve it.
The only new logic is added in 7a9488fa81f2104f201578ba4b232a13d9cfb1d0, and I
recommend reviewing the commits in reverse order and being sure to ignore white
space.
If tested this fix in integration tests model checking quint specs to be sure it
actually works. That will be added in a PR to quint soon.
> Fix quint conversion of let-binding

- tla-io/src/main/scala/at/forsyte/apalache/io/quint/Quint.scala
- tla-io/src/test/scala/at/forsyte/apalache/io/quint/TestQuintEx.scala
We were constructing an unneeded lambda wrapper, that was also
triggering a type err on the secondary type-checking pass.
```
<unknown>: internal error in type checking: Bug in ToEtcExpr. Expected an operator name, found: LET __QUINT_LAMBDA1(x, y) ≜ x + y IN __QUINT_LAMBDA1 E@15:46:23.130
at.forsyte.apalache.infra.AdaptedException: <unknown>: internal error in type checking: Bug in ToEtcExpr. Expected an operator name, found: LET __QUINT_LAMBDA1(x, y) ≜ x + y IN __QUINT_LAMBDA1
at at.forsyte.apalache.infra.passes.PassChainExecutor$.run(PassChainExecutor.scala:39)
at at.forsyte.apalache.tla.tooling.opt.CheckCmd.run(CheckCmd.scala:132)
at at.forsyte.apalache.tla.Tool$.runCommand(Tool.scala:138)
at at.forsyte.apalache.tla.Tool$.run(Tool.scala:118)
at …
```
> Fix conversion of quint foldr

- .unreleased/bug-fixes/quint-indexing.md
- tla-io/src/main/scala/at/forsyte/apalache/io/quint/Quint.scala
- tla-io/src/test/scala/at/forsyte/apalache/io/quint/TestQuintEx.scala
Closes #2509
Since quint lists are 0-indexed, we need to adjust the indices produced by
`DOMAIN`.
-------
> Fix conversion of quint indices operator

- tla-io/src/main/scala/at/forsyte/apalache/io/quint/Quint.scala
- tla-io/src/test/scala/at/forsyte/apalache/io/quint/TestQuintEx.scala
Closes #2514
Because of the limitation on operator applications discussed in
https://github.com/informalsystems/apalache/pull/2500#issuecomment-1486118937 we
need to specialize the constructed expressions depending whether the test
operator is given by name or a lambda.
> Fix conversion of quint select

- tla-io/src/test/scala/at/forsyte/apalache/io/quint/TestQuintEx.scala
It's becoming difficult to manage the type mapping for the
quint conversion tests, because currently we have to do double entry
when constructing the expressions and their types.
This ugly but pragmatic refactor makes it so that the construction of
expressions and registering their types happens in one go.
This PR is mostly mechanical, and is factored out of the fix for #2516.
-------
> Refactor quint expression conversion tests

- .unreleased/bug-fixes/quint-binding-ops-by-name.md
- tla-io/src/main/scala/at/forsyte/apalache/io/quint/Quint.scala
- tla-io/src/test/scala/at/forsyte/apalache/io/quint/TestQuintEx.scala
Closes #2516
Adds a case to the binaryBindingApp combinator to handle "binder" passed by
name. This is a pretty straightforward conversion akin to an eta conversion. 
I've tested this in a (WIP) integration test in the quint repo.
> Support quint binding operator passed by name

- tla-io/src/main/scala/at/forsyte/apalache/io/quint/Quint.scala
- tla-io/src/test/scala/at/forsyte/apalache/io/quint/TestQuintEx.scala
Found this while writing the integration tests for maps. I had just forgottent
to construct the appropriate element type in the case we needed to construct an
empty function.
-------
> Fix converting empty quint maps construction

- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/smt/Z3SolverContext.scala
Reuse the global Z3 `Params` object when setting a timeout in `Z3SolverContext`.
This was shadowing the global parameter object, on which we set the random seed.
So, perhaps, this fixez #2120? 🫣🤞
> Avoid shadowed field in when setting Z3 parameters

- .unreleased/bug-fixes/ignore-quint-runs.md
- tla-io/src/main/scala/at/forsyte/apalache/io/quint/Quint.scala
We don't currently support Quint runs in Apalache, and don't have any
immanent plans to do so.
I cannot think of any tests that are simpler than the change to
introduce this logic, so unless anyone can suggest one, I'll claim the
correctness of this change is self evident :)
Closes informalsystems/quint#896
-------
- [-] Tests added for any new code
> Ignore Quint run declarations

- tlair/src/main/scala/at/forsyte/apalache/tla/typecomp/signatures/FlexibleEquality.scala
- tlair/src/main/scala/at/forsyte/apalache/tla/types/TypeUnifier.scala
- tlair/src/test/scala/at/forsyte/apalache/tla/lir/TlaType1Gen.scala
- tlair/src/test/scala/at/forsyte/apalache/tla/typecomp/BuilderTest.scala
- tlair/src/test/scala/at/forsyte/apalache/tla/typecomp/TestBaseBuilder.scala
- tlair/src/test/scala/at/forsyte/apalache/tla/typecomp/TestRowTypedRecords.scala
Closes #2559
Closes #2581
It appears that the typed builder is not currently able to handle constructing application of polymorphic operator.
This adds a regression test for this omission and a fix to unblock it.
The fix is to replace the limited and more ad-hoc type compatibility check used in the builder previously with the same type unifier we use for type checking. The result is
- More code reuse.
- More correct checks on type compatibility in the builder.
- Less code.
This will unblock #2552.
> Support application of polymorphic operators in typed builder

- project/Dependencies.scala
- tla-io/src/main/scala/at/forsyte/apalache/tla/imp/SanyImporter.scala
Builds on Scala Steward's #2575 and fixes a deprecation warning breaking our CI.
- [-] Tests added for any new code
- [-] Documentation added for any new functionality
- [-] [Entries added to `./unreleased/`][changelog format] for any new functionality
> Update commons-io to 2.12.0

- tla-io/src/main/scala/at/forsyte/apalache/io/quint/Quint.scala
- tla-io/src/test/scala/at/forsyte/apalache/io/quint/TestQuintEx.scala
Flip arguments of `WF` and `SF` in Quint -> Apalache translation
> Fix argument order of `WF`/`SF` in Quint translation

- tla-io/src/main/scala/at/forsyte/apalache/io/quint/Quint.scala
Small fix to correctly consider nullary operators inside a Quint `assume` statement.
Thanks @shonfeder for confirming this fix.
> Consider nullary ops in Quint assume

- tla-io/src/main/scala/at/forsyte/apalache/io/quint/Quint.scala
- tla-io/src/test/scala/at/forsyte/apalache/io/quint/TestQuintEx.scala
Predefined set `BOOLEAN` requires special conversion of its Quint name `Bool`.
> Account for predefined set names

- tla-io/src/main/scala/at/forsyte/apalache/io/quint/Quint.scala
Rename quint lambda `_` parameters to `__QUINT_UNDERSCORE_{id}`.
This prevents shadowing of nested underscore parameters.
Closes #926
> Prevent shadowing of "_" Quint lambda parameters

- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/aux/CherryPick.scala
> Pointer propagation fix for powerset-cherrypick

- build.sbt
Update deprecated calls that append Sonatype resolvers in `build.sbt`.
This fixes the following deprecation warnings when building:
```
/home/runner/work/apalache/apalache/build.sbt:27: warning: method sonatypeRepo in class ResolverFunctions is deprecated (since 1.7.0): Use sonatypeOssRepos instead e.g. `resolvers ++= Resolver.sonatypeOssRepos("snapshots")`
Resolver.sonatypeRepo("snapshots"),
^
/home/runner/work/apalache/apalache/build.sbt:28: warning: method sonatypeRepo in class ResolverFunctions is deprecated (since 1.7.0): Use sonatypeOssRepos instead e.g. `resolvers ++= Resolver.sonatypeOssRepos("snapshots")`
Resolver.sonatypeRepo("releases"),
^
```
> Replace deprecated sonatype resolver

- .unreleased/bug-fixes/2621-qnt-nat-int.md
- tla-io/src/main/scala/at/forsyte/apalache/io/quint/Quint.scala
Translate `Nat`, `Int` to their built-in values.
We already considered `Bool`, because its name in TLA+ is different, but `Nat` and `Int` were missing.
ℹ️ Auto-merge is on
> Fix Quint translation of `Nat` and `Int`

- .unreleased/bug-fixes/2623-grpc-msg-size.md
- shai/src/main/scala/at/forsyte/apalache/shai/v1/RpcServer.scala
Increase max inbound gRPC message size to 8MB
This fixes an issue where large-enough Quint specs fail with
```
io.grpc.StatusRuntimeException: RESOURCE_EXHAUSTED: gRPC message exceeds maximum size 4194304: 5177182
```
Closes #2622
ℹ️ Auto-merge is **ON**
> Increase max inbound gRPC message size

- .unreleased/bug-fixes/2629-typevar-translation.md
- tla-io/src/main/scala/at/forsyte/apalache/io/quint/Quint.scala
- tla-io/src/main/scala/at/forsyte/apalache/io/quint/QuintTypeConverter.scala
- tla-io/src/test/scala/at/forsyte/apalache/io/quint/TestQuintEx.scala
- tla-io/src/test/scala/at/forsyte/apalache/io/quint/TestQuintTypes.scala
Use a single type converter for an entire quint spec.
We previously used one type converter per sub-expression. This re-initialized the map for translating Quint type variables (named) to Apalache TypeSystem 1 type variables (numbered), causing wrong type annotations. For example the type of the following Quint was translated as `(a,a) => {src: a, ts: a}`.
```bluespec
/// `p.msgFrom(ts)` is a message sent from `p` at time `ts` 
def msgFrom(p, ts) = {src: p, ts : ts}
```
> Use single typevar map for entire spec

- tlair/src/main/scala/at/forsyte/apalache/tla/typecomp/unsafe/UnsafeBaseBuilder.scala
Extend the exception message with expected and actual types, and the affected expression.
> Extend unification error message in appOp

- .unreleased/bug-fixes/2634-quint-open-tuple.md
- tla-io/src/main/scala/at/forsyte/apalache/io/quint/QuintTypeConverter.scala
- tla-io/src/test/scala/at/forsyte/apalache/io/quint/TestQuintTypes.scala
Translate Quint open row tuples to sparse tuples.
Also fixes an offset in the previous (non-sparse) tuple test.
> Translate Quint open row tuples to sparse tuples

- tla-io/src/main/scala/at/forsyte/apalache/io/quint/Quint.scala
Shorten the error message, if the typed builder fails to build a `QuintOpDef`.
Previously, this was printing the entire operator definition IR, which pollutes output, but isn't very useful. Now, this just prints the operator name that failed to build.
> Shorten error message on builder errors

- tlair/src/main/scala/at/forsyte/apalache/tla/typecomp/unsafe/UnsafeBaseBuilder.scala
2 small improvements to error messages the Quint translation / typed builder:
* print only the operator name, not the entire opdef IR, when constructing TLA+ from a QuintOpDef fails
* add an explanation for a failed `require` in the typed builder
> Small error message improvements

- .unreleased/bug-fixes/2684-decode-recrow.md
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/SymbStateDecoder.scala
Fixes #2683 
SymbStateDecoder is calling `tla.rec()` to decode a `RecRowT1` cell.
This leads to a type mismatch in `LazyEquality` (described in #2683) when asserting a path constraint, because we compare the original `RecRowT1` to the decoded `RecT1`.
Construct a RecRowT1 for cells of such type, via `tla.rowRec()`.
> Use tla.rowRec to decode RecRowT1 cells

- .unreleased/bug-fixes/2697-fresh-model-values.md
- docs/src/HOWTOs/uninterpretedTypes.md
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/SymbStateDecoder.scala
Construct fresh values when decoding a cell not in the model-value cache.
Fixes #2690 
> Construct fresh model values

- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/aux/ValueGenerator.scala
- tla-bmcmt/src/test/scala/at/forsyte/apalache/tla/bmcmt/TestSymbStateDecoder.scala
closes #2702 
Arenas for `Gen`-created sets were incorrectly always using fixed pointers, meaning that in the reconstruction (and subsequent output) these sets were shown to contain elements, which the underlying SMT constraints did not imply. The fix is to use a pointer with an unconstrained SMT value instead, and let the solver determine memberships, if any.
> Arena fix for Gen

- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/stratifiedRules/aux/RewriterImpl.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/stratifiedRules/base/IntConstStratifiedRule.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/stratifiedRules/base/SubstStratifiedRule.scala
- tla-bmcmt/src/test/scala/at/forsyte/apalache/tla/bmcmt/stratifiedRules/BoolRewriterTest.scala
- tla-bmcmt/src/test/scala/at/forsyte/apalache/tla/bmcmt/stratifiedRules/IntRewriterTest.scala
closes #2705 
In addition, tweaks the interface of `SubstStratifiedRule`, to avoid implementing an unnecessary do-nothing unit method, and adds a previously missing `BOOLEAN` set test.
> StratifiedRules: Integer literals

- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/stratifiedRules/aux/oracles/IntOracle.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/stratifiedRules/aux/oracles/Oracle.scala
- tla-bmcmt/src/test/scala/at/forsyte/apalache/tla/bmcmt/stratifiedRules/aux/oracles/TestIntOracle.scala
First step towards #2708. 
The PR makes the following changes to https://github.com/informalsystems/apalache/blob/6bb36acc1ad88fdeba21d45b67663b1e792e29c6/tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/aux/Oracle.scala:
- `SymbState` is replaced by `RewriterScope`
- Method names/parameters are renamed to be more verbose, but also more descriptive
- Exception previously thrown by each implementation individually has been pushed into the base trait
- Signature of `caseAssertions` has been changed such that the optional sequence is now an `Option`, instead of treating the empty sequence as a special case.
- Signature of `getIndexOfOracleValueFromModel` (previously `evalPosition`) has been changed, to no longer include `state`. Upon inspection, none of the oracle implementations …
> First attempt at refactoring `Oracle`s

- .unreleased/features/2732.md
- docs/src/adr/015adr-trace.md
- tla-io/src/main/scala/at/forsyte/apalache/io/itf/ItfToTla.scala
- tla-io/src/main/scala/at/forsyte/apalache/io/lir/ItfCounterexampleWriter.scala
- tla-io/src/test/scala/at/forsyte/apalache/io/lir/TestItfCounterexampleWriter.scala
Closes #2732. In this PR, we further simplify the ITF format by always representing integers as `{ "#bigint": "num" }`, instead of having two cases, namely, `num` for small integers and `{ "#bigint": "num" }` for big integers. This should simplify the usage of ITF in tests.
> Revise the ITF format

- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/vmt/BoolRule.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/vmt/EUFRule.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/vmt/FormulaRule.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/vmt/QuantifierRule.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/vmt/RestrictedSetJudgement.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/vmt/TermToVMTWriter.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/vmt/TlaExToVMTWriter.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/vmt/TlaType1ToSortConverter.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/vmt/ToTermRewriter.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/vmt/ToTermRewriterImpl.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/vmt/VMTExpr.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/vmt/ValueRule.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/vmt/package.scala
- tla-bmcmt/src/test/scala/at/forsyte/apalache/tla/bmcmt/rules/vmt/TestBoolRule.scala
- tla-bmcmt/src/test/scala/at/forsyte/apalache/tla/bmcmt/rules/vmt/TestEUFRule.scala
- tla-bmcmt/src/test/scala/at/forsyte/apalache/tla/bmcmt/rules/vmt/TestJudgement.scala
- tla-bmcmt/src/test/scala/at/forsyte/apalache/tla/bmcmt/rules/vmt/TestQuantRule.scala
- tla-bmcmt/src/test/scala/at/forsyte/apalache/tla/bmcmt/rules/vmt/TestTermConstruction.scala
- tla-bmcmt/src/test/scala/at/forsyte/apalache/tla/bmcmt/rules/vmt/TestValueRule.scala
- tlair/src/main/scala/at/forsyte/apalache/tla/lir/formulas/Base.scala
- tlair/src/main/scala/at/forsyte/apalache/tla/lir/formulas/Booleans.scala
- tlair/src/main/scala/at/forsyte/apalache/tla/lir/formulas/EUF.scala
- tlair/src/main/scala/at/forsyte/apalache/tla/lir/formulas/Integers.scala
This PR attempts to change the way the internal transpilation is performed, and, to a lesser extent, the SMT term representation.
The main issue is, that SMT separates two concepts: terms, and declarations/definitions. In an effort to make the transpilation "side-effect free", `FunDef` was introduced as a `Term`, which represented a function, to be defined in the SMT header, but used (by name) wherever `FunDef` appeared in the syntax tree. Later, a `Collector` would traverse the tree again, and extract the function definitions, along with any uninterpreted literals, which also needed to be declared.
This is clunky, and does not scale with extensions to `Term`s. Instead, the new approach introduces rules as `State` computations over a class which holds SMT declarations. This way, rules …
> PI-week: Refactor Transpile

- test/tla/cli-integration-tests.md
It's possible for output to be printed after the welcome message in
these tests. This change accounts for that.
An example of the incorrect failures on this case is https://github.com/informalsystems/apalache/actions/runs/6225708423/job/16896714985?pr=2739
It's just a race condition on the output.
-------
> Account for possible output in CLI server test

- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/stratifiedRules/aux/oracles/SparseOracle.scala
- tla-bmcmt/src/test/scala/at/forsyte/apalache/tla/bmcmt/stratifiedRules/aux/oracles/TestSparseOracle.scala
Following the pattern laid out in #2709 for `IntOracle`, this PR introduces the same alterations to `SparseOracle`.
> `SparseOracle` refactor

- docs/src/apalache/tlc-config.md
Action constraints in cfg files are labelled with `ACTION_CONSTRAINT` or `ACTION_CONSTRAINTS`, not `ACTION-CONSTRAINT` or `ACTION-CONSTRAINTS` (underscore instead of a hyphen).
Based on this comment in the TLC source code, I believe it changed from a hyphen to an underscore in 2009 https://github.com/tlaplus/tlaplus/blob/a41cbafc66b1dd225156aaca38ad35ec330f4ae9/toolbox/org.lamport.tla.toolbox.tool.tlc/src/org/lamport/tla/toolbox/tool/tlc/launch/TLCModelLaunchDelegate.java#L588
> Update TLC cfg file syntax

- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/PrimeRule.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/SubstRule.scala
- tla-bmcmt/src/test/scala/at/forsyte/apalache/tla/bmcmt/TestSymbStateRewriterAction.scala
- tla-bmcmt/src/test/scala/at/forsyte/apalache/tla/bmcmt/trex/TestTransitionExecutorImpl.scala
closes #2747
No regression tests, since this error only surfaces if an intermediate expression has no rule applicable to it (as is the case in the example provided in #2747), otherwise untyped ephemeral cell expressions do not break the solver.
> Bugfix for #2747

- .unreleased/bug-fixes/2758-sim-timeout.md
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/SeqModelChecker.scala
Prevent Apalache from halting the (global) search if an enabledness query times out in `simulate`.
This is a simple fix that considers a transition disabled if the corresponding SMT query times out in `simulate` mode.
A more comprehensive treatment of timeouts in `simulate` would be more invasive: It would require us to differentiate timeouts from other `UNKNOWN` Z3 results, and to define (or parameterize) the expected search behavior if invariant or deadlock checks time out during simulation.
Partially addresses #2316 and unblocks https://github.com/informalsystems/quint/issues/1196.
> Continue simulation on SMT timeout in enabledness check

- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/passes/VCGenPassImpl.scala
Fix a log message. This was printing `Only deadlocks will be checked` even with `--no-deadlocks`.
Fixes #2118
> Fix deadlock log message

- test/tla/Bug2772.tla
- test/tla/cli-integration-tests.md
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/analyses/ExpansionMarker.scala
closes #2772
The intended behavior is to throw an error, if a function set is packed into an expandable expression (e.g. `UNION`). 
The underlying issue was that `ExpansionMarker` was scope-unaware, as it was setting subexpression flags without regard to the current value of the flag.
> Throw error when attempting to construct a UNION of function sets

- mod-infra/src/main/scala/at/forsyte/apalache/infra/DefaultExceptionAdapter.scala
- project/Dependencies.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/config/CheckerExceptionAdapter.scala
- tla-io/src/main/scala/at/forsyte/apalache/tla/imp/ParserExceptionAdapter.scala
- tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/Desugarer.scala
- tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/ExprOptimizer.scala
- tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/Keramelizer.scala
- tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/Normalizer.scala
- tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/TypeSubstitutor.scala
- tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/temporal/LoopEncoder.scala
- tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/temporal/TableauEncoder.scala
- tlair/src/main/scala/at/forsyte/apalache/tla/lir/transformations/standard/IncrementalRenaming.scala
Upgrade our dependencies to Guice 7. Closes #2579.
Guice dropped support for `javax.inject.*` in favor of `jakarta.inject.*`:
https://github.com/google/guice/wiki/Guice700#jee-jakarta-transition
Since we do not want to pull in Java EE, we're switching to the properietary `com.google` package.
> Upgrade dependencies to Guice 7

- tla-io/src/main/scala/at/forsyte/apalache/io/quint/Quint.scala
- tla-io/src/test/scala/at/forsyte/apalache/io/quint/TestQuintEx.scala
Closes #2774
This is a workaround for https://github.com/informalsystems/quint/issues/381. 
The nub of the issue is that quint currently allows `oneOf` to occur outside of
`nondet` bindings, but we don't want to support this behavior in verification.
Our expectation is that we will make this illegal in quint, but in the mean time
this change will ensure less cryptic errors until the quint type discipline for
the operator is improved.
-------
> Add case to handle oneOf outside of nondet

- .unreleased/bug-fixes/2785-rewriter-disposal.md
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/passes/BoundedCheckerPassImpl.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/trex/OfflineExecutionContext.scala
- tla-bmcmt/src/test/scala/at/forsyte/apalache/tla/bmcmt/trex/ExecutorBase.scala
- tla-bmcmt/src/test/scala/at/forsyte/apalache/tla/bmcmt/trex/TestTransitionExecutorWithIncrementalAndArrays.scala
- tla-bmcmt/src/test/scala/at/forsyte/apalache/tla/bmcmt/trex/TestTransitionExecutorWithIncrementalAndFunArrays.scala
- tla-bmcmt/src/test/scala/at/forsyte/apalache/tla/bmcmt/trex/TestTransitionExecutorWithOfflineAndArrays.scala
- tla-bmcmt/src/test/scala/at/forsyte/apalache/tla/bmcmt/trex/TestTransitionExecutorWithOfflineAndFunArrays.scala
Fix disposal of rewriters in `OfflineExecutionContext`.
We previously omitted disposing of rewriters that were obsoleted by a call to `ctx.recover()`.
At the very least, this resulted in truncated SMT debug logs, see #2136 
We also fix a small protocol violation, where `BoundedCheckerPassImpl` was disposing of the rewriter directly, instead of disposing of the offline execution context (which in turn disposes of the rewriter).
Closes #2136
> Fix rewriter disposal in offline execution context

- .unreleased/bug-fixes/fix-default-cases.md
- tla-io/src/main/scala/at/forsyte/apalache/io/quint/Quint.scala
- tla-io/src/test/scala/at/forsyte/apalache/io/quint/TestQuintEx.scala
This is a followup to #2783, which omitted support for the "wildcard",
default match case in match expressions.
I found this problem when checking the `Paxos` spec in the quint repo.  In
addition to the unit test added here, I've verified that this solves the problem
on a few quint specs locally. Integration tests confirming this will be
forthcoming in the quint repo.
-------
> Add support for default cases in quint match expressions

- .unreleased/bug-fixes/fixSetInclusionwithArrays.md
- test/tla/FunInInfiniteSubset.tla
- test/tla/cli-integration-tests.md
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/SetInclusionRuleWithArrays.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/SetInclusionRuleWithFunArrays.scala
This PR fixes a crash on the `arrays` and `funArrays` encodings. See the associated issue for details. Closes #2810.
> Add support for infinite sets in set inclusion for the (fun)arrays encoding

- .unreleased/features/01.md
- tla-io/src/main/scala/at/forsyte/apalache/io/json/JsonToTla.scala
- tla-io/src/main/scala/at/forsyte/apalache/io/json/JsonToTlaViaBuilder.scala
- tla-io/src/main/scala/at/forsyte/apalache/io/json/TlaToJson.scala
- tla-io/src/main/scala/at/forsyte/apalache/io/lir/PrettyWriter.scala
- tla-io/src/main/scala/at/forsyte/apalache/io/quint/Quint.scala
- tla-io/src/main/scala/at/forsyte/apalache/io/quint/QuintIR.scala
- tla-io/src/main/scala/at/forsyte/apalache/tla/imp/AssumeTranslator.scala
- tla-io/src/test/scala/at/forsyte/apalache/io/TestPrettyWriterWithTypes.scala
- tla-io/src/test/scala/at/forsyte/apalache/io/json/TestTlaToUJson.scala
- tla-io/src/test/scala/at/forsyte/apalache/io/json/TestUJsonToTla.scala
- tla-io/src/test/scala/at/forsyte/apalache/io/json/TestUJsonToTlaViaBuilder.scala
- tla-io/src/test/scala/at/forsyte/apalache/io/quint/TestQuintEx.scala
- tla-io/src/test/scala/at/forsyte/apalache/io/quint/TestQuintIR.scala
- tla-io/src/test/scala/at/forsyte/apalache/tla/imp/TestSanyImporter.scala
- tla-typechecker/src/main/scala/at/forsyte/apalache/tla/typecheck/etc/ToEtcExpr.scala
- tla-typechecker/src/main/scala/at/forsyte/apalache/tla/typecheck/integration/TypeRewriter.scala
- tla-typechecker/src/test/scala/at/forsyte/apalache/tla/typecheck/etc/TestToEtcExprDecls.scala
- tlair/src/main/scala/at/forsyte/apalache/tla/lir/TlaDecl.scala
- tlair/src/main/scala/at/forsyte/apalache/tla/lir/TlaLevelFinder.scala
- tlair/src/main/scala/at/forsyte/apalache/tla/lir/io/Printer.scala
- tlair/src/main/scala/at/forsyte/apalache/tla/lir/transformations/standard/DeclarationSorter.scala
- tlair/src/main/scala/at/forsyte/apalache/tla/lir/transformations/standard/DeepCopy.scala
- tlair/src/main/scala/at/forsyte/apalache/tla/lir/transformations/standard/ModuleByExTransformer.scala
- tlair/src/test/scala/at/forsyte/apalache/tla/lir/IrGenerators.scala
- tlair/src/test/scala/at/forsyte/apalache/tla/lir/TestPrinter.scala
- tlair/src/test/scala/at/forsyte/apalache/tla/lir/transformations/standard/TestDeclarationSorter.scala
- tlair/src/test/scala/at/forsyte/apalache/tla/lir/transformations/standard/TestDeepCopy.scala
> Parse ASSUME declarations names

- .unreleased/bug-fixes/2800-error-on-empty-files.md
- test/tla/cli-integration-tests.md
- tla-io/src/main/scala/at/forsyte/apalache/tla/imp/SanyImporter.scala
> Handle empty file error

- shai/src/main/scala/at/forsyte/apalache/shai/v1/RpcServer.scala
I've been hitting this limit and this increases it. Closes https://github.com/informalsystems/quint/issues/1389
> Increase gRPC message size limit from 8MB to 64MB

- CONTRIBUTING.md
- flake.lock
- flake.nix
This PR:
1. Updates `flake.nix` to remove sourcing of `.envrc` file which resulted in a circular dependency if `direnv` was used to load nix. Other changes in `flake.nix` are just auto-formatting.
2. Adds instructions to `CONTRIBUTING.md` with how to use nix with `direnv`.
3. Updates `flake.lock` (with `nix flake update`) so the pinned version of `metals` is compatible with the scala version declared in `build.sbt`.
> Update flake and improve nix setup for development

- .unreleased/bug-fixes/quint-lambda-types-conversion.md
- tla-io/src/main/scala/at/forsyte/apalache/io/quint/Quint.scala
- tla-io/src/test/scala/at/forsyte/apalache/io/quint/TestQuintEx.scala
- tlair/src/main/scala/at/forsyte/apalache/tla/typecomp/ScopedBuilder.scala
Fixes https://github.com/informalsystems/quint/issues/1393
The issue happened because we were only using the types given by Quint in the type map to annotate parameters, but not the result type of lambdas. This way, there was a mismatch in variable names on Apalache type inference (used for the body) and Quint type inference (used for the parameters).
This PR ensures that we always use Quint types.
> Use type given by quint to build lambda bodies

- shai/src/test/scala/at/forsyte/apalache/shai/v1/TestCmdExecutorService.scala
- test/tla/cli-integration-tests.md
- tla-io/src/main/scala/at/forsyte/apalache/io/lir/TlaWriter.scala
Fixes an error in the existing TLA+ generated from quint, thanks to report from @bugarela
-------
> Extend Variants when pretty printing TLA+ in Shai

- tla-io/src/main/scala/at/forsyte/apalache/io/lir/PrettyWriter.scala
- tla-io/src/test/scala/at/forsyte/apalache/io/lir/TestPrettyWriter.scala
> Sanitize identifiers when pretty printing

- .unreleased/bug-fixes/converting-unit-types.md
- tla-io/src/main/scala/at/forsyte/apalache/io/quint/Quint.scala
- tla-io/src/main/scala/at/forsyte/apalache/io/quint/QuintTypeConverter.scala
- tla-io/src/test/scala/at/forsyte/apalache/io/quint/TestQuintEx.scala
- tla-io/src/test/scala/at/forsyte/apalache/io/quint/TestQuintTypes.scala
Hello :octocat:
This is needed as a consequence of https://github.com/informalsystems/quint/pull/1406, which started because we can't write empty records in TLA+ directly. In the end, we decided to use uninterpreted types/values to represent the unit type/value.
> Convert Quint empty tuples into uninterpreted types/values

- .github/workflows/main.yml
This fixes our unit tests setup in MacOS, which has recently started failing due to cache misses.
This follows instructions from https://github.com/coursier/setup-action
Before: https://github.com/informalsystems/apalache/actions/runs/8939732842/job/24556354036?pr=2891
After: https://github.com/informalsystems/apalache/actions/runs/8943811456/job/24569332724?pr=2891
> Fix unit test CI on MacOS

- .github/workflows/main.yml
`docker-tests` is failing after the migration to the org `apalache-mc`. Provisionally, disabling this workflow. Repairing is filed in #2931.
> provisionally disable docker-tests

- .unreleased/features/translate-generate.md
- tla-io/src/main/scala/at/forsyte/apalache/io/quint/Quint.scala
- tla-io/src/test/scala/at/forsyte/apalache/io/quint/TestQuintEx.scala
This PR adds translation of Quint `generate` introduced in https://github.com/informalsystems/quint/pull/1455 into `Apalache!Gen`.
> Translate Quint `generate`

- .unreleased/features/timeout-smt.md
- docs/src/apalache/tuning.md
- mod-infra/src/main/scala/at/forsyte/apalache/infra/passes/options.scala
- mod-tool/src/main/scala/at/forsyte/apalache/tla/tooling/opt/CheckCmd.scala
- test/tla/cli-integration-tests.md
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/Checker.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/SeqModelChecker.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/passes/BoundedCheckerPassImpl.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/search/ModelCheckerParams.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/search/SearchState.scala
In our experiments, it sometimes happens that `apalache-mc simulate` gets stuck in a randomly selected schedule, without progressing for many hours. Since we would like to get quicker feedback with `simulate`, this PR add the CLI option `--timeout-smt` that limits the time spent on a single SMT query. Also, we are removing the old tuning option `search.smt.timeout`, which is hard to discover.
> add `--timeout-smt` to `check` and `simulate`

- .unreleased/features/rewrite.md
- tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/ExprOptimizer.scala
- tla-pp/src/test/scala/at/forsyte/apalache/tla/pp/TestExprOptimizer.scala
```tla
EXTENDS Integers
VARIABLE
\* @type: Set({ p: (Int) });
v
TypeOK ==
v \in SUBSET [ p: Int ]
Init ==
v = { [p |-> 42] }
Next ==
UNCHANGED v
```
```sh
$ apalache-mc check --inv=TypeOK APARecSub.tla
[...]
Input error (see the manual): Found a set map over an infinite set of CellTFrom(Int). Not supported.
```
```tla
S \in SUBSET [a : T] ~~> \A r \in S: DOMAIN r = { "a" } /\ r.a \in T
```
Related commits, issues, PRs:
* 625a1645e75a910d43759c36ad8a06291ebc55b3
* 785e26925a45b077e14cf79f31f834e0c0919639
* https://github.com/apalache-mc/apalache/issues/723
* https://github.com/apalache-mc/apalache/issues/1627
* https://github.com/apalache-mc/apalache/issues/2762
* https://github.com/apalache-mc/apalache/pull/1453
* https://github.com/apalache-mc/apalache/pull/1629
> Rewrite for set membership of the powerset of a record where the record has infinite co-domains.

- .github/workflows/main.yml
closes #2931. Since the docker container is now properly built #2932, the docker tests should be working again
> enable docker tests

- .unreleased/bug-fixes/2969-powset-expansion
- test/tla/TestSets.tla
- test/tla/cli-integration-tests.md
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/Limits.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/config/CheckerExceptionAdapter.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/exceptions.scala
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/aux/PowSetCtor.scala
This PR simply improves error reporting for the case when `SUBSET _` has to be expanded to a very large set:
Currently, the source location of the problematic code is not properly identified, due to multiple iterations of the rewriter. We could try to recover the source location when unwinding the rewriting stack. However, this would require a more careful refactoring. 
> improve the error message about expanding powersets

- .unreleased/features/rewrite.md
- tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/ExprOptimizer.scala
- tla-pp/src/test/scala/at/forsyte/apalache/tla/pp/TestExprOptimizer.scala
```tla
----- MODULE ljasf -----
EXTENDS Integers
VARIABLE
\* @type: { v: Set( { p: Set( { v: Set(Int) } ) } ) };
m
TypeOK ==
m \in [ v : SUBSET [ p : SUBSET [ v: SUBSET {1,2,3,4,5}] ] ]
Init ==
m = [ v |-> {[p |-> {[v |-> {1}]} ]} ]
Next ==
UNCHANGED m
====
```
```
input:
m["v"] ∈ SUBSET ({["p" ↦ t_5$1] : t_5$1 ∈ SUBSET ({["v" ↦ t_4$1] : t_4$1 ∈ SUBSET {1, 2, 3, 4, 5}})})
old output:
∀t_a ∈ m["v"]: ((DOMAIN t_a = {"p"}) ∧ (∀t_b ∈ t_a["p"]: ((DOMAIN t_b = {"v"}) ∧ t_b["v"] ∈ SUBSET {1, 2, 3, 4, 5})))
new output:
∀t_a ∈ m["v"]: ((DOMAIN t_a = {"p"}) ∧ (∀t_b ∈ t_a["p"]: ((DOMAIN t_b = {"v"}) ∧ (∀t_c ∈ t_b["v"]: t_c ∈ {1, 2, 3, 4, 5}))))
```
> ExprOptimizer: Rewrite `S \in SUBSET T` when it occurs in subexpressions

- tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/Keramelizer.scala
- tla-pp/src/test/scala/at/forsyte/apalache/tla/pp/TestKeramelizer.scala
Keramelizer:
`A \in SUBSET B  ~~>  \A a \in A: a \in B`
Part of Github issue #2948
https://github.com/apalache-mc/apalache/issues/2948
> Bogus safety violation checking if a set is a subset of Nat.

- project/Dependencies.scala
- tla-io/src/main/scala/at/forsyte/apalache/io/quint/QuintIR.scala
- tla-io/src/test/scala/at/forsyte/apalache/io/quint/TestQuintIR.scala
This is a replacement for https://github.com/apalache-mc/apalache/pull/2905
I've updated `upickle` and `ujson` all the way to the most recent version (`4.0.0`), as that includes features for things we had to work around before. This way, I was able to remove all of the customized `rw` values, as `macroRW` works for everything now (with the proper config updates).
I've also added a couple of tests that helped me debug things, but no behavior was changed.
I checked that this version is compatible with all Quint's integration tests.
- [-] Documentation added for any new functionality
- [-] [Entries added to `./unreleased/`][changelog format] for any new functionality
[changelog format]: https://github.com/informalsystems/apalache/blob/main/CONTRIBUTING.md#how-to-record-a-chan …
> Update upickle to 4.0.0 and remove unecessary customizations

- .unreleased/bug-fixes/distinct-on-singleton.md
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/smt/Z3SolverContext.scala
Closes #2964. Simply translate `distinst` into `true`, when we have less than two subexpressions. It's only relevant for replaying SMT logs in CVC5, but it was sufficiently annoying for me to fix it.
> produce true on distinct for less than 2 elements

- .unreleased/breaking-changes/downgrade-z3.md
- project/Dependencies.scala
Since I've hit assertion failures and even cores dumped with 4.13.0, downgrading z3 to 4.12.6. This is a potentially breaking (unbreaking) change, so we will cut a separate minor release for this.
> Downgrade Z3 to 4.12.6

- README.md
- docs/src/adr/006rfc-unit-testing.md
- docs/src/tutorials/entry-tutorial.md
- docs/src/tutorials/pluscal-tutorial.md
- docs/src/tutorials/snowcat-tutorial.md
Replace some left-over links to Zulip with Discourse
> Replace some left-over Zulip links with Discourse

- .unreleased/bug-fixes/quint-to-tla-transpilation.md
- tla-io/src/main/scala/at/forsyte/apalache/io/lir/PrettyWriter.scala
- tla-io/src/main/scala/at/forsyte/apalache/io/quint/Quint.scala
- tla-io/src/main/scala/at/forsyte/apalache/io/quint/QuintTypeConverter.scala
- tla-io/src/test/scala/at/forsyte/apalache/io/lir/TestPrettyWriter.scala
- tla-io/src/test/scala/at/forsyte/apalache/io/quint/TestQuintEx.scala
- tla-io/src/test/scala/at/forsyte/apalache/io/quint/TestQuintTypes.scala
I was running into some issues when using Apalache to transpile Quint into TLA+. There were even parsing errors with invalid parenthesis. After much debugging, I got to fix all of the ones I know of, except for the assignments in init (which are not a big deal because there's only one init per spec so it's always easy to manually fix those).
Here are the issues:
1. Whenever we had a default eliminator on a match, we would produce something like `QUINT_LAMBDA1([])`, but `[]` is not a valid TLA+ expression. I've replaced it with `{}`.
2. When accessing a map (function) with lists as domains, we need to do something like `map[<<1, 2>>]` but the pretty printer was removing the tuple wrapper on this and producing `map[1, 2]` instead which is not right.
- I don't know why this …
> Quint -> TLA+ transpilation fixes

- .unreleased/bug-fixes/sany-tmpdir.md
- src/universal/bin/apalache-mc
Although rare, it may still happen that multiple CLI instances of Apalache hit concurrency issues that is filed in https://github.com/tlaplus/tlaplus/issues/688 (`apalache-mc server` has a separate mutex for that):
```
$ cat t.tla
------------------- MODULE t --------------------                               
EXTENDS Integers
VARIABLE
\* @type: Int;
x
Init == x = 0
Next == x' = x + 1
=================================================
$ seq 1 100 | parallel ~/devl/apalache/bin/apalache-mc parse --out-dir=c/{} t.tla
...
Encountered an exception while attempt to validate /var/folders/93/s11lf4f16c77bpq91r90njbm0000gn/T/Naturals.tla - /var/folders/93/s11lf4f16c77bpq91r90njbm0000gn/T/Naturals.tla (No such file or directory)
```
This is a simple fix that was already discussed in …
> protect against SANY race conditions on the filesystem

- .github/workflows/main.yml
All of a sudden, `sbt` is not included by default: https://github.com/actions/runner-images/issues/10788. This PR should fix that.
> fixing sbt in the CI

- .unreleased/breaking-changes/3057-z3.md
- project/Dependencies.scala
- test/tla/cli-integration-tests.md
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/smt/Z3SolverContext.scala
Via the new z3(-turnkey) releases (see https://github.com/Z3Prover/z3/issues/7201 and https://github.com/tudo-aqua/z3-turnkey/issues/18) we finally have support for `linux/arm64`.
We also stop passing the legacy parameter `seed`, which it seems has been removed.
If we try to pass it, `Solver.add` fails with
```
com.microsoft.z3.Z3Exception: unknown parameter 'seed'
Legal parameters are:
...
```
Only `random_seed` remains in the list.
> Upgrade Z3 (restores linux/arm64 support)

- tla-io/src/main/scala/at/forsyte/apalache/io/lir/PrettyWriter.scala
This repo will likely be deleted in the near future.
Ref https://github.com/tlaplus/tlaplus-standard/issues/6
> Fix hyperlink to tlaplus-standard repo

- .github/workflows/main.yml
- test/tla/MC20_TwoPhaseTypedInv.tla
- test/tla/MC3_TwoPhaseTypedInv.tla
- test/tla/MC50_TwoPhaseTypedInv.tla
- test/tla/MC7_TwoPhaseTypedInv.tla
- test/tla/TwoPhaseTypedInv.tla
This PR adds the inductive invariant for two-phase commit. This inductive invariant was available in the early [apalache tests](https://github.com/apalache-mc/apalache-tests/blob/master/performance/two-phase/APATwoPhase.tla). Adding it to the main tests, to keep it for the future reference.
Also, fixing the checkout version in the github workflow.
> Add an inductive invariant for two-phase commit from the earlier experiments

- .unreleased/features/3134-set-simplifications.md
- test/tla/Bug931.tla
- test/tla/cli-integration-tests.md
- tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/ConstSimplifierBase.scala
- tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/ExprOptimizer.scala
- tla-pp/src/test/scala/at/forsyte/apalache/tla/pp/TestConstSimplifier.scala
Simplify set operators over literals:                                                                                   
- Set union `{1, 2, 3} \cup {4}` becomes `{1, 2, 3, 4}`
- Set difference `{3, 4} \ {3}` becomes `{4}`
- Set union `{1, 2, 3} \cap {1, 3}` becomes `{1, 3}`
- Set cardinality `Cardinality({3, 4, 5})` becomes 3
These optimizations happen to be quite useful, especially, in conjunction with the operator `..`, e.g., `0..Cardinality({ 1, 2, 3} \union {4})`.
The set of optimizations is incomplete. It would be great to have a more general rewriting framework in the future.
> Constant simplifications for sets of literals

- .unreleased/breaking-changes/3138-apalache-generate.md
- tla-io/src/main/scala/at/forsyte/apalache/io/quint/Quint.scala
- tla-io/src/test/scala/at/forsyte/apalache/io/quint/TestQuintEx.scala
Update the intermediate representation of Quint's `apalache::generate`.
> Update the Quint version of `apalache::generate`

- .unreleased/features/3141-relax-generate.md
- tla-bmcmt/src/test/scala/at/forsyte/apalache/tla/bmcmt/TestSymbStateDecoder.scala
- tla-io/src/main/scala/at/forsyte/apalache/io/json/BuilderCallByName.scala
- tla-io/src/main/scala/at/forsyte/apalache/io/quint/Quint.scala
- tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/ConstSimplifierBase.scala
- tlair/src/main/scala/at/forsyte/apalache/tla/typecomp/subbuilder/ApalacheBuilder.scala
- tlair/src/main/scala/at/forsyte/apalache/tla/typecomp/unsafe/UnsafeApalacheBuilder.scala
- tlair/src/test/scala/at/forsyte/apalache/tla/typecomp/TestApalacheBuilder.scala
Currently, `apalache::generate` expects a constant integer and throws an exception otherwise. This is counterproductive, as there are plenty of opportunities to simplify the bound expression in the preprocessing passes.
This PR relaxes the requirement to the bound expression in `apalache::generate`. If it is not reduced to a constant expression while reaching the rewriting engine, then an error is produced. Basically, we increase the set of accepted expressions, while the UX is about the same for the end user.
> Relax bound expressions in apalache::generate

- .unreleased/breaking-changes/fix-gen3147.md
- test/tla/Bug2973.tla
- test/tla/cli-integration-tests.md
- tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/analyses/ExprGradeAnalysis.scala
Closes #2973. `Apalache!Gen` is declared as uncacheable in preprocessing.
[changelog format]: https://github.com/apalache-mc/apalache/blob/main/CONTRIBUTING.md#how-to-record-a-change
> Fix 2973: `Gen` should not be cached 

- .unreleased/breaking-changes/demote-generics-error.md
- passes/src/main/scala/at/forsyte/apalache/tla/passes/typecheck/EtcTypeCheckerPassImpl.scala
- passes/src/main/scala/at/forsyte/apalache/tla/passes/typecheck/LoggingTypeCheckerListener.scala
- test/tla/cli-integration-tests.md
- tla-typechecker/src/main/scala/at/forsyte/apalache/tla/typecheck/DefaultTypeCheckerListener.scala
- tla-typechecker/src/main/scala/at/forsyte/apalache/tla/typecheck/MultiTypeCheckerListener.scala
- tla-typechecker/src/main/scala/at/forsyte/apalache/tla/typecheck/TypeCheckerListener.scala
- tla-typechecker/src/main/scala/at/forsyte/apalache/tla/typecheck/etc/EtcTypeChecker.scala
- tla-typechecker/src/main/scala/at/forsyte/apalache/tla/typecheck/integration/RecordingTypeCheckerListener.scala
- tla-typechecker/src/test/scala/at/forsyte/apalache/tla/typecheck/etc/TestEtcTypeChecker.scala
Apalache's type checker has a very useful feature that checks whether a generic type is precise, that is, it is using exactly as many variables as needed. Unfortunately, this does not play well with the Quint's typechecker, which still does not have this feature.
Now we produce a warning instead of a type error in this case. Otherwise, it is quite hard to deal with Quint specifications.
/cc: @bugarela 
[changelog format]: https://github.com/apalache-mc/apalache/blob/main/CONTRIBUTING.md#how-to-record-a-change
> Demote the generic types checker
